### ISSUE TITLE
Support for HTCondor?

### ISSUE THREAD

**Issue by minghsieh-prenetics** [picrust/picrust2#10]
Hi Gavin, Morgan, and Daniel, 

This is actually a feature or guideline request. I try to figure out how difficult is to get PICRUSt2 support [HTCondor](http://research.cs.wisc.edu/htcondor/), based on this [CERN presentation](https://youtu.be/2PRGUOxL36M).

I saw on PICRUSt [make_cluster_jobs.py](https://github.com/picrust/picrust/blob/master/picrust/make_cluster_jobs.py) and you guys have support Galaxy, SGE, and Torque job before. The particular interesting topics for me are:

1. How do you guys handle checkpoint?

Jamie (@jjmmii) and I are actually colleagues. She ran some jobs on EC2 r4.large instances with `-4` and then the memory got blow-up on the last stage (not enough memory on the last merge stage). We moved to r4.xlarge then it got passed. This makes me wonder if I would like to run PICRUSt2 with full automatically way, the checkpoint making and resuming should be unavoidable. Just wonder how you guys handle this or previously you guys get Galaxy to handle this.

2. How do you guys balance from CPU and memory usage as reference of splitting a task to small jobs?

Continue on # 1, we try to come out some formula to estimate how many memory / CPU ratio, and how to manually specify the argument of a task to split multiple small jobs. If we fail to do so, no matter we submit to VM based scheduler (SGE, Torque, or AWS EMR) or container based scheduler (Kubernetes, Mesos, or AWS ECS, Google GKE) the outcome won't be good if we don't guard with checkpoint.

Thanks and have a weekend.

**Comment by gavinmdouglas** [comment]
Thanks for your interest!

I actually have no experience with these questions and currently we have no plans to make PICRUSt2 easy to execute on a cluster unfortunately. However, this could change in the future and if someone wants to contribute code who does have experience with these issues that would certainly be welcome!

Sorry I can't be of more help.

Gavin

**Comment by minghsieh-prenetics** [comment]
Thanks Gavin. Let's close it for now. // Ming
