### ISSUE TITLE
Is there  any other level in the output MetaCyc pathway ?

### ISSUE THREAD

**Issue by Eve-Cheung** [picrust/picrust2#100]
Hey！There are several levels in KEGG pathway and I am wondering if there is any other level in MetaCyc.  What should I do if I don't want the default output pathway which is specific and just get the rough predicted pathway?

**Comment by gavinmdouglas** [comment]
Hey @Eve-Cheung,

There is a hierarchy for MetaCyc pathways as well, which you can see here: https://metacyc.org/META/class-tree?object=Pathways

It's not clear to me whether this hierarchy is analogous to the BRITE hierarchy in that pathways can be summarized at three specific levels, but at the very least this information can be used for grouping pathways into broader categories.

Best,

Gavin

**Comment by Eve-Cheung** [comment]
Thanks for your response~ Moreover,  is there any code that can easily make the grouping pathways into broader categories instead of checking the information on the website of MetaCyc.

**Comment by gavinmdouglas** [comment]
No sorry - I haven't formatted the MetaCyc hierarchy to be a table or written a script to do that.

**Comment by Eve-Cheung** [comment]
OK, I see that.  Could you recommend me some  visualization tools jiust like R packages  if I want to draw a MetaCyc pathway map?

**Comment by gavinmdouglas** [comment]
I'm not an expert on visualizing pathways, but there are tools on the MetaCyc website and you might want to check out this R package: https://rdrr.io/cran/RbioRXN/

**Comment by Eve-Cheung** [comment]
It is so nice of you! Thank you sincerely~

**Comment by Jiung-Wen** [comment]
Hi @Eve-Cheung ,
You can download the mapfiles [here](https://github.com/Jiung-Wen/picrust_mapping) and use picrust2's add_description script to group MetaCyc pathway.
Hope it helps.
Jiung-Wen

**Comment by Eve-Cheung** [comment]
Thank you very much!! 
You are so so so so so nice! Give a like!! wonderful!  
------------------ 原始邮件 ------------------
发件人: "Jiung-Wen"<notifications@github.com>;
发送时间: 2019年9月14日(星期六) 下午4:13
收件人: "picrust/picrust2"<picrust2@noreply.github.com>;
抄送: "455037786"<455037786@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [picrust/picrust2] Is there  any other level in the outputMetaCyc pathway ? (#100)




Hi @Eve-Cheung ,
 You can download the mapfiles here and use picrust2's add_description script to group MetaCyc pathway.
 Hope it helps.
 Jiung-Wen
