### ISSUE TITLE
ValueError: This input file was not found: EC

### ISSUE THREAD

**Issue by lihongyi123** [picrust/picrust2#101]
HI Gavin

I installed a latest version of PICRUSt2 some days ago and today I found it did not worked with “--custom_trait_tables” arg. I have test it with a older version and it worked.

 The error message that I got:

(picrust2) [psnadmin@login MbPL201909137]$ picrust2_pipeline.py -s 3_sOTU/rep_seqs_filtered.fna -i 3_sOTU/table_filtered.biom -o ~/29_functional_composition6 -p 16 --custom_trait_tables /PERSONALBIO/Work/Mb/Mb07/database/qiime2/picrust2_2.2.0_b/default_files/fungi/ec_ITS_counts.txt.gz --min_reads 1 -r /PERSONALBIO/Work/Mb/Mb07/database/qiime2/picrust2_2.2.0_b/default_files/fungi/fungi_ITS --marker_gene_table /PERSONALBIO/Work/Mb/Mb07/database/qiime2/picrust2_2.2.0_b/default_files/fungi/ITS_counts.txt.gz --pathway_map /PERSONALBIO/Work/Mb/Mb07/database/qiime2/picrust2_2.2.0_b/default_files/pathway_mapfiles/metacyc_path2rxn_struc_filt_fungi_present.txt 
Traceback (most recent call last):
  File "/PERSONALBIO/Work/Mb/Mb07/.conda/envs/picrust2/bin/picrust2_pipeline.py", line 258, in <module>
    main()
  File "/PERSONALBIO/Work/Mb/Mb07/.conda/envs/picrust2/bin/picrust2_pipeline.py", line 249, in main
    verbose=args.verbose)
  File "/PERSONALBIO/Work/Mb/Mb07/.conda/envs/picrust2/lib/python3.6/site-packages/picrust2/pipeline.py", line 121, in full_pipeline
    check_files_exist(files2check)
  File "/PERSONALBIO/Work/Mb/Mb07/.conda/envs/picrust2/lib/python3.6/site-packages/picrust2/util.py", line 387, in check_files_exist
    raise ValueError("This input file was not found: " + missing_files[0])
ValueError: This input file was not found: EC

if I used the --in_traits argument instead for 16S data, it worked。

**Comment by lihongyi123** [comment]
oh~~~

I found that I shoud specified the “ --reaction_func “ same as the “--custom_trait_tables ” . And it worked now.

**Comment by gavinmdouglas** [comment]
Glad to hear this was resolved!
