### ISSUE TITLE
determine the low depth samples

### ISSUE THREAD

**Issue by ManarRashad** [picrust/picrust2#103]
Hi,
I am new in using this tool and overall the bioinformatics field
So could you help me to understand the number of observation in the output of:
biom summarize-table -i table.biom
and how I can determine through this output the low depth samples

Look forward to hearing from you
Thanks

**Comment by gavinmdouglas** [comment]
Hey @ManarRashad,

`biom` is a dependency of PICRUSt2 and isn't written by me just so you know. You can read more about using the biom tools and summarizing table [here](http://biom-format.org/documentation/summarizing_biom_tables.html).

The number of observations refers to the number of different features, whether they be operational taxonomic units, amplicon sequence variants, etc. These are the rows in a BIOM table and the samples are the columns.

You can see the depth per sample under `Counts/sample detail:`. What constitutes a low-depth sample can depend on the environment you're profiling. For instance, if there are only 3 taxa in the community then 100 reads would probably be sufficient, but for the human gut commonly at least 3000-4000 reads are required for each sample. There is no single cut-off accepted by the field however. You might also want to look at rarefaction curves to help determine the minimum depth requires for your environment of interest (see this [tutorial](https://github.com/LangilleLab/microbiome_helper/wiki/Amplicon-SOP-v2-(qiime2-2019.7)#43-exclude-low-depth-samples)).

Hopefully that helps!

Gavin

**Comment by ManarRashad** [comment]
Thanks a lot for clear explanation
