### ISSUE TITLE
Please allow to overwrite output directory

### ISSUE THREAD

**Issue by abalter** [picrust/picrust2#105]
As it is, you need to delete the output directory each time you run the code.

I understand the inclination to make it so the user can't overwrite their results. But, I think this is best left in the hands of the user.

In my particular case, I have a directory where I have other items and also want to include the picrust2 output. As it stands, I cannot do this.

**Comment by gavinmdouglas** [comment]
Hi @abalter,

Thanks for the suggestion, but I would prefer not to make this change to limit possible overwriting and also to keep all of the many intermediate files organized in a single directory and separated from unrelated files. The files can be moved afterwards if needed.

**Comment by abalter** [comment]
Ok. I added code to remove the picrust_out folder before each run.
