### ISSUE TITLE
is picrust2 suitable for pacbio 16S full-length data?

### ISSUE THREAD

**Issue by wangzlab** [picrust/picrust2#106]
Dear all,

I have run the picrust2 pipeline on some pacbio 16S full-length amplicon data (processed using dada2 first to generate ASVs) and obtained some results. I'm just not sure how accurate the results are and if the program were suitable for pacbio long reads at all? I have done some search and haven't found anyone testing picrust2 on pacbio data...

Any thoughts or comments on the performance of picrust2 on pacbio 16S FL data will be much appreciated.

Thanks,
Zhang

**Comment by gavinmdouglas** [comment]
See here for a discussion of the cross-post of this question: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/picrust-users/grRxcTL96ag/uq9qJ-nIBgAJ
