### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by restivve** [picrust/picrust2#109]
Hi, 

I received an error when trying to pull in my 16s rRNA fasta file into picrust2. I do get some filed in my output but I didn't get victoria.tre that I need for the next step.

I ran this: 
source activate picrust2
place_seqs.py
	-s rep_set.fna 
	-o victoria.tre 
	-p 10 \
	--placement_working

Error running this command:
epa-ng --tree /home/qiime2/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa victoria_tre/ref_seqs_hmmalign.fasta --query victoria_tre/study_seqs_hmmalign.fasta --chunk-size 5000 -T 10 -m /home/qiime2/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w victoria_tre/epa_out --filter-acc-lwr 0.99 --filter-max 100

Standard output of failed command:
"INFO Selected: Output dir: victoria_tre/epa_out/
INFO Selected: Query file: victoria_tre/study_seqs_hmmalign.fasta
INFO Selected: Tree file: /home/qiime2/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre
INFO Selected: Reference MSA: victoria_tre/ref_seqs_hmmalign.fasta
INFO Selected: Filtering by accumulated threshold: 0.99
INFO Selected: Maximum number of placements per query: 100
INFO Selected: Automatic switching of use of per rate scalers
INFO Selected: Preserving the root of the input tree
INFO Selected: Specified model file: /home/qiime2/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model
INFO    Rate heterogeneity: GAMMA (4 cats, mean),  alpha: 0.453141 (user),  weights&rates: (0.25,0.0250674) (0.25,0.220229) (0.25,0.782933) (0.25,2.97177) 
        Base frequencies (user): 0.229585 0.22008 0.298596 0.251739 
        Substitution rates (user): 1.00319 2.79077 1.5301 0.87441 3.83966 1
INFO Selected: Reading queries in chunks of: 5000
INFO Selected: Using threads: 10
INFO     ______ ____   ___           _   __ ______
        / ____// __ \ /   |         / | / // ____/
       / __/  / /_/ // /| | ______ /  |/ // / __  
      / /___ / ____// ___ |/_____// /|  // /_/ /  
     /_____//_/    /_/  |_|      /_/ |_/ \____/ (v0.3.5)
INFO Output file: victoria_tre/epa_out/epa_result.jplace

**Comment by gavinmdouglas** [comment]
Hey @restivve,

Usually EPA-ng fails if you don't have enough RAM (at least 16 GB, but sometimes more is needed). You could also try using fewer threads since this might decrease the overall memory usage as well.


Best,

Gavin

**Comment by restivve** [comment]
Hi @gavinmdouglas,

Thank you for the super quick response. What do you mean by using fewer threads?

Thank you,
Victoria

**Comment by gavinmdouglas** [comment]
No worries - by threads I mean the number of processors (the `-p` option) which is also used as the option for the number of threads when running EPA-ng.

**Comment by restivve** [comment]
Is there any difference in the output using a lower -p option?

**Comment by gavinmdouglas** [comment]
No the `-p` option just affects the speed and memory usage, but not the output.

**Comment by restivve** [comment]
Thanks! 

The Linux I'm on has 23.4 GB of RAM, and currently ~7 GB is being used by someone else. The script used about 14 GB to run. I still am getting the same error, even with -p 1 instead of -p 10.

(picrust2) qiime2@sl1pcomputer:~/Disk1/Victoria$ place_seqs.py -s rep_set.fna -o  placed_seqs.tre -p 1 --intermediate placement_working

Error running this command:
epa-ng --tree /home/qiime2/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa placement_working/ref_seqs_hmmalign.fasta --query placement_working/study_seqs_hmmalign.fasta --chunk-size 5000 -T 1 -m /home/qiime2/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w placement_working/epa_out --filter-acc-lwr 0.99 --filter-max 100

Standard output of failed command:
"INFO Selected: Output dir: placement_working/epa_out/
INFO Selected: Query file: placement_working/study_seqs_hmmalign.fasta
INFO Selected: Tree file: /home/qiime2/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre
INFO Selected: Reference MSA: placement_working/ref_seqs_hmmalign.fasta
INFO Selected: Filtering by accumulated threshold: 0.99
INFO Selected: Maximum number of placements per query: 100
INFO Selected: Automatic switching of use of per rate scalers
INFO Selected: Preserving the root of the input tree
INFO Selected: Specified model file: /home/qiime2/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model
INFO    Rate heterogeneity: GAMMA (4 cats, mean),  alpha: 0.453141 (user),  weights&rates: (0.25,0.0250674) (0.25,0.220229) (0.25,0.782933) (0.25,2.97177) 
        Base frequencies (user): 0.229585 0.22008 0.298596 0.251739 
        Substitution rates (user): 1.00319 2.79077 1.5301 0.87441 3.83966 1
INFO Selected: Reading queries in chunks of: 5000
INFO Selected: Using threads: 1
INFO     ______ ____   ___           _   __ ______
        / ____// __ \ /   |         / | / // ____/
       / __/  / /_/ // /| | ______ /  |/ // / __  
      / /___ / ____// ___ |/_____// /|  // /_/ /  
     /_____//_/    /_/  |_|      /_/ |_/ \____/ (v0.3.5)
INFO Output file: placement_working/epa_out/epa_result.jplace
"

Standard error of failed command:
""

**Comment by gavinmdouglas** [comment]
My best guess is that you're running into memory issues and I bet it will work once more memory is free. However, you can also try placing your ASVs with SEPP instead of EPA-ng. The QIIME 2 commands to run this are described here: https://github.com/picrust/picrust2/wiki/Swapping-in-SEPP-for-read-placement-with-q2-picrust2#q2-picrust2-running-example

**Comment by restivve** [comment]
So first download SEPP: https://github.com/smirarab/sepp/tree/master/sepp-package 

Then I can run this:

SEPP rep-seqs.qza  -s rep_set.fna -o placed_seqs.tre -p 1 --intermediate placement_working

**Comment by gavinmdouglas** [comment]
No the syntax for running SEPP is different (i.e. the options like `-s` and `-p` etc are simply options I defined for the `place_seqs.py` script and SEPP is an independent tool). I've only used SEPP as part of QIIME 2, which is  done using the `qiime fragment-insertion sepp` command on the tutorial I linked you to. Note that to run QIIME 2 commands on your files you first need to import your data as QIIME 2 artifacts using `qiime tools import` - see https://docs.qiime2.org/2019.10/tutorials/importing/)

**Comment by restivve** [comment]
Hi Gavin, 

I have now finished getting the input files I need to use sepp for picrust. I had to update my qiime2 for `qiime fragment-insertion sepp` to work. The call works, but it doesn't like the input for reference-alignment or reference-phylogeny (which are direct downloads from the tutorial: https://github.com/picrust/picrust2/wiki/Swapping-in-SEPP-for-read-placement-with-q2-picrust2). Here is the call:

get http://kronos.pharmacology.dal.ca/public_files/tutorial_datasets/picrust2_tutorial_files/reference.fna.qza

wget http://kronos.pharmacology.dal.ca/public_files/tutorial_datasets/picrust2_tutorial_files/reference.tre.qza

qiime fragment-insertion sepp --i-representative-sequences mammal_seqs.qza \
                              --p-threads 1 --i-reference-alignment reference.fna.qza \
                              --i-reference-phylogeny reference.tre.qza \
                              --output-dir tutorial_placed_out

Instead it is asking for reference-database. Do you know what I should use for this?

**Comment by gavinmdouglas** [comment]
Hey @restivve,

It looks like that command has changed in the latest QIIME 2 version and I haven't tested it out yet. I'll update the tutorial soon with instructions for the latest version, but for now you'll have to use qiime2-2019.7

**Comment by restivve** [comment]
Hi Gavin, 

I'm actually using qiime-2019.10, does it only work with 2019.7?

**Comment by gavinmdouglas** [comment]
Yes the plugin just works with 2019.7 currently, see: https://library.qiime2.org/plugins/q2-picrust2/13/
