### ISSUE TITLE
There is no package called ‘castor’

### ISSUE THREAD

**Issue by BoraKim2018** [picrust/picrust2#112]
Hello, I am following picrust2 tutorial but I had problem at the hsp.py step as below: 
``
(picrust2) [bkim@genseq-cn00 chemerin_16S]$ hsp.py -i 16S -t out.tre -o marker_predicted_and_nsti.tsv.gz -p 1 -n

Error running this command:
Rscript /home/bkim/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/Rscripts/castor_nsti.R out.tre /tmp/tmp5ivcx3tb/known_tips.txt /tmp/tmp5ivcx3tb/nsti_out.txt

Standard output of failed command:
""

Standard error of failed command:
"Error in library(castor, quietly = TRUE) :
  there is no package called ‘castor’
Execution halted
"
``
I re-installed picrust2 and also updated conda, but I have still same problem. 
I saw package 'castor' installed as 'r-castor' in NEW package list. 
Would it be the reason of this problem?
I would really appreciate if you can help me.

**Comment by gavinmdouglas** [comment]
Hey @BoraKim2018,

What command(s) did you use to install PICRUSt2?

The recipe has always been called r-castor actually (that's the convention for R packages distributed by conda), but the actual library is castor, so I don't think that's related to this issue.

You can take a look at `conda list | less` which will show you all the packages and their versions in your current conda environment... Hopefully that will help us figure out what's going on.

**Comment by BoraKim2018** [comment]
@gavinmdouglas Thank you very much for your quick response. 
I installed picrust2 as described on wiki, 
``
conda create -n picrust2 -c bioconda -c conda-forge picrust2=2.2.0_b
``

And here is list of packages: 


packages in environment at /home/bkim/miniconda3/envs/picrust2:

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
binutils_impl_linux-64    2.33.1               he1b5a44_7    conda-forge
binutils_linux-64         2.33.1              h9595d00_16    conda-forge
biom-format               2.1.7           py36hc1659b7_1002    conda-forge
bwidget                   1.9.14                        0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
click                     7.0                        py_0    conda-forge
coverage                  5.0.3            py36h516909a_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
epa-ng                    0.3.5                he860b03_0    bioconda
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
future                    0.18.2                   py36_0    conda-forge
gappa                     0.2.0                he860b03_0    bioconda
gcc_impl_linux-64         7.3.0                hd420e75_4    conda-forge
gcc_linux-64              7.3.0               h553295d_16    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_4    conda-forge
gfortran_linux-64         7.3.0               h553295d_16    conda-forge
glib                      2.58.3          py36h6f030ca_1002    conda-forge
glpk                      4.65              he80fd80_1002    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_4    conda-forge
gxx_linux-64              7.3.0               h553295d_16    conda-forge
h5py                      2.9.0           nompi_py36h513d04c_1104    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
hmmer                     3.2.1                he1b5a44_2    bioconda
icu                       64.2                 he1b5a44_1    conda-forge
importlib_metadata        1.4.0                    py36_0    conda-forge
joblib                    0.13.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libidn2                   2.3.0                h516909a_0    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
make                      4.2.1             h14c3975_2004    conda-forge
more-itertools            8.1.0                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.3           py36he5ce36f_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pandas                    0.24.2           py36hb3f55d8_1    conda-forge
pango                     1.42.4               ha030887_1    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
picrust2                  2.1.4_b                    py_0    bioconda
pip                       19.3.1                   py36_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
pytest                    4.4.1                    py36_0    conda-forge
pytest-cov                2.6.1                      py_0    conda-forge
python                    3.6.7             h357f687_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
r-base                    3.5.1             hc461eb7_1012    conda-forge
r-castor                  1.3.6            r351h0357c0b_0    conda-forge
r-naturalsort             0.1.3           r35h6115d3f_1002    conda-forge
r-nloptr                  1.2.1             r35h0357c0b_1    conda-forge
r-rcpp                    1.0.3             r35h0357c0b_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scipy                     1.2.1            py36h09a28d5_1    conda-forge
setuptools                45.0.0                   py36_1    conda-forge
six                       1.14.0                   py36_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tktable                   2.10                 h555a92e_3    conda-forge
wget                      1.20.1               h22169c7_0    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zipp                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge  






And my conda info is as: 


 active environment : picrust2
    active env location : /home/bkim/miniconda3/envs/picrust2
            shell level : 2
       user config file : /home/bkim/.condarc
 populated config files :
          conda version : 4.8.1
    conda-build version : not installed
         python version : 3.8.1.final.0
       virtual packages : __glibc=2.12
       base environment : /home/bkim/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/bkim/miniconda3/pkgs
                          /home/bkim/.conda/pkgs
       envs directories : /home/bkim/miniconda3/envs
                          /home/bkim/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.1 requests/2.22.0 CPython/3.8.1 Linux/2.6.32-754.10.1.el6.x86_64 centos/6.10 glibc/2.12
                UID:GID : 1061:500
             netrc file : None
           offline mode : False



I also tried ``picrust2_pipeline.py`` but got same error.

**Comment by gavinmdouglas** [comment]
Hey @BoraKim2018,

Hmm it looks like castor is installed.

Can you post the output of `echo $PATH` and `which R` when the picrust2 environment is activated? I'm concerned that although castor is installed in the R instance installed in the picrust2 environment that for some reason you're using a different R instance. This could happen if a different folder containing R was earlier in your $PATH, which hopefully those commands will help us figure out.

Best,

Gavin

**Comment by BoraKim2018** [comment]
Hi Gavin, thank you for your help. 
Indeed, seems like R path is earlier than picrust env: 

(picrust2) [bkim@genseq-cn00 ~]$ which R
/mad/bin/R

(picrust2) [bkim@genseq-cn00 ~]$ echo $PATH
/mad/bin:/home/bkim/miniconda3/envs/picrust2/bin:/home/bkim/miniconda3/condabin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin


In this case, do I have to remove R and re-install picrust?

**Comment by gavinmdouglas** [comment]
No you just need to update your PATH variable so that "/home/bkim/miniconda3/envs/picrust2/bin" is first. I would recommend you look in your `.bashrc` and `.profile` files to see how `/mad/bin` is being added currently and change it, because this will likely cause issues for all your conda environments.

**Comment by BoraKim2018** [comment]
@gavinmdouglas, Thank you very much for your help. I am sorry for late update, but unfortunately, I couldn't manage to change path. Because I was using university server and R PATH was created by university. I asked my server manager if I have an authority to do it, but I didn't receive any response yet. I will try to change path if I can and keep you updated.

**Comment by mgalland** [comment]
Hello @BoraKim2018 
A dear friend of mine had the same issue. Indeed the solution from @gavinmdouglas is the correct one. The default `/mad/bin` folder where default 

I modified the `~/.bash_profile` file using `nano`:

1. I've commented out the default `/mad/bin` modifications to the $PATH. 
2. I've then added the path to your folder where you have your miniconda3 environments. 
3. Don't forget to export this new PATH and source it `source ~./.bash_profile` 

```
# User specific environment and startup programs
#if [ -d /mad/bin ]; then
#   PATH=/mad/bin:${PATH}
#fi
#if [ -d ~/bin ]; then
#   PATH=$HOME/bin:${PATH}
#fi

PATH="/home/<yourusername>/miniconda3/bin:$PATH"
export PATH

```

This solved the castor issue.
