### ISSUE TITLE
python command not found

### ISSUE THREAD

**Issue by fanwayne** [picrust/picrust2#120]
When I was tring below code on shell after activating the picrust2 envrionment, it just output the error: "zsh: command not found: place_seqs.py"

> place_seqs.py -s ../seqs.fna -o out.tre -p 1 \
>               --intermediate intermediate/place_seqs

How can I run this directly on shell? Is there anything wrong with my installation? Is it necessary to add severall paths into the system PATH variable?

I was running it on macOS catalina 10.15.3 with picrust2 (2.3.0_b) installed.

**Comment by gavinmdouglas** [comment]
Hi there,

You shouldn’t need to change your $PATH variable. How did you install the tool? If you installed from source you can try running the unittests with “pytest” in the picrust2 directory.

Could you print out your $PATH variable?


Thanks,

Gavin

**Comment by fanwayne** [comment]
> Hi there,
> 
> You shouldn’t need to change your $PATH variable. How did you install the tool? If you installed from source you can try running the unittests with “pytest” in the picrust2 directory.
> 
> Could you print out your $PATH variable?
> 
> Thanks,
> 
> Gavin

Hi, @gavinmdouglas . Many thanks for your suppot. It seems that I could not download all the dependancies successfully. I switched to the bioconda version of picrust2 and changed all the default channels. It now works well.
