### ISSUE TITLE
The new version seems to have some problem about the --min_align option

### ISSUE THREAD

**Issue by LuffyLuffy** [picrust/picrust2#122]
Warning - 193 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.1 aligning to reference sequences). These input sequences will not be placed and will be excluded from downstream steps.

almost all 16s seqs were treated as aligned poorly to reference sequences ones. But old version ,such as 2.1.3 seems to work well.

**Comment by gavinmdouglas** [comment]
Hey @LuffyLuffy,

This is probably the same issue described here: https://github.com/picrust/picrust2/wiki/Major-Bug-Reports-and-Announcements#bug-report-very-poorly-aligning-input-sequences-not-treated-correctly-prior-to-v230-b. There's a good chance your input sequences are on the negative strand and aren't being aligned properly.


Sorry for the inconvenience,

Gavin

**Comment by LuffyLuffy** [comment]
> Hey @LuffyLuffy,
> 
> This is probably the same issue described here: https://github.com/picrust/picrust2/wiki/Major-Bug-Reports-and-Announcements#bug-report-very-poorly-aligning-input-sequences-not-treated-correctly-prior-to-v230-b. There's a good chance your input sequences are on the negative strand and aren't being aligned properly.
> 
> Sorry for the inconvenience,
> 
> Gavin

Great! 
In case some one may need this, use seqtk to get reverse complementary seqs, then using picrust2_pipeline.py.

 seqtk seq -r  otus.fa.format.fasta  > otus_rc.fa

**Comment by hjdong** [comment]
> Hey @LuffyLuffy,
> 
> This is probably the same issue described here: https://github.com/picrust/picrust2/wiki/Major-Bug-Reports-and-Announcements#bug-report-very-poorly-aligning-input-sequences-not-treated-correctly-prior-to-v230-b. There's a good chance your input sequences are on the negative strand and aren't being aligned properly.
> 
> Sorry for the inconvenience,
> 
> Gavin

I have the same problem and use seqtk to get reverse complementary seqs to  solve the problem.

Sample type：Mouse feces 、16S rRNA V3V4
It seems to have something  with the sample type.

**Comment by j0eschm0** [comment]
I am running into the same problem, but unfortunately the using seqtk didn't help. Is there anything else that can be done? I generate the sequence data in Mothur, could that be the problem?

**Comment by wyanren** [comment]
The same as j0eschm0. Even i reverse my fasta, still report this error.

**Comment by gavinmdouglas** [comment]
Hi @wyanren,

Sorry to hear that - feel free to email your file to me at <img width="144" alt="gmail_screenshot" src="https://user-images.githubusercontent.com/12489683/99812510-eec68b80-2b1c-11eb-96d6-c43d189865b4.png"> and I can help troubleshoot.


All the best,

Gavin

**Comment by shashibisht9** [comment]
Hi,
I am also getting the same Warning - 47 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences). These input sequences will not be placed and will be excluded from downstream steps.

This is the set of poorly aligned input sequences to be excluded

1 of 2294 ASVs were above the max NSTI cut-off of 2.0 and were removed from the downstream analyses.
1 of 2294 ASVs were above the max NSTI cut-off of 2.0 and were removed from the downstream analyses.

Reverse complementing sequences with seqtk didn't help. Sequence file is generated using DADA2 pipeline.

**Comment by gavinmdouglas** [comment]
Hi @shashibisht9,

I'm guessing that those 47 sequences are problematic (maybe 18S or total junk sequences for instance). You can BLASTN them online to get an idea of what they are. Either way, because the vast majority of your sequences could be aligned this isn't a problem with your dataset overall.


Cheers,

Gavin

**Comment by shashibisht9** [comment]
Yes. All of them are mating to some Uncultured bacterium clone. This could be the reason of poor alignment. Thank you for your suggestion.

**Comment by Mara-93** [comment]
Hi @gavinmdouglas, 

I am trying to use PICRUSt (version 2.3.0_b) for my data, generated using the NG-Tax pipeline. Also for me, all OTUs are poorly aligned to reference sequences (except for 3 OTUs out of 1390). I had no problems with older versions of PICRUSt (and data also generated using NG-Tax). Any chance you could help me troubleshooting? Something else I could still try?

Thank you very much!
Mara

**Comment by gavinmdouglas** [comment]
Hi @Mara-93,

Have you confirmed whether the sequences are on the positive strand? That's the most common reason for this problem.

If that's not the problem then sure I can take a look at your sequences if you email them to <img width="144" alt="gmail_screenshot" src="https://user-images.githubusercontent.com/12489683/115713114-04e6ab00-a34c-11eb-95e5-e16f28c03370.png">


Cheers,

Gavin

**Comment by marwa38** [comment]
Hi Gavin @gavinmdouglas 
For me, reverse complementing sequences with seqtk didn't help.
Before reverse complementing:
I have a problem with poorly aligned ASVs? do you think that this is too many ASVs lost
I aligned against silva (not greengenes) and used dada2 for denoising
`Warning - 363 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences). These input sequences will not be placed and will be excluded from downstream st eps.`
![image](https://user-images.githubusercontent.com/68851733/151331861-57995228-bd03-40fd-aeee-c2db24afc3d4.png)

**55 of 2474 ASVs were above the max NSTI cut-off of 2.0 and were removed.

55 of 2474 ASVs were above the max NSTI cut-off of 2.0 and were removed.
**

after reverse complementing:
 ```
picrust2_pipeline.py -s ASVs_rc.fa -i ASVs_counts.tsv -o                                                                                                                      picrust2_out_pipeline_rc -p 19
Warning - 2869 input sequences aligned poorly to reference sequences (--min_alig                                                                                                                     n option specified a minimum proportion of 0.8 aligning to reference sequences).                                                                                                                      These input sequences will not be placed and will be excluded from downstream steps.

0 of 2 ASVs were above the max NSTI cut-off of 2.0 and were removed.
Warning: fewer than half of the sequence ids overlap between the input files.

0 of 2 ASVs were above the max NSTI cut-off of 2.0 and were removed.
Warning: fewer than half of the sequence ids overlap between the input files.
```
my main post: #233

**Comment by mimba30** [comment]
Hi,

I am having the same issue.
This is the error message I am getting:
Stopping - all 44545 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences).

I processed my 16S V4 rRNA data in mothur.

I've tried reverse compliment and that doesn't work and there's no extra white space in the sequence IDs as each sequence is named with >Otu00001, >Otu00002 etc.

I am new to picrust2 so any help would be much appreciated.

**Comment by j0eschm0** [comment]
@mimba30 

For my analysis, I had to reformat my mother FASTA file. You can probably do this a few ways, but what I believe worked for me was using the get.oturep command (rename=true, method=abundance) using my fasta and list file. I had to remove all other characters in the name (e.x. >Otu00001 convert to 00001). Good luck and I hope this helps!

**Comment by mimba30** [comment]
Thanks for your response. I tried your suggestion but still got the same error (Stopping - all 44545 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences)). 

Is there anything else I can try?

**Comment by mimba30** [comment]
Thanks for your response! I tried your suggestion and it still came up with the same error message. 

The sequences in my fasta file look like this:
>00001
GT-G-C-CA-G-C--A--G-C--CG-C---GG--TA-AT--AC---GT-AG-GTG-----GCG-A-G-C-G--TT--GT-C-CGG-AA--TT-A--T-T--GG-GC--GT-A--AA-GA-GC-AT--G-TA-G-G-C-G----G--T-TT-T-T-T--AA-G-T-C-T-G-G-A-G--TG--A-AA-AT--G-C-GG-G-G-------CT-C-AA--C-C-C-C-G-T-A--T---G-G--C-T-C-T----G--GA-T-A-C-T--G-G--AA--G-A-C-T-T-G-A-G-T-G-C-AG----GA-G-A-------G-G-A-A---AG-G----GG-A--ATT--C-C-C-A-GT--GT-A-G-CG-GT--G-----A-AA-----TG-C-GT-AG--AT-A-TT--------G-G---G-A-G-G-A-AC-A-CC--AG-T-G--GC-GAA-G--G-C-G-C--C-T-T-T--CTG-G--AC-T-G---T-G-T-C-T--GA--CG--C-T-G--A-GA--T-G-CG-A-AA-G-C--C-AG-GG-T--AG-C-G-AA--CG--GG-AT-TA-G-ATA-C-C-C-C--G-GTA-G-TC-C

I'm wondering if the dashes in the sequence are causing the problem as the tutorial fasta file has no dashes or gaps in the sequences?

**Comment by gavinmdouglas** [comment]
Hi there,

Yes it's expecting unaligned sequences, so that could be a problem. Also make sure that there is a ">" at the start of each headline. It's possible that the number format for the sequence ids is causing problems too. You could add "seq" in front of each number to see if that makes a difference, although I don't think that should be a problem.

Cheers,

Gavin

**Comment by mimba30** [comment]
Hi @gavinmdouglas,

I managed to make my fasta file run in the sequence placement part of the pipeline, however I can't work out how to make my biom file IDs match the sequence IDs in the unaligned sequence fasta file. The biom file IDs are Otu00001 etc. where as the fasta file that worked has sequence IDs MISEQ_159_000000000-JJ3F9_1_1108_20027_18877. 

I tried using the get.oturep command in mothur to generate a fasta file containing the representative sequence for each OTU so the IDs would match. However, when I try to run this fasta file in picrust2, the same error as before about sequences aligning poorly comes up.

Any idea how to change the biom file Otu IDs to sequence IDs so they match the fasta file? 

Thanks.

**Comment by gavinmdouglas** [comment]
I'm not familiar with any tool that would do that for you - I think you might have to write some custom code in order to change the ids. For instance, you could convert the biom table to TSV format and load it into R and then convert the ids yourself. Sorry I can't be more specific!


Cheers,

Gavin

**Comment by mimba30** [comment]
Thanks for getting back to me @gavinmdouglas. I think perhaps I am using the wrong mothur output files.

@j0eschm0 - You mentioned you had successfully used your mothur output files in PICRUST2. Would you mind sharing which fasta file you used from the mothur pipeline and with what parameters did you make your biom file?

**Comment by mimba30** [comment]
It's alright. I realised I hadn't tried reverse complimenting my get.oturep fasta file as I assumed the representative sequences were on the positive strand like the original sequences. After reverse complimenting the get.oturep fasta file, it seems to be working now with only 1 representative sequence aligning poorly.

**Comment by gavinmdouglas** [comment]
Hi @EJS01,

The default database is for 16S sequences, which is why you are running into that problem. Please see here for how to run ITS data (and the major additional caveats of this approach): https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-a-custom-or-non-default-database-such-as-the-fungi-18s-and-its-databases

**Comment by R-Wright-1** [comment]
Hi Gordon,

Could you try running with a very low min_align threshold (e.g. 0.1)? When I run a few of those sequences in NCBI BLAST, they do come up as uncultured with no species assignment so it does seem possible that they aren't well represented in the PICRUSt2 database. Were you able to assign species names to them with your analysis pipeline? 

Robyn

**Comment by R-Wright-1** [comment]
Hmm that's interesting. Could you try creating a BLAST database with the PICRUSt2 16S sequences and running yours against it? That should clear up whether they actually don't match at all or not. If you're not sure how to do that, then if you want to send me your files then I can try. 

Robyn

**Comment by gcuster1991** [comment]
Hi Robyn,
I am not sure how to do that. I'm happy to share the files if you're willing to give it a shot. How would you like me to share? 

Cheers,
Gordon

**Comment by R-Wright-1** [comment]
Assuming they're not too big, do you want to email them to me? robyn.wright@dal.ca

Robyn

**Comment by gcuster1991** [comment]
Files sent. Thanks for the help!
Cheers,
Gordon

**Comment by R-Wright-1** [comment]
Just in case anyone comes across this issue, it was due to duplicated ASV names in the fasta file (but the feature table didn't have duplicates). I've now added to the FAQ on the "all X input sequences aligned poorly to reference sequences" error that duplicate ASV names can cause this error.
