### ISSUE TITLE
picrust2 for multiple regions 16S metagenomics

### ISSUE THREAD

**Issue by hvanphucs** [picrust/picrust2#124]
Can I analyze the 16S metagenomics samples  from multiple 16S regions with picrust2? What difference when I use only one region and multiple regions for analysis. Thank you for any help

**Comment by gavinmdouglas** [comment]
Hi there,

My focus has predominately been on testing one region at a time. You can use multiple regions, but you should then expect more biases as different parts ot the 16S will be placed into the reference tree with different efficacies.


Best,

Gavin
