### ISSUE TITLE
Relative abundance pathway (%)

### ISSUE THREAD

**Issue by hvanphucs** [picrust/picrust2#125]
Dear,
I have received this file from running command  **pathway_pipeline.py**.                                                                                                                                                                                          But the result for the samples is not% units. I can calculate the relative distribution rate (%) by dividing the data by each pathway by the total data for each sample. Is this true when I want to compare samples with each other? Thank you for any help.

![image](https://user-images.githubusercontent.com/47340777/85397147-3c929400-b57d-11ea-96f3-a03bc48195de.png)

**Comment by gavinmdouglas** [comment]
Yes the data is in similar units as the gene family metagenome tables - i.e. the abundance of each gene multiplied by the corrected relative abundance of each taxon that encodes the gene. You can certainly convert the data to relative abundance if that's how you prefer to analyze it.
