### ISSUE TITLE
ValueError: No sequence ids overlap between all three of the input files

### ISSUE THREAD

**Issue by MarwaElnaiem** [picrust/picrust2#126]
Dear all, 
I'm running PICRUSt2 and following the steps of the tutorial available on GitHub page. However, I obtained an error when running the metagenome prediction step. 

The error was as follows

`14 of 5178 ASVs were above the max NSTI cut-off of 2.0 and were removed.
Traceback (most recent call last):
  File "/home/marwa/miniconda3/envs/picrust2/bin/metagenome_pipeline.py", line 122, in <module>
    main()
  File "/home/marwa/miniconda3/envs/picrust2/bin/metagenome_pipeline.py", line 104, in main
    skip_norm=args.skip_norm)
  File "/home/marwa/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/metagenome_pipeline.py", line 66, in run_metagenome_pipeline
    pred_marker)
  File "/home/marwa/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/util.py", line 372, in three_df_index_overlap_sort
    "input files.")
ValueError: No sequence ids overlap between all three of the input files.
` 
Although my sequence ids are identical. Would you please help? 
I went through some issues with a similar problem, but all the suggested answers do not suit my case. 
my input files coming from ASVs table from phyloseq object.

**Comment by gavinmdouglas** [comment]
Hi there,

The sequences must differ in some way - maybe there is whitespace following the ids for instance?

Feel free to send me the files and I can help troubleshoot.


Best,

Gavin

**Comment by MarwaElnaiem** [comment]
Hey, 

Thanks very much. You are right but I could not figure out where is the difference.
I attached them in one compressed folder. 
[Marwa_Files.tar.gz](https://github.com/picrust/picrust2/files/4846780/Marwa_Files.tar.gz)

Regards,
Marwa

**Comment by gavinmdouglas** [comment]
Thanks for sending the files - I also don't see any obvious differences. What's the exact command you're running? Also this problem might be related because the script is expecting the table filename to end in ".biom" so you could add that to the end of the filename.

Best,

Gavin

**Comment by MarwaElnaiem** [comment]
Thanks very much for your help. 
Yes, it was the problem. 
I did run this comment first:

` metagenome_pipeline.py -i Elgref_biom4 -m marker_predicted_and_nsti.tsv.gz -f EC_predicted.tsv.gz \
                       -o EC_metagenome_out --strat_out
`

I renamed the file with .biom extension after I read your reply and the new command worked for me successfully in few seconds.
`metagenome_pipeline.py -i Elgref_biom.biom -m marker_predicted_and_nsti.tsv.gz -f EC_predicted.tsv.gz \ 
                       -o EC_metagenome_out --strat_out
`
Very important point. 

Once again thanks very much. 
Regards, 
Marwa

**Comment by Saldiyan** [comment]
Hello, 

I am a new user of applying PICRUST2 to my data. I am getting same error, When I run this command; 
metagenome_pipeline.py -i feature-table.biom -f KO_predicted.tsv.gz -m marker_predicted_and_nsti.tsv.gz --strat_out -o KO_metagenome_out
It looks that the command has worked and showing this message; "32 of 4575 ASVs were above the max NSTI cut-off of 2.0 and were removed from the downstream analyses but next line show this error **Stopping - no sequence ids overlap between all three of the input files" and the built output folder** "KO_metagenome_out" is empty, so I can not proceed to the next step. I would appreciate if you can help me in this regards. I have attached the files in case you have a chance to take a look.Thank you.

[Archive.zip](https://github.com/picrust/picrust2/files/10296347/Archive.zip)
