### ISSUE TITLE
qiime2 feature sequences aligned poorly to reference sequences

### ISSUE THREAD

**Issue by hyystvar** [picrust/picrust2#127]
When I use feature sequence and feature table from my qiime2-2019.10 pipline to run the picrust2 pipline, I get an error which is  "Stopping - all 315 input sequences aligned poorly to reference sequences ".
The input data is from 4 human feces with 16S rDNA sequencing. 
Why the qiime2 feature sequence con't align to picrust's reference sequences? Should I choose a smaller min_align?

**Comment by gavinmdouglas** [comment]
Hi @hyystvar,

Usually this problem is due to sequences being on the negative strand - is that possible for your data? If so you could take the reverse complement to fix this problem. If that doesn't work then you could BLAST a few sequences by hand to see what they are matching.

Best,

Gavin
