### ISSUE TITLE
How should I change setting if I use a fungi ITS sequences ?

### ISSUE THREAD

**Issue by sixvable** [picrust/picrust2#131]
Hi Gavin!

I am trying to predict functional abundances based on my fungi ITS2 ASV sequences. I have some questions about the parameter setting.

The command I thought should be :
```
picrust2_pipeline.py \
-s sequences.fna \
-i otu_table.biom \
-r ~/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/fungi/fungi_ITS \
--marker_gene_table ~/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/fungi/ITS_counts.txt.gz \
--pathway_map ~/miniconda3/envs/picrust2/lib/python3.6/sitepackages/picrust2/default_files/pathway_mapfiles/metacyc_path2rxn_struc_filt_fungi.txt \
-o result
```

1. which file should I choose for `--marker_gene_table`?   **fungi/ITS_counts.txt.gz** or **fungi/ec_ITS_counts.txt.gz**
2. which file should I choose for `--pathway_map`? **metacyc_path2rxn_struc_filt_fungi.txt** or **metacyc_path2rxn_struc_filt_fungi_present.txt**
 3. Should I choose a non-default file for `--reaction_func``? Since I find [WIKI](https://github.com/picrust/picrust2/wiki/Full-pipeline-script) shows it is a *default EC file which is corresponds to the prokaryotic EC number table*
 4. Are there any other parameter that I should take care?

Hope it would not botter you! 

sixvable

**Comment by gavinmdouglas** [comment]
Hey @sixvable,

You can see this FAQ about this question: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-a-custom-or-non-default-database-such-as-the-fungi-18s-and-its-databases

I think that will answer all of your questions!

Please note that we do not recommend users use these databases for standard analyses though - you can see the validations in the supplementary materials of the PICRUSt2 paper for more details.


Gavin

**Comment by sixvable** [comment]
Thank you! That really helpfull!
