### ISSUE TITLE
Level in PICRUSt2

### ISSUE THREAD

**Issue by dikiprawisuda** [picrust/picrust2#133]
Dear developers,

I wanted to ask about the command of level in PICRUSt1. Is it still available in this newer version?

Additionally, is it still compatible to use in STAMP software? Also, if I run it in iMac with 8 GB of RAM (run through terminal), will it be alright?

Thank you.

**Comment by gavinmdouglas** [comment]
Hey @dikiprawisuda,

The original way of getting KEGG levels with PICRUSt1 isn't supported anymore, but you can do it with a workaround (see: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-categorize_by_functionpy-like-in-picrust1).

You can use STAMP, although I would only recommend it for visualization, not for statistical tests. See: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.3.0-beta)#add-functional-descriptions

8 GB of RAM probably isn't enough for the default read placing pipeline, but you can use SEPP with the qiime2 plugin instead as described here: https://github.com/picrust/picrust2/wiki/Swapping-in-SEPP-for-read-placement-with-q2-picrust2


Best,

Gavin

**Comment by dikiprawisuda** [comment]
Thank you for your clear explanation. :+1:

**Comment by marwa38** [comment]
@mlangill 

I can't see any tutorial/wiki that can visualise the statistically analyzed data (after using picrust2 and aldex2 for example). Please correct me if I am wrong.
