### ISSUE TITLE
Executing transaction: / ERROR:

### ISSUE THREAD

**Issue by gaofangzhou377** [picrust/picrust2#134]
hello, i have a problem when install picrust2 with conda. my system is Ubuntu 18.4
what should i do next?
thank you

Executing transaction: / ERROR: post-link.sh was unable to download /home/meta/miniconda2/envs/picrust2/staging/v2.3.0-b.tar.gz with the sha256 ac12c372bc263e750d9101eca0cd0e57de37089b661fa1a13caf5a544d293737 from https://github.com/picrust/picrust2/archive/v2.3.0-b.tar.gz.

done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::picrust2-2.3.0_b-py_0'.
Rolling back transaction: done

CondaMultiError: LinkError: post-link script failed for package bioconda::picrust2-2.3.0_b-py_0
location of failed script: /home/meta/miniconda2/envs/picrust2/bin/.picrust2-post-link.sh
==> script messages <==
ERROR: post-link.sh was unable to download /home/meta/miniconda2/envs/picrust2/staging/v2.3.0-b.tar.gz with the sha256 ac12c372bc263e750d9101eca0cd0e57de37089b661fa1a13caf5a544d293737 from https://github.com/picrust/picrust2/archive/v2.3.0-b.tar.gz.

==> script output <==
stdout: /home/meta/miniconda2/envs/picrust2/staging/v2.3.0-b.tar.gz: FAILED

stderr: --2020-09-03 15:50:48--  https://github.com/picrust/picrust2/archive/v2.3.0-b.tar.gz
Resolving github.com (github.com)... 13.250.177.223
Connecting to github.com (github.com)|13.250.177.223|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/picrust/picrust2/tar.gz/v2.3.0-b [following]
--2020-09-03 15:50:49--  https://codeload.github.com/picrust/picrust2/tar.gz/v2.3.0-b
Resolving codeload.github.com (codeload.github.com)... 13.250.162.133
Connecting to codeload.github.com (codeload.github.com)|13.250.162.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/home/meta/miniconda2/envs/picrust2/staging/v2.3.0-b.tar.gz’

     0K .......... .......... .......... .......... .......... 2.02K
    50K .......... .......... .......... .......... .......... 2.45K
   100K .......... .......... .......... .......... .......... 5.42K
   150K .......... .......... .......... .......... .......... 3.82K
   200K .......... .......... .......... .......... .......... 2.26K
   250K .......... .......... .......... .......... .......... 2.30K
   300K .......... .......... .......... .......... .......... 1.26K
   350K .......... .......... .......... .......... .......... 6.51K
   400K .......... .......... .......... .......... .......... 8.73K
   450K .......... .......... .......... .......... .......... 4.93K
   500K .......... .......... .......... .......... .......... 5.50K
   550K .......... .......... .......... .......... .......... 8.28K
   600K .......... .......... .......... .......... .......... 4.99K
   650K .......... .......... .......... .......... .......... 3.54K
   700K .......... .......... .......... .......... .......... 4.54K
   750K .......... .......... .......... .......... .......... 4.29K
   800K .......... .......... .......... .......... .......... 2.71K
   850K .......... .......... .......... .......... .......... 8.74K
   900K .......... .......... .......... .......... .......... 8.03K
   950K .......... .......... .......... .......... .......... 6.47K
  1000K .......... .......... .......... .......... .......... 2.14K
  1050K .......... .......... .......... .......... .......... 2.26K
  1100K .......... .......... .......... .......... .......... 6.93K
  1150K .......... .......... .......... .......... .......... 6.88K
  1200K .......... .......... .......... .......... .......... 3.14K
  1250K .......... .......... .......... .......... .......... 6.27K
  1300K .......... .......... .......... .......... .......... 5.03K
  1350K .......... .......... .......... .......... .......... 3.97K
  1400K .......... .......... .......... .......... .......... 9.42K
  1450K .......... .......... .......... .......... .......... 3.58K
  1500K .......... .......... .......... .......... .......... 4.92K
  1550K .......... .......... .......... .......... ..........  433 
  1600K .......... .......... .......... .......... .......... 3.67K
  1650K .......... .......... .......... .......... .......... 3.93K
  1700K .......... .......... .......... .......... .......... 5.86K
  1750K .......... .......... .......... .......... .......... 4.77K
  1800K .......... .......... .......... .......... .......... 4.22K
  1850K .......... .......... .......... .......... .......... 7.02K
  1900K .......... .......... .......... .......... .......... 2.61K
  1950K .......... .......... .......... .......... .......... 2.24K
  2000K .......... .......... .......... .......... .......... 3.17K
  2050K .......... .......... .......... .......... .......... 5.13K
  2100K .......... .......... .......... .......... .......... 3.18K
  2150K .......... .......... .......... .......... .......... 5.96K
  2200K .......... .......... .......... .......... .......... 3.32K
  2250K .......... .......... .......... .......... .......... 4.07K
  2300K .......... .......... .......... .......... .......... 5.08K
  2350K .......... .......... .......... .......... ..........  451 
  2400K .......... .......... .......... .......... .......... 5.28K
  2450K ......                                                 32.9K=14m5s

2020-09-03 16:04:58 (2.91 KB/s) - ‘/home/meta/miniconda2/envs/picrust2/staging/v2.3.0-b.tar.gz’ saved [2515390]

sha256sum: WARNING: 1 computed checksum did NOT match

return code: 1

()

**Comment by gavinmdouglas** [comment]
If anyone has similar issues I would recommend re-running the command since it seems like a downloading error that caused the resulting gzipped folder to have the wrong sha256sum.
