### ISSUE TITLE
dada2 to picrust2

### ISSUE THREAD

**Issue by razz1618** [picrust/picrust2#135]
Hi,
Is there any to use dada2 output (asv abundance table, taxonomy table assigned with SILVA database)directly in picrust2 or  to convert the dada2 output to picrust2 compatible format? I didn't find any solid material regarding this on DADA2 and google. I have my OTU/ASV taxonomy, abundance, metadata files in txt (tsv/csv) format as well as phyloseq object (Taxonomy assigned using SILVA database).

Any help/suggestions will be highly appreciated.

**Comment by gavinmdouglas** [comment]
Hey @razz1618,

Yes you can certainly format the objects output by DADA2 to be compatible with PICRUSt2. You can see the expected format at the beginning of this tutorial: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.3.0-beta)#tutorial-dataset

So you will need to output the ASV sequences in FASTA format and create a tab-delimited abundance table. It's not necessary to create a BIOM file - you can just create a tab-delimited table with the extension `.tsv`. Samples are columns and ASVs rows (first column is the ASV ids).


Best,

Gavin

**Comment by razz1618** [comment]
Thanks. it seems to be working fine.

**Comment by joshuacgil** [comment]
Hi @razz1618,
I have been trying to do the same but I have been unsuccessful and similarly I cannot find any clear instructions on how to convert my data into the proper .fna and .biom files. Can you elaborate on what you did/what needs to be done to go from DADA2 to Picrust2?

Thank you,

-josh

**Comment by razz1618** [comment]
@joshuacgilPICRUST2 accepts the default DADA2 ouput of asv.fasta and count table in .tsv format (no need of .biom file).
 https://github.com/picrust/picrust2/issues/136#issuecomment-743696114
