### ISSUE TITLE
Issue regarding qiime2 plugin- ImportError: cannot import name 'default_ref_dir'

### ISSUE THREAD

**Issue by razz1618** [picrust/picrust2#136]
Hi,
 I got an error while installing qiime2 plugin. everything went smoothly  during installation following the prescribed method but when I try check it in qiime2 it gives me error saying :

QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/click/command.py", line 43, in parse_args
    return super().parse_args(ctx, args)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 1209, in parse_args
    echo(ctx.get_help(), color=ctx.color)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 570, in get_help
    return self.command.get_help(self)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 975, in get_help
    self.format_help(ctx, formatter)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 1003, in format_help
    self.format_options(ctx, formatter)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/click/command.py", line 157, in format_options
    for subcommand in self.list_commands(ctx):
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/commands.py", line 92, in list_commands
    plugins = sorted(self._plugin_lookup)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/commands.py", line 76, in _plugin_lookup
    import q2cli.core.cache
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/core/cache.py", line 406, in <module>
    CACHE = DeploymentCache()
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/core/cache.py", line 61, in __init__
    self._state = self._get_cached_state(refresh=refresh)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/core/cache.py", line 107, in _get_cached_state
    self._cache_current_state(current_requirements)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/core/cache.py", line 200, in _cache_current_state
    state = self._get_current_state()
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/core/cache.py", line 238, in _get_current_state
    plugin_manager = qiime2.sdk.PluginManager()
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 54, in __new__
    self._init(add_plugins=add_plugins)
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 81, in _init
    plugin = entry_point.load()
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/home/mcs/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mcs/gene/shail/16/q2-picrust2-2019.10_0/q2_picrust2/__init__.py", line 9, in <module>
    from ._full_pipeline import full_pipeline
  File "/home/mcs/gene/shail/16/q2-picrust2-2019.10_0/q2_picrust2/_full_pipeline.py", line 7, in <module>
    from picrust2.default import (default_ref_dir, default_tables,
**ImportError: cannot import name 'default_ref_dir'**

Is it a compatibility issue as I am using qiime2-2020.8 version
plugin version: q2-picrust2 2019.10_0

When I check version in picrust2 conda env (without activating qiime2 conda env) it shows-
picrust2_pipeline.py 2.3.0-b

with qiime2 activated, it shows
picrust2_pipeline.py 2.0.3-b

I have installed the latest picrust 2 from https://github.com/picrust/picrust2/archive/v2.3.0-b.zip then followed the manual method to install q2-plugin.

**Comment by 123chenlei** [comment]
Hi bro，I have the same problem with you, did you solve this problem?

**Comment by razz1618** [comment]
@123chenlei unfortunately not. I used PICRUST2 package directly. It worked for me.

**Comment by antonio-gs009** [comment]
@razz1618 how do you used PICRUST2 package directly? Could you give me to the information? I have the same problem. thanks.

**Comment by razz1618** [comment]
@antonio-gs009 Once you have your OTU/ASV table and abundance table, install PICRUST2 via conda (https://github.com/picrust/picrust2/wiki/Installation) and follow the PICRUST2 tutorial (https://github.com/picrust/picrust2/wiki/Full-pipeline-script). 

The input file need not be .biom, Picrust2  also accepts .tsv file (Samples are columns and OTU/ASVs rows (first column is the OTU/ASV ids).

For me running each individual step did not work properly, but running the picrust2_pipeline.py worked.

**Comment by JBL05** [comment]
> @antonio-gs009 Once you have your OTU/ASV table and abundance table, install PICRUST2 via conda (https://github.com/picrust/picrust2/wiki/Installation) and follow the PICRUST2 tutorial (https://github.com/picrust/picrust2/wiki/Full-pipeline-script).
> 
> The input file need not be .biom, Picrust2 also accepts .tsv file (Samples are columns and OTU/ASVs rows (first column is the OTU/ASV ids).
> 
> For me running each individual step did not work properly, but running the picrust2_pipeline.py worked.

Hi ShaiNair, I am stucking here, could you please share your code that how you can get the fna and tsv file from dada2?

**Comment by ShailNair** [comment]
@JBL05 To get ASV sequence table and tsv files from dada2

After you assign taxonomy

# Change seq headers to asv number (ASV_1, ASV_2...)
```
asv_seqs <- colnames(seqtab.nochim)
asv_headers <- vector(dim(seqtab.nochim)[2], mode="character")

for (i in 1:dim(seqtab.nochim)[2]) {
  asv_headers[i] <- paste(">ASV", i, sep="_")
}
```
# Create and write out a fasta of our final ASV seqs
```
asv_fasta <- c(rbind(asv_headers, asv_seqs))
write(asv_fasta, str_c(dada2_dir, "ASVs.fa"))
```
# ASV count table:
```{r}
asv_tab <- t(seqtab.nochim)
row.names(asv_tab) <- sub(">", "", asv_headers)
write.table(asv_tab, "~/dada2/ASVs_counts.tsv", sep="\t", quote=F, col.names=NA)
```

# tax table
```{r}
asv_tax <- taxa
row.names(asv_tax) <- sub(">", "", asv_headers)
write.table(asv_tax, "~/dada2/ASVs_taxonomy.tsv", sep = "\t", quote=F, col.names=NA)
```

# To merge asv abundance and taxonomy into one file
```{r}
OTU_TAX_table <- merge(asv_tab, asv_tax, by=0)
write.table(OTU_TAX_table, "~/dada2/OTU_TAX_table.tsv", sep = "\t", quote=F, col.names=NA)
```

**Comment by JBL05** [comment]
> 

Thank you very much for your quick reply; that greatly helps!

**Comment by marwa38** [comment]
many thanks @ShailNair
your two posts/issues helped to find out that I could go directly from dada2 into PICRUST2
have you got any problem with poorly aligned ASVs? do you think that this is too many ASVs lost
I aligned against silva (not greengenes) and used dada2 for denoising 
`Warning - 363 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences).  These input sequences will not be placed and will be excluded from downstream st  eps.`
![image](https://user-images.githubusercontent.com/68851733/151235272-d2b03aa5-5dfa-4322-a306-dee24180e8ea.png)
```
**55 of 2474 ASVs were above the max NSTI cut-off of 2.0 and were removed.

55 of 2474 ASVs were above the max NSTI cut-off of 2.0 and were removed.
**
```

**Comment by ShailNair** [comment]
@marwa38 it may be due to poor filtering while processing your sequences. Probably you should recheck your dada2/qiime2 process for filtering poor quality sequences, chimera removal. Presence of primer will also afffect. 
If you are sure that your sequences are clean it may be related to  https://github.com/picrust/picrust2/issues/122

**Comment by marwa38** [comment]
@ShailNair
thanks very much for your comments again
I removed the chimeras and primers beforehand using dada2 in R 
I reverse complemented the sequences but found out that my strand is already in the right position. 
I was wondering if you have used greengenes rather than silva? or that ASV number is considered high to be poorly aligned in the first place, from your point of view? (363 out of 2474)?
Cheers .. Marwa

**Comment by ShailNair** [comment]
I used silva. Yes only 363 sequences aligned means you wont get metabolic prediction about 85% of your sequences. 

You can isolate a few random sequence from this poorly asigned, and blast it in ncbi..check if they matches with the 16s rRNA gene of the  assigned taxonomy.

similiarly, a lot of people have created similiar threads in the issuessection..you can the solutions from there.

If nothing works you can contact Gavin as i am not a pro in this.

**Comment by marwa38** [comment]
363 are the ones not aligned
thanks, have good day :)

**Comment by ShailNair** [comment]
> 363 are the ones not aligned thanks, have good day :)

Thats ok i guess...u have more than 80% data....but still if u can use all seuences...thats more better

**Comment by chuynh96** [comment]
> @JBL05 To get ASV sequence table and tsv files from dada2
> 
> After you assign taxonomy
> 
> # Change seq headers to asv number (ASV_1, ASV_2...)
> ```
> asv_seqs <- colnames(seqtab.nochim)
> asv_headers <- vector(dim(seqtab.nochim)[2], mode="character")
> 
> for (i in 1:dim(seqtab.nochim)[2]) {
>   asv_headers[i] <- paste(">ASV", i, sep="_")
> }
> ```
> 
> # Create and write out a fasta of our final ASV seqs
> ```
> asv_fasta <- c(rbind(asv_headers, asv_seqs))
> write(asv_fasta, str_c(dada2_dir, "ASVs.fa"))
> ```
> 
> # ASV count table:
> ```
> asv_tab <- t(seqtab.nochim)
> row.names(asv_tab) <- sub(">", "", asv_headers)
> write.table(asv_tab, "~/dada2/ASVs_counts.tsv", sep="\t", quote=F, col.names=NA)
> ```
> 
> # tax table
> ```
> asv_tax <- taxa
> row.names(asv_tax) <- sub(">", "", asv_headers)
> write.table(asv_tax, "~/dada2/ASVs_taxonomy.tsv", sep = "\t", quote=F, col.names=NA)
> ```
> 
> # To merge asv abundance and taxonomy into one file
> ```
> OTU_TAX_table <- merge(asv_tab, asv_tax, by=0)
> write.table(OTU_TAX_table, "~/dada2/OTU_TAX_table.tsv", sep = "\t", quote=F, col.names=NA)
> ```

In this, what was the "dada2_dir" in
asv_fasta <- c(rbind(asv_headers, asv_seqs))
write(asv_fasta, str_c(dada2_dir, "ASVs.fa"))
?

**Comment by chuynh96** [comment]
I've also tried inputting different objects from my environment into the command
write(asv_fasta, str_c(dada2_dir, "ASVs.fa"))
for dada2_dir and am getting errors that are similar to this one (varies depending on what object I use):
Error in file(file, ifelse(append, "a", "w")) : 
  invalid 'description' argument
In addition: Warning messages:
1: In stri_c(list(OTU = c("ASV49", "ASV262", "ASV219", "ASV1", "ASV1",  :
  argument is not an atomic vector; coercing
2: In if (file == "") file <- stdout() else if (startsWith(file, "|")) { :
  the condition has length > 1 and only the first element will be used
3: In if (startsWith(file, "|")) { :
  the condition has length > 1 and only the first element will be used
