### ISSUE TITLE
Find the closest reference genome used for the prediction of functional profile

### ISSUE THREAD

**Issue by kafker** [picrust/picrust2#137]
Hello,

I have been asked to find the closest reference genome used for the functional profiling of the ASVs having a NSTI score below 0.15. I was wondering if this can be accomplished by simply looking at the placment of the ASVs into the reference phylogenetic tree.

Thanks!

**Comment by gavinmdouglas** [comment]
Hey @kafker,

Yes the easiest way to do this would be go to look at the tree that is created after the `place_seqs.py` step. If you're comfortable in R then to identify the closest tips to each ASV you could use the `get_pairwise_distances` function from the castor R package.


All the best,

Gavin

**Comment by kafker** [comment]
Thank you, Gavin!

Best

Andrea

Il giorno ven 2 ott 2020 alle ore 22:55 Gavin Douglas <
notifications@github.com> ha scritto:
