### ISSUE TITLE
Is it possible to run Sequence Placement using the repseq.qza file from QIIME2?

### ISSUE THREAD

**Issue by ec-ho-ra-mos** [picrust/picrust2#138]
I need to do a metagenome prediction using QIIME2 from inputs of QIIME2. Is it possible to run

place_seqs.py -s <repseq from DADA>.qza  ...

With the <repseq from DADA>.qza coming from here -> qiime dada2 denoise-paired --o-representative-sequences <repseq from DADA>.qza

**Comment by gavinmdouglas** [comment]
Hi @echogeronca,

No you can't input a QZA file, but you can export it to a FASTA file and then import than (check out ```qiime tools export --help```


All the best,

Gavin
