### ISSUE TITLE
Compatibility issue with different R version on system

### ISSUE THREAD

**Issue by DoetschA** [picrust/picrust2#139]
I'm trying to run PICRUSt2 using miniconda and run into trouble with the hsp.py script, apparently caused by calling Rcpp, which was built with R 4.0.0. Apparently, there is an issue with the conda and system versions of R being different version and picrust attempting to use an incompatible package from the system.
The exact call and error message are:

`(picrust2) [myPath]$ hsp.py -i 16S -t out.tre -o marker_predicted_and_nsti.tsv.gz -p 60 -n`

`Error running this command:`
`Rscript /home/bioinf/programs/picrust2-2.3.0-b/picrust2/Rscripts/castor_nsti.R out.tre /tmp/tmp551iibxt/known_tips.txt /tmp/tmp551iibxt/nsti_out.txt`

`Standard error of the above failed command:`
`Error: package or namespace load failed for ‘Rcpp’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/R/4.0.0/lib/R/Rcpp/libs/Rcpp.so':
  /opt/R/4.0.0/lib/R/Rcpp/libs/Rcpp.so: undefined symbol: CAR0`
`Error: package ‘Rcpp’ could not be loaded`
`In addition: Warning messages:`
`1: package ‘castor’ was built under R version 3.6.3`
`2: package ‘Rcpp’ was built under R version 4.0.0`
`Execution halted`

The system is Ubuntu 18.04.5 LTS with R version 4.0.0 installed. I am not using QIIME and also not familiar with conda. To install picrust2, I chose miniconda and tried both installation options explained here in the wiki (i.e. install from either bioconda or source). Both resulted in the same issue as described above.
Installing Rcpp via conda does not work because it is already installed.

Is there a way to install a different version of Rcpp specifically for the picrust environment? 
Or did I get the main issue entirely wrong?

**Comment by gavinmdouglas** [comment]
Hey @DoetschA,

Sorry you're running into problems. I think this is either a rare issue between Rcpp and conda or alternatively maybe your different version of R is further up in your path even when the conda environment is activated?

Regarding the former issue you can take a look at this thread to see if it helps: https://stackoverflow.com/questions/40333691/unable-to-use-rcpp-after-conda-install


Cheers,

Gavin

**Comment by DoetschA** [comment]
Hi @gavinmdouglas ,

the path might be the point, but I am not experienced how this is handled in conda or in picrust2. 
This is what I managed to check myself so far (everything was done in activated picrust2 environment: `conda activate picrust2`):

The path to R seems to work, because R will start correctly with the miniconda version when called via 'R' (version is 3.6.3, system version is 4.0.0):
`R --version`
`R version 3.6.3 (2020-02-29) -- "Holding the Windsock"`

But the library path is indeed in the wrong order:
`> .libPaths()`
`[1] "/opt/R/4.0.0/lib/R"`
`[2] "/home/bioinf/programs/miniconda3/envs/picrust2/lib/R/library"`

I tried to switch the order by adding the following lines to Rprofile (located in .../miniconda3/envs/pircust2/lib/R/library/base) :
`myPath <- .libPaths()`
`.libPaths(myPath[c(2,1)])`

This is apparently executed since I can call the new variable myPath afterwards. But calling .libPaths either has no effect or is reverted upon startup:
`> .libPaths()`
`[1] "/opt/R/4.0.0/lib/R"`
`[2] "/home/bioinf/programs/miniconda3/envs/picrust2/lib/R/library"`

I can start R, switch the path order and load Rcpp just fine but how can I fix this already during startup?

**Comment by gavinmdouglas** [comment]
Hi @DoetschA,

Sounds like you've narrowed down the issue. You can see others complaining about this issue with conda here: https://github.com/conda-forge/r-base-feedstock/issues/37

There are a few fixes at the bottom of that thread which you might find useful!


Best,

Gavin
