### ISSUE TITLE
Error occurs when using "place_seqs.py"

### ISSUE THREAD

**Issue by wyanren** [picrust/picrust2#140]
Hi Dr. ,
Error occurs when i use <place_seqs.py> dealing with the ITS data, here is my typing and error report:

```
place_seqs.py -s rep_set.fna -o placedseqs_rep_set.tre --ref_dir ../github_code/picrust2/picrust2/default_files/fungi/fungi_ITS -p 1 --intermediate placement_working
Stopping - all 37331 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences).
```

I tried to add "--min_align 0" to solve the error, while it didn't work. 

Looking forward to your reply.

**Comment by gavinmdouglas** [comment]
Sorry for the late reply - the problem may be that the FASTA headers need to be cleaned up for the file you're inputting. See this FAQ response: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#why-am-i-getting-the-error-stopping---all-x-input-sequences-aligned-poorly-to-reference-sequences

I think one of those suggestions will solve your problem.
