### ISSUE TITLE
place_seqs.py fails when using my fasta file #75

### ISSUE THREAD

**Issue by cindynino** [picrust/picrust2#141]
Hello,
I have picrust2.1.0-b installed.
I'm trying to run picrust2_pipeline.py -s cin_final_final_este_si.fna -i table.from_txt.biom -o picrust2_out_pipeline -p 1
 and the process fails with the following error when I use my fasta file, but not the tutorial one. Below is the error I get. Help is much appreciated. Thanks :)

Error running this command:
place_seqs.py --study_fasta cin_final_final_este_si.fna --ref_dir /opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref --out_tree picrust2_out_pipeline/out.tre --processes 1 --intermediate picrust2_out_pipeline/intermediate/place_seqs --min_align 0.8 --chunk_size 5000

Standard error of the above failed command:

Error running this command:
hmmalign --trim --dna --mapali /opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna.gz --informat FASTA -o picrust2_out_pipeline/intermediate/place_seqs/query_align.stockholm /opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.hmm cin_final_final_este_si.fna

**Comment by gavinmdouglas** [comment]
Hey @cindynino,

Usually that happens when users have insufficient memory for the placement step. How much memory do you have?

You might want to do read placement with SEPP as mentioned in this tutorial: https://github.com/picrust/picrust2/wiki/q2-picrust2-Tutorial


Cheers,

Gavin

**Comment by cindynino** [comment]
Hi
Yes  I only have 8GB, I would have to use more memory, thank you very much for your answer.

De: Gavin Douglas <notifications@github.com>
Fecha: viernes, 16 de octubre de 2020, 7:52 a. m.
Para: picrust/picrust2 <picrust2@noreply.github.com>
CC: cindynino <cindyninos@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [picrust/picrust2] place_seqs.py fails when using my fasta file #75 (#141)

Hey @cindynino<https://github.com/cindynino>,

Usually that happens when users have insufficient memory for the placement step. How much memory do you have?

You might want to do read placement with SEPP as mentioned in this tutorial: https://github.com/picrust/picrust2/wiki/q2-picrust2-Tutorial

Cheers,

Gavin
