### ISSUE TITLE
shared object 'Rcpp.dylib' not found"

### ISSUE THREAD

**Issue by microresearcher** [picrust/picrust2#143]
Hello, I am following the picrust2 tutorial on a Mac running OS Mojave, but am running into an issue. When I run the command:

"hsp.py -i 16S -t placed_seqs.tre -o marker_nsti_predicted.tsv.gz -p 1 -n"

I get the following error:
"Error running this command:
Rscript /Users/sohali/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/Rscripts/castor_nsti.R placed_seqs.tre /var/folders/hk/xzr6rgq5119flp9h4j3928242bqz0v/T/tmpl6owcne8/known_tips.txt /var/folders/hk/xzr6rgq5119flp9h4j3928242bqz0v/T/tmpl6owcne8/nsti_out.txt

Standard error of the above failed command:
Error: package or namespace load failed for ‘Rcpp’ in library.dynam(lib, package, package.lib):
 shared object ‘Rcpp.dylib’ not found
Error: package ‘Rcpp’ could not be loaded
Execution halted"

My issue at first seemed the same as [#112](https://github.com/picrust/picrust2/issues/112), but when I check my R instance with "which R", I get:
"/Users/[username]/opt/anaconda3/envs/picrust2/bin/R"
which I believe is the instance I want, is this correct? This is also at the very beginning of my path, so if it is correct, then any idea why it is still not finding Rcpp?

Any help appreciated. Thanks in advance!

**Comment by gavinmdouglas** [comment]
Hi @microresearcher,

Yes that is the correct R that should be in your path. Someone ran into a similar problem here which might help you: https://github.com/picrust/picrust2/issues/139#issuecomment-709986795

I would try re-installing Rcpp specifically in that environment to see if that helps. It seems like a transient issue with Rcpp and conda that needs to be addressed. Unfortunately I'm not sure what to recommend besides try to re-install it and follow the leads in that other issue.


Best,

Gavin

**Comment by microresearcher** [comment]
Thank you @gavinmdouglas! The conda-forge thread you linked to on issue 139 was helpful.

What worked for me was going into the "Renviron" file at conda/envs/<myenvname>/lib/R/etc and commenting out the following line:

R_LIBS_USER=${R_LIBS_USER-'~/Library/R/3.6/library'}

It seems like that line was referencing my own Rstudio's library which, as others on that thread have expressed, is an odd choice.

Thanks again
