### ISSUE TITLE
Picrust2- EC

### ISSUE THREAD

**Issue by zina-R** [picrust/picrust2#145]
Hello, I have 1200 KEGG EC Ids like EC:1.1.1.116 , EC:1.1.1.137 and so on . I have retrieved it for my genome using picrust2. I want to retrieve corresponding name at the 3 levels like: Metabolism, Carbohydrate metabolism, Fructose and mannose metabolism ... any help, thank you

**Comment by gavinmdouglas** [comment]
Hey there,

Sorry for the late response - I don't have an easy way of mapping to those specific levels unfortunately. I would recommend you perform pathway inference if you are interested in higher-level functions.


Cheers,

Gavin

**Comment by Mingye-Peng** [comment]
> 您好，我有1200个KEGG EC ID，例如EC：1.1.1.116，EC：1.1.1.137等。我已经使用picrust2为我的基因组检索了它。我想在3个级别上检索相应的名称，例如：代谢，碳水化合物代谢，果糖和甘露糖代谢...有什么帮助，谢谢

Hello, I have the same problem as you. how can i get high level of description L1, L2 or L3 of the KEGG pathway? thank you for your time. looking forward to your reply.

**Comment by gavinmdouglas** [comment]
Hey @Mingye-Peng,

I think your question is related to this section of the FAQ: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-categorize_by_functionpy-like-in-picrust1


Hopefully that helps,

Gavin

**Comment by shaopopper** [comment]
> > 您好，我有1200个KEGG EC ID，例如EC：1.1.1.116，EC：1.1.1.137等。我已经使用picrust2为我的基因组检索了它。我想在3个级别上检索相应的名称，例如：代谢，碳水化合物代谢，果糖和甘露糖代谢...有什么帮助，谢谢
> 
> Hello, I have the same problem as you. how can i get high level of description L1, L2 or L3 of the KEGG pathway? thank you for your time. looking forward to your reply.

![image](https://user-images.githubusercontent.com/79366437/123894764-51281a00-d991-11eb-971f-234acb7705ea.png)
hello,hello.  I run the picrust2 and got the results. How can I do downstream analysis. I have found some analysis guides, I wanna know how could tell "lever 1、2、3、4" from the results of picrust2.  Thanks. 你好，我已经按照picrust2软件分析，得到KO、EO和parthway的结果，我看国内一些成果展示有水平1、2、3、4这些，我想知道怎么根据picrust2输出的结果进行这些不同水平分析呢？ 感谢。

**Comment by shaopopper** [comment]
> > 您好，我有1200个KEGG EC ID，例如EC：1.1.1.116，EC：1.1.1.137等。我已经使用picrust2为我的基因组检索了它。我想在3个级别上检索相应的名称，例如：代谢，碳水化合物代谢，果糖和甘露糖代谢...有什么帮助，谢谢
> 
> Hello, I have the same problem as you. how can i get high level of description L1, L2 or L3 of the KEGG pathway? thank you for your time. looking forward to your reply.
@Mingye-Peng ，Have you solved the problem.
hello,hello. I run the picrust2 and got the results. How can I do downstream analysis. I have found some analysis guides, I wanna know how could tell "lever 1、2、3、4" from the results of picrust2. Thanks. 你好，我已经按照picrust2软件分析，得到KO、EO和parthway的结果，我看国内一些成果展示有水平1、2、3、4这些，我想知道怎么根据picrust2输出的结果进行这些不同水平分析呢？ 感谢。
