### ISSUE TITLE
PyCRUST2 installing in new Qiime2

### ISSUE THREAD

**Issue by AFASantos** [picrust/picrust2#147]
Hi, 
I have installed Qiime2 2020.8 and I would like to install the q2-picrust2 plug-in, but I always get back this error: 

conda install q2-picrust2=2019.10_0 -c conda-forge -c bioconda -c gavinmdouglas

Collecting package metadata (current_repodata.json): done

Solving environment: failed with initial frozen solve. Retrying with flexible solve.

Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

Collecting package metadata (repodata.json): done

Solving environment: \ failed with initial frozen solve. Retrying with flexible solve.

what am i doing wrong?
thank you

**Comment by gavinmdouglas** [comment]
Hey @AFASantos ,

The plugin only works with QIIME 2 version 2019.10 at the moment - you will need to install that version if you want to use the plugin (or you can use the standalone version outside of QIIME 2).


Cheers,

Gavin
