### ISSUE TITLE
Feasibility of having SEPP outside qiime2

### ISSUE THREAD

**Issue by harish0201** [picrust/picrust2#150]
Hi,

I have processed the entire data through dada2 and phyloseq. I was trying picrust2, and unfortunately, I have only 8Gb ram on the system that I'm working on.

Is there a possibility of running SEPP based placements outside of the q2picrust2 plugin; rather than being dependent on EPA-NG?

Any help will be appreciated!

**Comment by Pbdas** [comment]
Just dropping in to say I'm sorry that EPA-NG still fails in this regard, I'm working on a new mode for EPA-NG right now that lets you specify a memory limit. Also, the next version will have a lower memory requirement even when running normally.  Hopefully the new version will be here next month!

**Comment by harish0201** [comment]
Thank you for the update!

Let me know if I can beta-test the same for you!

**Comment by Pbdas** [comment]
Just to be clear: @gavinmdouglas might have a real answer to your question, I'm just being apologetic about epa

**Comment by harish0201** [comment]
Ah no worries ;)

I'll wait for the update.

**Comment by harish0201** [comment]
Hey, sorry to necro-post on the thread after the issue has been closed. But I did find a way to resolve the issue.

I manually changed the chunking options in place_seqs.py and hsp.py to a very low number. The default IIRC is 5000, which I reduced to 500 in order to fit into the RAM. The pipeline has then finished successfully.
