### ISSUE TITLE
How to run picrust2 for the fungal analysis?

### ISSUE THREAD

**Issue by aeonrapt59** [picrust/picrust2#151]
I tried several times to analyze the fungi but failed by the [--ref_dir DIRECTORY] option.
There are fungal references in the picrust2 folder. 

but It doesn't work from the command bellow.
place_seqs.py -s dna-sequences.fasta --ref_dir /home/picrust2-2.3.0-b/picrust2/default_files/fungi/fungi_ITS -o out.tre -p 1 --intermediate placement_working

How to run picrust2 for the fungal analysis?

**Comment by gavinmdouglas** [comment]
Hey @aeonrapt59,

Did you get an error?

You can see this link for how to run the experimental fungal database: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-a-custom-or-non-default-database-such-as-the-fungi-18s-and-its-databases

**Comment by aeonrapt59** [comment]
Hello, @gavinmdouglas 
I thought I would get an error, but it was because the reference sequence didn't match my query sequence.
Do you have any plans to reinforce the reference?

**Comment by gavinmdouglas** [comment]
I see - no I have no current plans to update the fungal database sorry!
