### ISSUE TITLE
error in making the pathways output

### ISSUE THREAD

**Issue by chenniehu** [picrust/picrust2#152]
Hi, after multiple times I still get the same error (see below), that prevents the output of the pathway output using the picrust2_pipeline.py function on my own data. I did not encounter this error when using the chemerin test set of the tutorial. Does anyone know what causes this error and how to solve it? Many thanks in advance!

(picrust2) [370002@gena dada2]$ picrust2_pipeline.py -s Prep_fasta_20201201.fna -i data_biom.biom -o picrust2_output -p 1

0 of 1433 ASVs were above the max NSTI cut-off of 2.0 and were removed.

0 of 1433 ASVs were above the max NSTI cut-off of 2.0 and were removed.

Error running this command:
pathway_pipeline.py --input picrust2_output/EC_metagenome_out/pred_metagenome_unstrat.tsv.gz --out_dir picrust2_output/pathways_out --map /home/370002/picrust2-2.3.0-b/picrust2/default_files/pathway_mapfiles/metacyc_path2rxn_struc_filt_pro.txt --intermediate picrust2_output/intermediate/pathways --proc 1 --regroup_map /home/370002/picrust2-2.3.0-b/picrust2/default_files/pathway_mapfiles/ec_level4_to_metacyc_rxn.tsv

**Comment by gavinmdouglas** [comment]
Hi there,

Do you get any more information if you use the `--verbose` option with the `pathway_pipeline.py` command? Note that you can just run that command rather than `picrust2_pipeline.py` at this point.


Cheers,

Gavin

**Comment by chenniehu** [comment]
Thank you Gavin for responding! I'm not very familiar with coding, but I do not see errors, and also the pathway_out map is missing, when I use both following commands:

pathway_pipeline.py -i EC_metagenome_out/pred_metagenome_unstrat.tsv.gz  -o pathways_out   --intermediate minpath_working    -p 1 --verbose

pathway_pipeline.py -i EC_metagenome_out/pred_metagenome_unstrat.tsv.gz -o pathways_out -p 1 --verbose

The full rtf file is too big to save, I can send you more code, but it ends like this:

pathway 552 553 PYRIDOXSYN-PWY path2fam 8  real-family 5
this pathway is added back
pathway 554 555 RHAMCAT-PWY path2fam 5  real-family 4
this pathway is added back
pathway 557 558 SALVADEHYPOX-PWY path2fam 5  real-family 5
this pathway is added back
pathway 558 559 SER-GLYSYN-PWY path2fam 4  real-family 4
this pathway is added back
pathway 559 560 SO4ASSIM-PWY path2fam 4  real-family 4
this pathway is added back
pathway 560 561 SUCSYN-PWY path2fam 10  real-family 8
this pathway is added back
pathway 562 563 TCA path2fam 10  real-family 6
this pathway is added back
pathway 563 564 TCA-GLYOX-BYPASS path2fam 12  real-family 6
this pathway is added back
pathway 567 568 THRESYN-PWY path2fam 6  real-family 6
this pathway is added back
pathway 569 570 TRPSYN-PWY path2fam 6  real-family 4
this pathway is added back
pathway 570 571 TYRFUMCAT-PWY path2fam 5  real-family 1
pathway 571 572 UBISYN-PWY path2fam 10  real-family 6
this pathway is added back
pathway 572 573 UDPNAGSYN-PWY path2fam 5  real-family 5
this pathway is added back
pathway 574 575 VALSYN-PWY path2fam 4  real-family 4
this pathway is added back
added pathway = 184

Results are saved in file:/tmp/tmp0iqnop19/minpath_running/5436_minpath_report.t                                                                               xt
Details are saved in file:/tmp/tmp0iqnop19/minpath_running/5436_minpath_details.                                                                               txt


Killed

**Comment by gavinmdouglas** [comment]
Hey @chenniehu,

Ok hmm I'm not sure what the problem is. But if you send the file `EC_metagenome_out/pred_metagenome_unstrat.tsv.gz` to me at 
<img width="144" alt="gmail_screenshot" src="https://user-images.githubusercontent.com/12489683/101039842-55eb3380-3552-11eb-99be-eba734884995.png"> then I can help troubleshoot.


All the best,

Gavin

**Comment by chenniehu** [comment]
Hi Gavin, thank you again for your quick responses. I've figured out the problem, it was an issue on our server, picrust2 was running fine on smaller sample sizes. Thank you! Best wishes, Chen
