### ISSUE TITLE
error in predicting KEGG pathway

### ISSUE THREAD

**Issue by sxqchen** [picrust/picrust2#153]
Hi,
I am using PICRUSt2 to predict pathways of my microbiome data. I successfully predicted the MetaCyc pathways, and is predicting KEGG pathways following instructions at: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-determine-kegg-pathway-abundances-from-the-predicted-ko-abundances, but it output error information (below). Could you please help on it?

I use the following command to predict KEGG pathway:

metagenome_pipeline.py -i feature_table.txt -m marker_nsti_predicted.tsv.gz -f KO_predicted.tsv.gz --strat_out --min_reads 10 --min_samples 5 -o KO_metagenome_out
pathway_pipeline.py -i KO_metagenome_out/pred_metagenome_contrib.tsv.gz -o KEGG_pathways_out --no_regroup --map KEGG_pathways_to_KO.tsv

The error output by the second command (pathway_pipeline.py) are:

/home/xs7tm/.conda/envs/picrust2/bin/pathway_pipeline.py:272: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  main()
Traceback (most recent call last):
  File "/home/xs7tm/.conda/envs/picrust2/bin/pathway_pipeline.py", line 272, in <module>
    main()
  File "/home/xs7tm/.conda/envs/picrust2/bin/pathway_pipeline.py", line 210, in main
    verbose=args.verbose)
  File "/home/xs7tm/.conda/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 398, in pathway_pipeline
    for sample_id in samples)
  File "/home/xs7tm/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/xs7tm/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/xs7tm/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/xs7tm/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/home/xs7tm/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/home/xs7tm/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/xs7tm/.conda/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/xs7tm/.conda/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 898, in contrib_format_pathway_levels
    gap_fill_on)
  File "/home/xs7tm/.conda/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 1138, in pathway_abun_and_coverage
    pathway_abun = sum(subset_reaction_abun) / len(subset_reaction_abun)
ZeroDivisionError: division by zero

**Comment by gavinmdouglas** [comment]
Hi there,

Sorry you ran into this problem.

If you don't mind sending me your input file `KO_metagenome_out/pred_metagenome_contrib.tsv.gz` to 
<img width="144" alt="gmail_screenshot" src="https://user-images.githubusercontent.com/12489683/101266284-b8dff480-3723-11eb-831c-6918c68dcd8f.png"> then I can help troubleshoot what's going on.


Cheers,

Gavin

**Comment by sxqchen** [comment]
Hi Gavin,

Thank you very much for your reply! The pred_metagenome_contrib.tsv.gz is more than 500 MB, so I am not able to attach it to you. I shared the files with you on google drive, and have sent you an email. The link is: https://drive.google.com/drive/folders/1wNZgAcT85BHZlDbYpZVLJxDdIvRiiCHj?usp=sharing
Meet Google Drive – One place for all your files<https://drive.google.com/drive/folders/1wNZgAcT85BHZlDbYpZVLJxDdIvRiiCHj?usp=sharing>
Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.
drive.google.com

If you did not receive my email or cannot access the shared files, please let me know.

I generated the pred_metagenome_contrib.tsv.gz by the following command, and I have shared all the files that are needed in the command. I used the two options --min_reads and --min_samples to try solving the problem in the next step of prediction but still failed.

metagenome_pipeline.py -i feature_table.txt \
                       -m marker_nsti_predicted.tsv.gz \
                       -f KO_predicted.tsv.gz \
                    --strat_out \
                    --min_reads 10 \
                    --min_samples 5 \
                       -o KO_metagenome_out

I predicted the KEGG pathway by this command and it produced those error information.

pathway_pipeline.py -i KO_metagenome_out/pred_metagenome_contrib.tsv.gz \
-o KEGG_pathways_out \
--no_regroup \
--map KEGG_pathways_to_KO.tsv

Thank you very much!

Xiangqing

Xiangqing Sun, PhD, MS
Research Specialist
Department of Family Medicine
University of Virginia
P.O. Box 800729
Charlottesville, VA 22908
Tel: 434-924-1146
Fax: 434-243-4800
Email: xs7tm@virginia.edu


________________________________

**Comment by gavinmdouglas** [comment]
Hey @sxqchen,

I wasn't able to reproduce this issue using your input files and the exact command you provided. This was with the latest version (v2.3.0). What version of PICRUSt2 are you using?


Cheers,

Gavin

**Comment by sxqchen** [comment]
Thank you for your help to find the error!

**Comment by gavinmdouglas** [comment]
For future reference the problem was that the file `KEGG_pathways_to_KO.tsv` was downloaded incorrectly.

**Comment by EOMAK91** [comment]
Hi Gavin,

How should the file be downloaded? I am having a similar issue.

Best,
Edwin

**Comment by gavinmdouglas** [comment]
Hey Edwin,

The file is included as part of the full repository. You can clone the repository with git or download the latest release from here: https://github.com/picrust/picrust2/archive/refs/tags/v2.4.1.tar.gz


Cheers,

Gavin

**Comment by EOMAK91** [comment]
Thanks Gavin! 

Best,
Edwin
