### ISSUE TITLE
Not getting predicted_metagenome_contrib output and pathways folder

### ISSUE THREAD

**Issue by afOSU-dot** [picrust/picrust2#155]
Hello, 
I had a previous issue with not getting the pathway outputs when I tried to run the whole pipeline or when I did it step by step. When I put the pipeline on one processor, I finally got all outputs except the predicted_metagenome_contrib output. This was the script I used: picrust2_pipeline.py -s sequences.fasta -i otu_table_no_singletons.biom -o picrust_a5 --processes 1 --verbose

Before I switched to one processor it was -p 20 and it gave me the metagenome contribution but no pathways folder: picrust2_pipeline.py -s sequences.fasta -i otu_table_no_singletons.biom -o picrust_a5 **--processes 20** --verbose

I then tried to add --stratified to the first pipeline script above to get the metagenome contribution added but it stopped before getting the pathway output again. I used this script:  picrust2_pipeline.py -s sequences.fasta -i otu_table_no_singletons.biom -o picrust_strat --processes 1 --stratified --verbose

Any help with getting ALL of the outputs once? Does this have something to do with my data size? I have 39,990 rows of denovos in my fasta. I have very little experience working with terminal and picrust.

**Comment by afOSU-dot** [comment]
Would it be appropriate to additionally use the metagenome_pipeline.py script using the outputs that came from the pipeline that gave me all of the outputs except the predicted_metagenome_contrib file?  So I used this script below: 
picrust2_pipeline.py -s sequences.fasta -i otu_table_no_singletons.biom -o picrust_a5 --processes 1 --verbose 

and I got every output except the metagenome contribution output and I want to use this script below to add the predicted_metagenome_contrib file to "picrust_a5" using the outputs that came from the picrust2_pipelin.py.:

metagenome_pipeline.py -i ../table.biom -m marker_predicted_and_nsti.tsv.gz -f EC_predicted.tsv.gz \-o EC_metagenome_out --strat_out --metagenome_contrib.

**Comment by gavinmdouglas** [comment]
Hi there,

Yes that is ok to do.


All the best,

Gavin

**Comment by afOSU-dot** [comment]
I tried: 
metagenome_pipeline.py -i ../table.biom -m marker_predicted_and_nsti.tsv.gz -f EC_predicted.tsv.gz -o EC_metagenome_out --strat_out --metagenome_contrib. 

I got an error:
usage: metagenome_pipeline.py [-h] -i PATH -f PATH [-m PATH]
                              [--max_nsti FLOAT] [--min_reads INT]
                              [--min_samples INT] [--strat_out] [--wide_table]
                              [--skip_norm] [-o PATH] [-v]
metagenome_pipeline.py: error: unrecognized arguments:  -o EC_metagenome_out --metagenome_contrib

Any help with this one? Thanks!

**Comment by afOSU-dot** [comment]
Okay, I think I got it to work. Is it normal to have 16gb pred_metagenome_contrib file. Initially, it was at 1.67gb but when I came back it became a 16gb file.

**Comment by gavinmdouglas** [comment]
Good to hear! Yes that is normal for the files to be very large - the number of rows can blow up because there is one row per sample x ASV x gene.


Cheers,

Gavin

**Comment by MonicaSteffi** [comment]
> I tried:
> metagenome_pipeline.py -i ../table.biom -m marker_predicted_and_nsti.tsv.gz -f EC_predicted.tsv.gz -o EC_metagenome_out --strat_out --metagenome_contrib.
> 
> I got an error:
> usage: metagenome_pipeline.py [-h] -i PATH -f PATH [-m PATH]
> [--max_nsti FLOAT] [--min_reads INT]
> [--min_samples INT] [--strat_out] [--wide_table]
> [--skip_norm] [-o PATH] [-v]
> metagenome_pipeline.py: error: unrecognized arguments: -o EC_metagenome_out --metagenome_contrib
> 
> Any help with this one? Thanks!

How did you solve this error?

**Comment by gavinmdouglas** [comment]
Hi @MonicaSteffi,

The option ```--metagenome_contrib``` has not been used for a few versions and now that functionality is performed when the ```--strat_out``` option is used. You can see the tutorial for details.


Cheers,

Gavin
