### ISSUE TITLE
error in picrust analysis

### ISSUE THREAD

**Issue by Muneer111** [picrust/picrust2#159]
Hello Sir
I am trying to analyze my samples, 
however running the command I got the error 
stopping - no asv ids overlap between input fasta and sequence abundance table
but then trying for alternative method I also got the error as mentioned below 
place_seqs.py -s Narwani_final/Narwani_clustered_sequences/dna-sequences.fasta -o out.tre -p 1 --intermediate intermediate/place_seqs/epa_out/epa_result.jplace
Warning - 41 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences). These input sequences will not be placed and will be excluded from downstream steps.

This is the set of poorly aligned input sequences to be excluded: 836908, 4297918, 109469, 2456449, 250705, 521852, 328281, 208800, 3407058, 4406763, 237889, 779617, 323600, 4348417, 182490, 4469859, 706095, 2432071, 74159, 583766, 131662, 242389, 4396376, 1110769, 737413, 714536, 193866, 774802, 4386673, 4421746, 1124836, 91492, 211578, 4383626, 4446022, 548510, 1119783, 651305, 259220, 712007, 357092

Error running this command:
epa-ng --tree /home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa intermediate/place_seqs/epa_out/epa_result.jplace/ref_seqs_hmmalign.fasta --query intermediate/place_seqs/epa_out/epa_result.jplace/study_seqs_hmmalign.fasta --chunk-size 5000 -T 1 -m /home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w intermediate/place_seqs/epa_out/epa_result.jplace/epa_out --filter-acc-lwr 0.99 --filter-max 100

Standard output of the above failed command:
INFO Selected: Output dir: intermediate/place_seqs/epa_out/epa_result.jplace/epa_out/
INFO Selected: Query file: intermediate/place_seqs/epa_out/epa_result.jplace/study_seqs_hmmalign.fasta
INFO Selected: Tree file: /home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre
INFO Selected: Reference MSA: intermediate/place_seqs/epa_out/epa_result.jplace/ref_seqs_hmmalign.fasta
INFO Selected: Filtering by accumulated threshold: 0.99
INFO Selected: Maximum number of placements per query: 100
INFO Selected: Automatic switching of use of per rate scalers
INFO Selected: Preserving the root of the input tree
INFO Selected: Specified model file: /home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model
INFO    Rate heterogeneity: GAMMA (4 cats, mean),  alpha: 0.453141 (user),  weights&rates: (0.25,0.0250674) (0.25,0.220229) (0.25,0.782933) (0.25,2.97177) 
        Base frequencies (user): 0.229585 0.22008 0.298596 0.251739 
        Substitution rates (user): 1.00319 2.79077 1.5301 0.87441 3.83966 1
INFO Selected: Reading queries in chunks of: 5000
INFO Selected: Using threads: 1
INFO     ______ ____   ___           _   __ ______
        / ____// __ \ /   |         / | / // ____/
       / __/  / /_/ // /| | ______ /  |/ // / __  
      / /___ / ____// ___ |/_____// /|  // /_/ /  
     /_____//_/    /_/  |_|      /_/ |_/ \____/ (v0.3.6)

I am stuck in this from a long time 
Please suggest

**Comment by gavinmdouglas** [comment]
Hi again,

I believe you're running into issues now due to having insufficient RAM. You can get around this by running SEPP with the qiime 2 plugin instead (see: https://github.com/picrust/picrust2/wiki/Swapping-in-SEPP-for-read-placement-with-q2-picrust2).

Alternatively you could try a different metagenome prediction tool such as Piphillin, which uses a web portal: https://piphillin.secondgenome.com/


Cheers,

Gavin

**Comment by Muneer111** [comment]
Hello Sir 
I think this command run was through SEPP is not it
place_seqs.py -s Narwani_final/Narwani_clustered_sequences/dna-sequences.fasta -o out.tre -p 1 --intermediate intermediate/place_seqs/epa_out/epa_result.jplace
Warning - 41 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences). These input sequences will not be placed and will be excluded from downstream steps.

This is the set of poorly aligned input sequences to be excluded: 836908, 4297918, 109469, 2456449, 250705, 521852, 328281, 208800, 3407058, 4406763, 237889, 779617, 323600, 4348417, 182490, 4469859, 706095, 2432071, 74159, 583766, 131662, 242389, 4396376, 1110769, 737413, 714536, 193866, 774802, 4386673, 4421746, 1124836, 91492, 211578, 4383626, 4446022, 548510, 1119783, 651305, 259220, 712007, 357092

Error running this command:
epa-ng --tree /home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa intermediate/place_seqs/epa_out/epa_result.jplace/ref_seqs_hmmalign.fasta --query intermediate/place_seqs/epa_out/epa_result.jplace/study_seqs_hmmalign.fasta --chunk-size 5000 -T 1 -m /home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w intermediate/place_seqs/epa_out/epa_result.jplace/epa_out --filter-acc-lwr 0.99 --filter-max 100

Standard output of the above failed command:
INFO Selected: Output dir: intermediate/place_seqs/epa_out/epa_result.jplace/epa_out/
INFO Selected: Query file: intermediate/place_seqs/epa_out/epa_result.jplace/study_seqs_hmmalign.fasta
INFO Selected: Tree file: /home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre
INFO Selected: Reference MSA: intermediate/place_seqs/epa_out/epa_result.jplace/ref_seqs_hmmalign.fasta
INFO Selected: Filtering by accumulated threshold: 0.99
INFO Selected: Maximum number of placements per query: 100
INFO Selected: Automatic switching of use of per rate scalers
INFO Selected: Preserving the root of the input tree
INFO Selected: Specified model file: /home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model
INFO Rate heterogeneity: GAMMA (4 cats, mean), alpha: 0.453141 (user), weights&rates: (0.25,0.0250674) (0.25,0.220229) (0.25,0.782933) (0.25,2.97177)
Base frequencies (user): 0.229585 0.22008 0.298596 0.251739
Substitution rates (user): 1.00319 2.79077 1.5301 0.87441 3.83966 1
INFO Selected: Reading queries in chunks of: 5000
INFO Selected: Using threads: 1
INFO ______ ____ ___ _ __ ______
/ // __ \ / | / | / // /
/ __/ / // // /| | ______ / |/ // / __
/ / / // ___ |/_____// /| // // /
/_____/// // || // |/ __/ (v0.3.6)


Secondly
The main pipe line showed this error
stopping - no asv ids overlap between input fasta and sequence abundance table

Thirdly 
I did get my samples analyzed through piphillin  and from there I got two files one is pathway and other is feature table.
In which I got keg ids and some values of the sample.
There I am wondering how to interpret results and which file to use.

Please suggest
