### ISSUE TITLE
Error with generating the pathway-level abundance table

### ISSUE THREAD

**Issue by ytaoo** [picrust/picrust2#160]
Hi,

I tried to run the complete picrust2 pipeline but it stopped when it reached the pathway-level inference step reporting an open file error. So I redid this step and it happened again. Does anyone know how to fix this issue? 

my code:
picrust2_out_pipeline Yiran$ pathway_pipeline.py -i EC_metagenome_out/pred_metagenome_contrib.tsv.gz \
>                     -o pathways_out -p 1

Error running this command:
/opt/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/MinPath/MinPath12hmp.py -any /var/folders/v_/db8wgzrn3356lyjnwllnjv_00000gn/T/tmp2c8rio75/minpath_running/VCa1-38_S38 Abundance_minpath_in.txt -map /var/folders/v_/db8wgzrn3356lyjnwllnjv_00000gn/T/tmp2c8rio75/parsed_mapfile.tsv -report /var/folders/v_/db8wgzrn3356lyjnwllnjv_00000gn/T/tmp2c8rio75/minpath_running/VCa1-38_S38 Abundance_minpath_report.txt -details /var/folders/v_/db8wgzrn3356lyjnwllnjv_00000gn/T/tmp2c8rio75/minpath_running/VCa1-38_S38 Abundance_minpath_details.txt -mps /var/folders/v_/db8wgzrn3356lyjnwllnjv_00000gn/T/tmp2c8rio75/minpath_running/VCa1-38_S38 Abundance_minpath.mps

Standard error of the above failed command:
open file error /var/folders/v_/db8wgzrn3356lyjnwllnjv_00000gn/T/tmp2c8rio75/minpath_running/VCa1-38_S38

**Comment by gavinmdouglas** [comment]
Hey @ytaoo,

It looks like this problem might be due to there being a space at the end of that sample name, which is causing issues when writing an outfile. I would check to see if there is a space present and remove it if so.


Cheers,

Gavin
