### ISSUE TITLE
Queries related to PICRUST 2 stand-alone version

### ISSUE THREAD

**Issue by upasanagupta127** [picrust/picrust2#161]
Good Morning everyone!
I am new to this platform. Currently, I am using QIIME 2 2020.11 from where i got  seq.qza and table.qza files format as my qiime 2 output files and now I want to analyze my results using Picrust 2 stand-alone version (as of my knowledge q2-picrust2 plugin is not compatible with the lastest qiime 2 version) for that i need seqs.fna and featuretable.biom as the input files. but, I don't have those input files as the have mentioned above (using qiime 2 202.11). Could anyone please help me with this. It will be a great help.

Thanks & Regard
Upasana Gupta

**Comment by AbhishakeL** [comment]
Unzip the .qza folders and you will have the files in the corresponding data folder... You can also look into extract command from qiime2..

**Comment by upasanagupta127** [comment]
> Unzip the .qza folders and you will have the files in the corresponding data folder... You can also look into extract command from qiime2 

Thanks for your suggestions, will definitely going to try .

Thanks alot
Upasana Gupta
