### ISSUE TITLE
error running pathway_pipeline

### ISSUE THREAD

**Issue by jamlover** [picrust/picrust2#162]
I am getting an error running pathway_pipeline. My command was as follows:

/data/progs/picrust2/scripts/pathway_pipeline.py -i EC_metagenome_out/pred_metagenome_contrib.tsv.gz -o MetaCycPathways -p 8 --verbose >pathway_pipeline.verbose.log

While running, much output went to the terminal, looking like this:
.....

/data/progs/picrust2/picrust2/MinPath/MinPath12hmp.py -any /tmp/tmp_5m5cfew/minpath_running/FMC-W09_minpath_in.txt -map /tmp/tmp_5m5cfew/parsed_mapfile.tsv -report /tmp/tmp_5m5cfew/minpath_running/FMC-W09_minpath_report.txt -details /tmp/tmp_5m5cfew/minpath_running/FMC-W09_minpath_details.txt -mps /tmp/tmp_5m5cfew/minpath_running/FMC-W09_minpath.mps

/data/progs/picrust2/picrust2/MinPath/MinPath12hmp.py -any /tmp/tmp_5m5cfew/minpath_running/FMC-W10_minpath_in.txt -map /tmp/tmp_5m5cfew/parsed_mapfile.tsv -report /tmp/tmp_5m5cfew/minpath_running/FMC-W10_minpath_report.txt -details /tmp/tmp_5m5cfew/minpath_running/FMC-W10_minpath_details.txt -mps /tmp/tmp_5m5cfew/minpath_running/FMC-W10_minpath.mps

/data/progs/picrust2/picrust2/MinPath/MinPath12hmp.py -any /tmp/tmp_5m5cfew/minpath_running/FMC-W11_minpath_in.txt -map /tmp/tmp_5m5cfew/parsed_mapfile.tsv -report /tmp/tmp_5m5cfew/minpath_running/FMC-W11_minpath_report.txt -details /tmp/tmp_5m5cfew/minpath_running/FMC-W11_minpath_details.txt -mps /tmp/tmp_5m5cfew/minpath_running/FMC-W11_minpath.mps

etc., etc.

..... If I do a "ls" command of the minpath_running temp directory while all this is happening many files appear.....
 ls /tmp/tmp_5m5cfew/minpath_running/
890-W01_minpath_details.txt
BRF-W11_minpath_details.txt
FVC-W08_minpath_details.txt
HLR-W04_minpath_details.txt
LCF-W01_minpath_details.txt
890-W01_minpath_in.txt
BRF-W11_minpath_in.txt 
FVC-W08_minpath_in.txt 
HLR-W04_minpath_in.txt
LCF-W01_minpath_in.txt
890-W01_minpath_report.txt
BRF-W11_minpath_report.txt
FVC-W08_minpath_report.txt
HLR-W04_minpath_report.txt
LCF-W01_minpath_report.txt
etc., etc., etc.

But then eventually the error occurs:

joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/data/progs/envs/picrust2/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/data/progs/envs/picrust2/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/data/progs/envs/picrust2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/data/progs/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/data/progs/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data/progs/picrust2/picrust2/pathway_pipeline.py", line 859, in contrib_format_pathway_levels
    print_opt)
  File "/data/progs/picrust2/picrust2/pathway_pipeline.py", line 673, in minpath_wrapper
    id_minpath_fh = open(minpath_in, "w")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_5m5cfew/minpath_running/Reads/OTU_minpath_in.txt'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/progs/picrust2/scripts/pathway_pipeline.py", line 272, in <module>
    main()
  File "/data/progs/picrust2/scripts/pathway_pipeline.py", line 210, in main
    verbose=args.verbose)
  File "/data/progs/picrust2/picrust2/pathway_pipeline.py", line 398, in pathway_pipeline
    for sample_id in samples)
  File "/data/progs/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/data/progs/envs/picrust2/lib/python3.6/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/data/progs/envs/picrust2/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/data/progs/envs/picrust2/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/data/progs/envs/picrust2/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_5m5cfew/minpath_running/Reads/OTU_minpath_in.txt'

After the error the /tmp directory is empty:
(base) [jmartins@d2626ujmartins3 picrust2_output_stratified]$ ls /tmp

At the end of the log file where I was capturing STDOUT is the following:
.....
pathway 572 573 UDPNAGSYN-PWY path2fam 5  real-family 5
this pathway is added back
pathway 574 575 VALSYN-PWY path2fam 4  real-family 4
this pathway is added back
added pathway = 228

Results are saved in file:/tmp/tmp_5m5cfew/minpath_running/UST-W14_minpath_report.txt
Details are saved in file:/tmp/tmp_5m5cfew/minpath_running/UST-W14_minpath_details.txt

Any idea of what might be going on?

Thanks

**Comment by jamlover** [comment]
After examining the error message some more and comparing it to my input file, I got the program to run to completion by doing the following. At the bottom of my stratified input file were multiple "Reads/OTU" lines. I removed those lines and reran the command and the error did not occur and output was produced. I then tried an unstratified input file (which had also failed when I tried it previously). In that file I noted that Reads/OTU occurred as the last column of every line, so I removed that column, and again, after doing that, there was no error and output was produced.

I would appreciate any insight into the "Reads/OTU" input files I was originally using, the correctness/incorrectness of my solution, etc., etc.

Thanks,
John Martinson

**Comment by gavinmdouglas** [comment]
Hey @jamlover,

That certainly sounds odd! If you don't mind sending me your original input BIOM table and FASTA to me at <img width="144" alt="gmail_screenshot" src="https://user-images.githubusercontent.com/12489683/107864422-4cbff200-6e32-11eb-804c-7c7c05985010.png"> I can take a look and help troubleshoot!


All the best,

Gavin

**Comment by jamlover** [comment]
Gavin,

Here are the requested files.

Thanks,
John

**Comment by gavinmdouglas** [comment]
Sorry I don't seem them attached - would you mind emailing them to the email address I posted above?

**Comment by jamlover** [comment]
Sorry. Missed that. Sending momentarily via gmail.

**Comment by gavinmdouglas** [comment]
Hey @jamlover,

The last column in your BIOM file is "Reads/OTU" which seems like it's causing the problem. I would remove this column (or ignore it in your analyses as you have been doing). The slash causes a problem because the pathway script makes temporary output files and it gets confused by the slash because it thinks it's specifying a directory path.


Cheers,

Gavin

**Comment by jamlover** [comment]
Gavin,

Thanks. I inherited the file from a person I am helping and I'm guessing in the spreadsheet version of the OTU table they shared with me they probably added that column for their own purposes. I did not note it, and the convert to
biom process I used apparently didn't care either, so it was still in there to cause problems.

Take care and appreciate you looking it over.

**Comment by gavinmdouglas** [comment]
No worries at all!
