### ISSUE TITLE
KEGG_Pathways_to_KO.tsv

### ISSUE THREAD

**Issue by mysfxh** [picrust/picrust2#163]
你好，我发现这个文件中的 ko00312在kegg pathway maps中并不存在，通过add_descriptions.py 注释后发现 ko00312 在Kegg pathway maps编号是ko01501

Hello, I found that KO00312 in this file does not exist in the KEGG pathway maps. Through add_tools.py annotation, I found that KO00312 in the KEGG pathway maps number is KO01501

**Comment by mysfxh** [comment]
https://www.genome.jp/kegg-bin/show_brite?br08901.keg

**Comment by gavinmdouglas** [comment]
Hi @mysfxh,

The KEGG mapping packaged with PICRUSt2 is the last version that was publicly available. There are definitely differences with the latest version of KEGG - thanks for pointing this one out!


Gavin

**Comment by vivenha** [comment]
> Hi @mysfxh,
> 
> The KEGG mapping packaged with PICRUSt2 is the last version that was publicly available. There are definitely differences with the latest version of KEGG - thanks for pointing this one out!
> 
> Gavin

Hi @gavinmdouglas ,
I am wondering if the KEGG database used in PICRUSt2 is the latest version. On the KEGG website, the last update was on April 4, 2024. However, I noticed that the last commit date for the **KEGG_modules_info.tsv.gz** file in the PICRUSt2 GitHub repository (located at picrust2/picrust2/default_files/description_mapfiles/) was five years ago. Does this mean that the default pipeline of PICRUSt2 uses the 2019 version of KEGG for annotation? Thank you!
