### ISSUE TITLE
not getting pred_metagenome_strat file after metagenome_pipeline.py

### ISSUE THREAD

**Issue by carlmed00** [picrust/picrust2#166]
Hello!

I am trying the pipeline using my dataset and it seems that even with --strat_out, I am unable to see a metagenome_strat file generated in my folder.

It only gerated 4 files (pred_metagenome_contrib, pred_metagenom_unstrat, seqtab_norm, and weighted_nsti)

is the metagenome_contrib the stratified file I can use?

Thank you very much in advance!

**Comment by gavinmdouglas** [comment]
Hey @carlmed00,

Yes that is the stratified file to use! You can see it described in detail in this tutorial: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.3.0-beta)


Thanks,

Gavin

**Comment by carlmed00** [comment]
> Hey @carlmed00,
> 
> Yes that is the stratified file to use! You can see it described in detail in this tutorial: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.3.0-beta)
> 
> Thanks,
> 
> Gavin

Ohh! I got the new version bas was looking at the tutorial of the older version. Thank you!

All the best!
