### ISSUE TITLE
error in place_seqs.py

### ISSUE THREAD

**Issue by mingy64** [picrust/picrust2#170]
Hi. there

I have a problem with place_seqs.py step.

I used picrust2 old version with no problem. But, My colleague installs picrust2 latest version on the same computer. 
At that time we have a problem with place_seqs.py step.
I used a total 1000 ASV sequence fasta file. And the RAM is enough too.

The error message is :

#input command
(picrust2) user@user:~/miniconda3/envs/picrust2/bin/210402_out$ place_seqs.py -s ../test.fna -o out.tre --intermediate intermediate/place_seqs

Error running this command:
epa-ng --tree /home/algae/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa intermediate/place_seqs/ref_seqs_hmmalign.fasta --query intermediate/place_seqs/study_seqs_hmmalign.fasta --chunk-size 5000 -T 1 -m /home/algae/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w intermediate/place_seqs/epa_out --filter-acc-lwr 0.99 --filter-max 100

Standard output of failed command:
"INFO Selected: Output dir: intermediate/place_seqs/epa_out/
INFO Selected: Query file: intermediate/place_seqs/study_seqs_hmmalign.fasta
INFO Selected: Tree file: /home/algae/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre
INFO Selected: Reference MSA: intermediate/place_seqs/ref_seqs_hmmalign.fasta
INFO Selected: Filtering by accumulated threshold: 0.99
INFO Selected: Maximum number of placements per query: 100
INFO Selected: Specified model file: /home/algae/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model
"

Standard error of failed command:
"terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid model name:
"

I would appreciate it if you could feedback on this question.

**Comment by gavinmdouglas** [comment]
Hey there,

I haven’t seen that error before - I would suggest re-downloading the tool to make sure that the reference files aren’t malformed. If not can you confirm what version you’re using? Is it v2.4.1?


Thanks,

Gavin

**Comment by mingy64** [comment]
Thank you for your response.

I try to delete picrust2 envs (using command : conda remove -n picrust2 --all ). 
And, reinstall the latest version. but, the error message is the same.

I don't know what I used version (old version), but, I downloaded it in 2018. 11. 06
