### ISSUE TITLE
filtering contrib and unstrat files

### ISSUE THREAD

**Issue by carlmed00** [picrust/picrust2#171]
Good day! 

Is it possible to filter both contrib and unstrat files to create tables containing only functions or KO of interest?

Thank you very much in advance!

**Comment by gavinmdouglas** [comment]
Hey @carlmed00,

You could use grep to filter the rows of the tables to KOs you're interested in.

For example:
```
# Get the header:
zcat pred_metagenome_contrib.tsv.gz | head -n 1 > contrib_subset.tsv

# Get all rows corresponding to either K00003 or K19353.
zcat pred_metagenome_contrib.tsv.gz | grep 'K00003\|K19353' >> contrib_subset.tsv
```

**Comment by carlmed00** [comment]
> Hey @carlmed00,
> 
> You could use grep to filter the rows of the tables to KOs you're interested in.
> 
> For example:
> 
> ```
> # Get the header:
> zcat pred_metagenome_contrib.tsv.gz | head -n 1 > contrib_subset.tsv
> 
> # Get all rows corresponding to either K00003 or K19353.
> zcat pred_metagenome_contrib.tsv.gz | grep 'K00003\|K19353' >> contrib_subset.tsv
> ```

Got it!

Thank you very much!
