### ISSUE TITLE
interpretion of stratified pathway abundances

### ISSUE THREAD

**Issue by maque4004** [picrust/picrust2#172]
Hi developer,
My data is 16S rRNA data. To get KEGG pathway stratified abundances file, I ran 
`picrust2_pipeline.py -s sequences.fasta -i rarefied-otu-table.biom -o picrust2-pipeline-out/ --stratified`
`pathway_pipeline.py -i KO_metagenome_out/pred_metagenome_contrib.tsv.gz -o KEGG_pathways_out -m /picrust2-2.3.0-b/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv --no_regroup` 
and generated file path_abun_contrib.tsv.gz,  a table with columns for both pathways and sequences along with the abundance within each sample.

I noticed that, for example, I have two samples: A and B, sequence S is abundant in both samples. for pathway P, only in sample A, S contributed (let' say) 100 abundances to P; However, in sample B, S contributed none to P. 
I don't understand why this happen. I supposed that the contribution of sequence S to pathway P in sample A and sample B was positively correlated with the abundance of S in sample A and B. At least, for pathway P, S wouldn't contributed in one sample while not in another.
Did I misinterpret anything?

Thank you in advance!

Best,
Jericho

**Comment by gavinmdouglas** [comment]
Hey @maque4004,

If you want the per sequence contributions of a pathway you will need to use the ```--per_sequence_contrib``` option, which predicts pathway abundances for each sequence separately.

In contrast, for the default usage the contributional format gives the breakdown of how each sequence contributes to the sample (i.e. community)-wide pathway abundances using a naive approach of how many genes involved in that pathway that the sequence is predicted to encode.

This answer might also help: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#what-is-the-difference-between-the-default-and---per_sequence_contrib-pathway-output
