### ISSUE TITLE
running picrust2 in cygwin

### ISSUE THREAD

**Issue by tcrispino13** [picrust/picrust2#173]
Hi there, I am new tp picrust2 I have already downloaded the installation files and was supposed to run it in cygwin, Can anyone help me how could I proceed. Im not sure if I installed it properly as I cannot see any exe file to be executed. I am using Windows 10. Thank you so much for your help!

**Comment by gavinmdouglas** [comment]
Hi @tcrispino13,

PICRUSt2 has only been tested on Linux and Mac systems. I think there are now better linux emulators than cygwin which might be more able to use linux tools, but I'm not familiar with them myself.


Cheers,

Gavin
