### ISSUE TITLE
rarefied table

### ISSUE THREAD

**Issue by maque4004** [picrust/picrust2#175]
Hi developer,

https://github.com/picrust/picrust2/wiki/q2-picrust2-Tutorial
In the tutorial, the input table is a table with read counts, before the downstream analysis (like diversity analysis), we need to rarefied the generated q2-picrust2_output/pathway_abundance.qza to a certain depth.
My question is:  if I input a rarefied table,  then I will NOT need to rarefy the output pathway_abundance.qza before downstream analysis?
Or it's best to input a raw table, then rarefy?

Thank you!

Best,
Jericho

**Comment by gavinmdouglas** [comment]
Hi there,

I would still rarefy afterwards in this case just to make the comparison fairer, but which analysis approach is better is largely undetermined honestly.

I would suggest you avoid rarefying data in general and use compositional data analysis methods instead. See here: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#should-i-rarefy-or-transform-the-predictions-after-running-picrust2

**Comment by maque4004** [comment]
Thank you!
