### ISSUE TITLE
Add description using custom table maps error

### ISSUE THREAD

**Issue by tcrispino13** [picrust/picrust2#176]
Hello! I've ben trying to use the add description command of picrust2 and been following this link: 
https://github.com/Jiung-Wen/picrust_mapping
I am using these scripts for my run:
srun conda init bash
source activate picrust2
add_descriptions.py -i out_pipeline/pathways_out/path_abun_unstrat.tsv -m METACYC \
		    --custom_map_table picrust_mapping-master/metacyc_pathways_info_prokaryotes_top_level.tsv 
		    -o pathways_out/path_abun_unstrat_descriplevel1.tsv

But I keep on having error during my run.
Here's the error message:
usage: add_descriptions.py [-h] -i PATH -o PATH
                           [-m {METACYC,COG,EC,KO,PFAM,TIGRFAM}]
                           [--custom_map_table PATH] [-v]
add_descriptions.py: error: the following arguments are required: -o/--output
/var/spool/slurm/job226071/slurm_script: line 25: -o: command not found

I want to know what am I doing wrong here, thank you so much for your help!

**Comment by gavinmdouglas** [comment]
Hi there,

That error means that the `-o` argument wasn't provided. Is it possible that the command you copied was pasted as separate commands? I would make sure there are no newline characters causing issues.


Cheers,

Gavin

**Comment by tcrispino13** [comment]
Hi Gavin, it turns out you have to add \ after the --custom_table command. It works now! Thanks!

**Comment by gavinmdouglas** [comment]
Hi @tcrispino13,

Yes that character is used to denote that a newline shouldn't be added when a command is type over multiple lines (that's a linux thing, not something specific to this tool).


Cheers,

Gavin
