### ISSUE TITLE
How to generate KO contribution file

### ISSUE THREAD

**Issue by safiraloebis** [picrust/picrust2#177]
Hi, I notice that the EC folder can generate a contribution table as mentioned so:

EC_metagenome_out/pred_metagenome_contrib.tsv.gz (download) - A stratified table in "contributional" format breaking down how the ASVs contribute to gene family abundances in each sample.

However, I can't seem to find this function for KO predictions. BURRITO works best processing KO predictions due to the default hierarchy it can work with. Working with EC predictions in BURRITO means needing to create our own hierarchy file. 

If anyone could reply with the needed command that'd be great. Thanks.

**Comment by gavinmdouglas** [comment]
Hi there,

KO predictions can be generated just like EC number predictions, and are done independently. The commands are all the same except you would replace "EC" with "KO". Does that answer your question? 


Cheers,

Gavin
