### ISSUE TITLE
Add description levels using KEGG modules and pathways 

### ISSUE THREAD

**Issue by tcrispino13** [picrust/picrust2#179]
Hi, I am using these commands to add descriptions to my outputs. I checked the default files for these commands for KEGG and there are two (modules and pathways) but in my outputs does not show such descriptions. Am I doing something wrong on my commands?

add_descriptions.py -i EC_metagenome_out/pred_metagenome_unstrat.tsv.gz -m EC \
                    -o EC_metagenome_out/pred_metagenome_unstrat_descrip.tsv.gz

add_descriptions.py -i KO_metagenome_out/pred_metagenome_unstrat.tsv.gz -m KO \
                    -o KO_metagenome_out/pred_metagenome_unstrat_descrip.tsv.gz

add_descriptions.py -i pathways_out/path_abun_unstrat.tsv.gz -m METACYC \
                    -o pathways_out/path_abun_unstrat_descrip.tsv.gz

**Comment by gavinmdouglas** [comment]
Hi there,

Each of those commands look correct. If they're still not working for you then you can send the input files to me here and I can help troubleshoot:   <img width="144" alt="gmail_screenshot" src="https://user-images.githubusercontent.com/12489683/116812164-abd4ff00-ab23-11eb-8fdd-ab8489d08f99.png">

**Comment by tcrispino13** [comment]
Hi Gavin, I tried your suggestion from the email you send to me, however when I run this command:

pathway_pipeline.py -i out_pipeline_aldex/KO_metagenome_out/pred_metagenome_strat.tsv -o KEGG_pathways_out --no_regroup --map picrust2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv

(I generated the pred_metagenome_strat.tsv using the --stratified command options).
I encountered this error:
This input file was not found: picrust2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv

Does this mean I should manually copy the default files to my conda environment.

**Comment by gavinmdouglas** [comment]
Hi there,

That command mean that there’s no file found at the relative path "picrust2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv”.

You need to point that path to where that file actually is. The file will be found where PICRUSt2 is installed on your system, but it might be hard to find. A solution would be to download the github repo (no need to reinstall), which contains that file: https://github.com/picrust/picrust2.

**Comment by gavinmdouglas** [comment]
Hi @tcrispino13,

What version of PICRUSt2 did you use to create `out_pipeline_aldex/KO_metagenome_out/pred_metagenome_strat.tsv`? Wide table formatted results were last output in a version from several years ago.

You can specify the `--wide_table` option to still specify that you want to read in the table in that format though by the way - it just tends to be more memory intensive to handle tables in that format.

**Comment by tcrispino13** [comment]
I used the latest version to create the out_pipeline_aldex/KO_metagenome_out/pred_metagenome_strat.tsv. 

I re run the command using the stratified command option:
picrust2_pipeline.py -s seq.fna -i otutable.TSV -o final_out_pipeline_strat -p 1 --stratified
to get the input for this command:
pathway_pipeline.py -i KO_metagenome_out/pred_metagenome_strat.tsv -o KEGG_pathways_out --no_regroup --map picrust2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv

However, even with the --stratified command option, I wasnt able to get the stratified table. 
What should I do? Thank you so much

**Comment by gavinmdouglas** [comment]
Sorry, do you mean that no stratified output table is being created or that only a wide-format table is being created?

If it's the former then I think it's probably a memory limitation on the system you're working on. If only a wide-format table is created then there must be something wrong with your installation (maybe multiple versions installed?), because wide-format tables are not created in the latest version.


Gavin

**Comment by tcrispino13** [comment]
Hi, there is no stratified output table from these commands:
picrust2_pipeline.py -s seq.fna -i otutable.TSV -o final_out_pipeline_strat -p 1 --stratified
I think that memory is not the problem here because I am running the command in a high performance computing server already. Thanks for your help!

**Comment by gavinmdouglas** [comment]
Sorry for the delayed response - is this still a problem for you? If you are able to track how much memory the command used at peak then that would help determine whether high memory usage was the problem.
