### ISSUE TITLE
Do feature sequence (.fasta) need to be filtered when feature table (.biom) is filtered?

### ISSUE THREAD

**Issue by wangkai7** [picrust/picrust2#181]
Before processing picrust2, I excluded features that occurred in less than two samples. Do I need to filter the corresponding feature sequence file?

**Comment by gavinmdouglas** [comment]
If you're running `picrust2_pipeline.py` then no it's not necessary, but if you're running `place_seqs.py` directly then you could to speed up the running time.

Cheers,

Gavin
