### ISSUE TITLE
open file error /tmp/tmpqu1b3gv2/minpath_running/Unnamed:

### ISSUE THREAD

**Issue by xhxlilium** [picrust/picrust2#184]
Error running this command:
/root/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/MinPath/MinPath12hmp.py -any /tmp/tmpqu1b3gv2/minpath_running/Unnamed: 10_minpath_in.txt -map /tmp/tmpqu1b3gv2/parsed_mapfile.tsv -report /tmp/tmpqu1b3gv2/minpath_running/Unnamed: 10_minpath_report.txt -details /tmp/tmpqu1b3gv2/minpath_running/Unnamed: 10_minpath_details.txt -mps /tmp/tmpqu1b3gv2/minpath_running/Unnamed: 10_minpath.mps

Standard error of the above failed command:
open file error /tmp/tmpcd5u16_l/minpath_running/Unnamed:

**Comment by gavinmdouglas** [comment]
Hi @xhxlilium,

Is there a sample or a sequence called "Unnamed: 10" in your dataset? The problem is that the colon and/or the space in the name is causing problems when a temporary file is being created. You can remove these characters from the name and this problem should be resolved.


Cheers,

Gavin

**Comment by xhxlilium** [comment]
> Hi @xhxlilium,
> 
> Is there a sample or a sequence called "Unnamed: 10" in your dataset? The problem is that the colon and/or the space in the name is causing problems when a temporary file is being created. You can remove these characters from the name and this problem should be resolved.
> 
> Cheers,
> 
> Gavin
yeah, I have addressed this problem by your advice. Thank you very much! I guess this may be a bug of picrust2, as my raw data did not have "Unnamed: 10". However, after running the procession, this colunm was added, and made the error. Maybe in the future the space between the "Unnamed:" and "10" would be discarded. 
Thanks again!
