### ISSUE TITLE
picrust2

### ISSUE THREAD

**Issue by kellyshannon99** [picrust/picrust2#186]
Hello, I am sorry to bring this issue back up, but I have read all of the conversations on here that I could find and have still not been able to solve it. I'm running into issues running the command: 

hsp.py -i 16S -t out.tre -o marker_predicted_and_nsti.tsv.gz -p 1 -n

And am getting the following error: 

Error running this command:
Rscript /Users/kellyshannon/opt/anaconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/Rscripts/castor_nsti.R out.tre /var/folders/8x/xnfvrmrs6430gh1s7wbk6zsm0000gq/T/tmp63mbn13m/known_tips.txt /var/folders/8x/xnfvrmrs6430gh1s7wbk6zsm0000gq/T/tmp63mbn13m/nsti_out.txt

Standard error of the above failed command:
Error: package or namespace load failed for ‘castor’ in library.dynam(lib, package, package.lib):
 shared object ‘Matrix.dylib’ not found
In addition: Warning message:
package ‘Rcpp’ was built under R version 4.0.5 
Execution halted

Now, I believe I got around the similar error to this with the Rcpp package by uninstalling it on Rstudio. I did the same with castor on Rstudio but uninstalling did not seem to fix it. When I go into my .libPaths() pathway, where it could be on Rstudio, I also do not see it. Also <which R> returns: </Users/kellyshannon/opt/anaconda3/envs/picrust2/bin/R> so the R package seems to be in the right place and I see that castor is also installed. Any help would be greatly appreciated, and apologize again for re-asking this question but I can't seem to find a solution from previous posts on the issue.

**Comment by gavinmdouglas** [comment]
Hi @kellyshannon99,

Are you referring to this past issue? https://github.com/picrust/picrust2/issues/143

Can you confirm that you can load the ```Matrix``` library? That looks like what's underlying this error. If not I would try installing it manually (or with conda, under ```r-matrix```) and see if that solves the problem.


Cheers,

Gavin

**Comment by kellyshannon99** [comment]
Oh, you know what I can load the Matrix library in RStudio and when I uninstalled I now get this error from the same picrust2 command: 

Standard error of the above failed command:
Error: package or namespace load failed for ‘castor’ in library.dynam(lib, package, package.lib):
 shared object ‘RSpectra.dylib’ not found
In addition: Warning message:
package ‘Rcpp’ was built under R version 4.0.5 
Execution halted

Seems like it's an issue with the packages in RStudio being prioritized over the picrust R tools. Also yes, that is the issue that I was referring to (#143). That's the first issue I had that went away after digging into RStudio and making sure Rcpp was uninstalled in my User Library and in .libPaths().

**Comment by kellyshannon99** [comment]
I have tried installing the specific libraries with conda and changing my PATH with: <PATH="Users/kellyshannon/miniconda3/bin:$PATH"> 
<export PATH>
But I couldn't get that to fix the issue. I had tried that with the Castor package originally.

**Comment by kellyshannon99** [comment]
Update: I got around the issue by uninstalling Matrix and Rspectra in RStudio! This isn't a huge deal because I can just go back and reinstall them in R, but it would be nice to have a workaround in conda. Anyway it looks like I have obtained the correct files: EC_predicted.tsv.gz and marker_predicted_and_nsti.tsv.gz

**Comment by gavinmdouglas** [comment]
Great to hear - thanks for posting your fix here!

**Comment by kellyshannon99** [comment]
Yep, thank you for your help as well! I would not have thought to look into that Matrix package in R.
