### ISSUE TITLE
r-httr missing from conda env?

### ISSUE THREAD

**Issue by russellsmithies** [picrust/picrust2#187]
I think `r-httr` is missing from the conda package and picrust2-env.yaml
While running the tutorial I was getting this error:
```
pikachu$ hsp.py -i 16S -t out.tre -o marker_predicted_and_nsti.tsv.gz -p 16 -n

Error running this command:
Rscript /opt/conda/envs/picrust2_2.4.1_singularity/lib/python3.6/site-packages/picrust2/Rscripts/castor_nsti.R out.tre /tmp/tmps_u0oujg/known_tips.txt /tmp/tmps_u0oujg/nsti_out.tx                                 t

Standard error of the above failed command:
Error in library(httr) : there is no package called 'httr'
Execution halted
```

When I added r-httr to the env everything worked :-)

**Comment by gavinmdouglas** [comment]
Thanks for pointing this out @russellsmithies,

R packages are often problematic with conda it seems. I can confirm that this is not always missing when it is installed PICRUSt2 with conda, but it's good to know that this can happen sometimes and that installing it separately fixes the problem
.

Thanks,

Gavin
