### ISSUE TITLE
Error - at least one trait in the prediction table was entirely missing values.

### ISSUE THREAD

**Issue by lisacangioli** [picrust/picrust2#189]
Hi everyone,
I tried to run the full picrust2 pipeline and also step by step on my work station but it returns this error every time.

picrust2_pipeline.py -s study_seqs_formatted.fna -i study_seqs.biom -o picrust2_out_pipeline -p 8 -t sepp

Error running this command:
hsp.py --tree picrust2_out_pipeline/out.tre --output picrust2_out_pipeline/marker_predicted_and_nsti.tsv.gz --observed_trait_table /home/ladylisa/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/16S.txt.gz --hsp_method mp --edge_exponent 0.5 --seed 100 --calculate_NSTI --processes 1

Standard error of the above failed command:

Error running this command:
Rscript /home/ladylisa/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/Rscripts/castor_hsp.R picrust2_out_pipeline/out.tre /tmp/tmpahm_5i8u/subset_tab_0 mp 0.5 FALSE FALSE /tmp/tmpeq38dw1w/predicted_counts.txt /tmp/tmpeq38dw1w/predicted_ci.txt 100

Standard error of the above failed command:
Error: 
Error - at least one trait in the prediction table was entirely missing values.
Execution halted

How can I do to solve the problem?

Thank you

**Comment by gavinmdouglas** [comment]
Hi there,

I think setting `--edge_exponent 0` or performing placement with EPA-ng would fix this problem. You can see this issue for the same issue and more details: https://github.com/gavinmdouglas/q2-picrust2/issues/13


Cheers,

Gavin

**Comment by lisacangioli** [comment]
Thank you very much, I immidiately try to run it! Inviato da Posta per Windows 10 Da: Gavin DouglasInviato: mercoledì 14 luglio 2021 15:11A: picrust/picrust2Cc: lisacangioli; AuthorOggetto: Re: [picrust/picrust2] Error - at least one trait in the prediction table was entirely missing values. (#189) Hi there,I think setting --edge_exponent 0 or performing placement with EPA-ng would fix this problem. You can see this issue for the same issue and more details: gavinmdouglas/q2-picrust2#13Cheers,Gavin—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  
	
      
		Mail priva di virus. www.avast.com

**Comment by lisacangioli** [comment]
Hi,
I tried to run the following command but a new error occurred.

picrust2_pipeline.py -s study_seqs_formatted.fna -i study_seqs.biom -o picrust2_out_pipeline -p 8 -t sepp -e 0

Error running this command:
hsp.py --tree picrust2_out_pipeline/out.tre --output picrust2_out_pipeline/KO_predicted.tsv.gz --observed_trait_table /home/ladylisa/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/ko.txt.gz --hsp_method mp --edge_exponent 0.0 --seed 100 --processes 8

Do you have other suggestions on what I can modify?
Thank you

**Comment by gavinmdouglas** [comment]
Hi there,

The pipeline normally stops there due to insufficient RAM. How much RAM does the computer you're using have? You could try running the command it printed directly and see whether a more descriptive error is returned.


Cheers,

Gavin
