### ISSUE TITLE
Error on metagenome_pipeline.py: error: unrecognized arguments: marker_predicted_and_nsti.tsv.gz

### ISSUE THREAD

**Issue by claudiavic** [picrust/picrust2#191]
Hi!
I'm getting an error on metagenome_pipeline.py:

metagenome_pipeline.py: error: unrecognized arguments: marker_predicted_and_nsti.tsv.gz

This enable to advance for the rest of the tutorial. 

How can I resolve this? 

Thanks in advance.

**Comment by gavinmdouglas** [comment]
Hi @claudiavic,

That error means that the ```-i``` label before that argument must not be present (or isn't being interpreted correctly). If you copied and pasted the command directly from the wiki you might want to paste it into a text editor that removes all formatting first (e.g., BBEdit or Notepad++). If that doesn't work would you mind pasting the exact command you're running?


Thanks,

Gavin
