### ISSUE TITLE
Error on: picrust2.util import

### ISSUE THREAD

**Issue by grenced2** [picrust/picrust2#192]
Hello Everyone,

I am receiving the following error message when attempting to run the full picrust2_pipeline:

File "picrust2_pipeline.py", line 13, in <module>
    from picrust2.util import make_output_dir, restricted_float
ImportError: cannot import name 'restricted_float'

Not sure what the cause is/how to address, any help would be greatly appreciated! Thank you in advance!

-Dennis

**Comment by gavinmdouglas** [comment]
Hi @grenced2,

How did you install the tool? Is it in a fresh conda environment? This error indicates that the program hasn't been installed correctly and/or that there are two conflicting versions installed.


Thanks,

Gavin

**Comment by grenced2** [comment]
Hi Gavin,

The program was installed on my institution's HPC by the computing team, so I will check in with them about this issue. Thank you for the insight, I have been really worried I accidentally made some kind of error (this is my first endeavor with bioinformatics!). Much appreciated overall!

-Dennis
