### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by cghiban** [picrust/picrust2#194]
Hi, any chance you can upgrade qiime2 picrust2 plugin? I can't install it with the latest qiime2 version. 

I tried installing it from the source, but the 1st thing I noticed was the python version was an issue:

`
$ qiime info

System versions

Python version: 3.8.8

QIIME 2 release: 2021.4
`

and in picrust2-env.yaml I see:
`
$ grep python picrust2-env.yaml

python >=3.5,<3.7
`

**Comment by crusher083** [comment]
Same issue.

**Comment by gavinmdouglas** [comment]
Thanks for reporting this - right now q2-picrust2 is versioned with qiime2-2021.2, but next time I make a release I'll bump the version of the qiime 2 plugin as well. In the meantime note that you can also use PICRUSt2 outside of QIIME 2.


Cheers,

Gavin

**Comment by Lisa-tuc** [comment]
Hi, I am new to this forum. I have installed Picrust2 using version 2.4.1. I am using qiime2-2021.4 and when I try qiime picrust2 full-pipeline it gives me this error: Error: QIIME 2 has no plugin/command named 'picrust2'.
Is there anyone who can help me? Thank you!
