### ISSUE TITLE
Absence of data for existing metabolic pathways

### ISSUE THREAD

**Issue by Hermann-CPU** [picrust/picrust2#196]
Hello!
First of all - thank You for the great picrust2 pipeline and regular updates - these are jolly helpful!
Also, we noticed that some pathways are not presented in the output files while we trying to predict amio acid biosynthesis pathway abundances for picked bacteria set. 
For example:
_CYSTSYN-PWY L-cysteine biosynthesis I
PHESYN L-phenylalanine biosynthesis I
PWY-3462 L-phenylalanine biosynthesis II
PROSYN-PWY L-proline biosynthesis I
SERSYN-PWY L-serine biosynthesis
HOMOSER-THRESYN-PWY L-threonine biosynthesis
PWY-3461 L-tyrosine biosynthesis II
TYRSYN L-tyrosine biosynthesis I
PWY-6120 L-tyrosine biosynthesis III_

May I kindly ask you for advice in order to channell my energy in the right direction? :)
Thank you!
Best regard, CPU.

**Comment by gavinmdouglas** [comment]
Hi @Hermann-CPU,

I believe those pathways are based on three or fewer reactions, which means they would not have been included in predictions made by PICRUSt2 and HUMAnN2 due to the difficulty of estimating pathway levels based on so few reactions.


Cheers,

Gavin

**Comment by Hermann-CPU** [comment]
Thank you, Gavin!
Best regards, Hermann.
