### ISSUE TITLE
place_seqs.py: No option `--print_cmds` only `--verbose`

### ISSUE THREAD

**Issue by crusher083** [picrust/picrust2#197]
![image](https://user-images.githubusercontent.com/61702053/128824922-6ae2ab58-3787-4a97-9356-f95e1df61080.png)

Adding `--print_cmds` results in error.
![image](https://user-images.githubusercontent.com/61702053/128825032-3eef012f-379b-4e86-a824-9c7658b5b00e.png)

Tried to fix the docs myself, but don't know how to edit wiki :)

**Comment by gavinmdouglas** [comment]
Thanks for catching that!
