### ISSUE TITLE
reproducibility of Picrust2

### ISSUE THREAD

**Issue by nightkid03** [picrust/picrust2#199]
Hi all,

I ran Picrust2 in three different datasets and compared the EC_predicted.tsv files.
Since the three datasets had some common ASVs, I thought the EC copy number of the common ASV should be same in all the three EC_predicted.tsv files. However, it is not.

I think the process of predicting EC copy number for each ASV is regardless of ASV abundance table. Is it possible that same ASV in different ASV sets will get different EC copy number result?

Has someone met same issue? And how to solve it?  Thank you!

**Comment by gavinmdouglas** [comment]
Hey @nightkid03,

This is a known issue where different combinations of ASVs will result in some variation in placement locations in the reference tree. This is largely a problem when EPA-ng is used so if you need reproducible placements/predictions then you can use SEPP for ASV placement instead.


Hopefully that helps,

Gavin

**Comment by nightkid03** [comment]
> Hey @nightkid03,
> 
> This is a known issue where different combinations of ASVs will result in some variation in placement locations in the reference tree. This is largely a problem when EPA-ng is used so if you need reproducible placements/predictions then you can use SEPP for ASV placement instead.
> 
> Hopefully that helps,
> 
> Gavin

Thank you Gavin. 
Does Picrust2 use EPA-ng  to place all sequences at one time but use SEPP to place sequence one by one? Thus, SEPP is good for reproducibility?

**Comment by gavinmdouglas** [comment]
No they both place multiple ASVs at once, but in my testing it turned out that SEPP is much more robust to the problem of variation in how the ASVs are placed.

**Comment by nightkid03** [comment]
> No they both place multiple ASVs at once, but in my testing it turned out that SEPP is much more robust to the problem of variation in how the ASVs are placed.

Maybe it is naive. Is it possible to place one by one in current/future version of Picrust2? I know place multiple ASVs is much faster.  But since Picrust2 places ASVs in a reference tree, it is better to make the result stable. Sometimes the difference is critical as same ASVs will be recognized as xxx producer, but in another dataset it is not.

**Comment by gavinmdouglas** [comment]
Yes that would be possible, but not implemented in PICRUSt2 itself at the moment. You could do that by looping over all of your ASVs and including only one ASV at a time in the input BIOM table / FASTA as you run the pipeline and then combine the results afterwards.


Cheers,

Gavin

**Comment by nightkid03** [comment]
> Yes that would be possible, but not implemented in PICRUSt2 itself at the moment. You could do that by looping over all of your ASVs and including only one ASV at a time in the input BIOM table / FASTA as you run the pipeline and then combine the results afterwards.
> 
> Cheers,
> 
> Gavin

Thank you Gavin. I guess it is run "Sequence placement" and "Hidden-state prediction" for each ASV individually. And then merge all x_predicted.tsv.gz into one file. Then run "Metagenome prediction", "Infer pathway abundances", "Add descriptions" . Is that right?

**Comment by gavinmdouglas** [comment]
Yes that would work!
