### ISSUE TITLE
The place of feature rarefaction when using `picrust2`

### ISSUE THREAD

**Issue by crusher083** [picrust/picrust2#201]
Hi, 

this is more of a general methodological question. 
If we use PICRUSt2, when in the pipeline should be samples rarefied? Is it on the OTU-table, before plugging it in? Or after predictions are made, on feature tables? 
Which would be the best practice? 

Cheers

**Comment by gavinmdouglas** [comment]
Hi @crusher083, this question is related to this FAQ: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#should-i-rarefy-or-transform-the-predictions-after-running-picrust2

I don't rarefy microbiome count data in general - for PICRUSt2 I would not rarefy the data at any point and either convert to relative abundances at the end or use a tool that can handle compositional data.
