### ISSUE TITLE
struct.error: 'i' format requires -2147483648 <= number <= 2147483647 

### ISSUE THREAD

**Issue by laurebindels** [picrust/picrust2#204]
Hi ! 

I ran Picrust2 on multiple datasets before with success. I have now applied it to the biggest dataset used so far (~270 samples). I got an error message at the pathway-inference level.

> pathway_pipeline.py -i EC_metagenome_out/pred_metagenome_contrib.tsv.gz -o pathways_out -p 4

> struct.error: 'i' format requires -2147483648 <= number <= 2147483647 

I looked online and it seems to be a memory issue that could be solved with the use of Python 3.8.
https://stackoverflow.com/questions/47776486/python-struct-error-i-format-requires-2147483648-number-2147483647 
I noticed that Picrust2 requierement includes <Python3.7, but I still tried to update python to 3.8 in a clone of my usual picrust2 conda environment. It didn't work :-).

My last idea was to split the datasets manually in two, run the step on both subsets and then merge the outcome. But I do not master the pipeline enough to be 100% sure that this is a good idea. What do you think ? Any other idea as how to solve my issue ?

Looking forward to reading from you, 
Thanks for the pipeline !

**Comment by gavinmdouglas** [comment]
Hey @laurebindels,

You can definitely split up the **samples** into different subsets and then run the pathway inference and join them again afterwards. This step is done independently for each sample anyway, but clearly it can cause memory issues sometimes with large sample numbers.


All the best,

Gavin

**Comment by laurebindels** [comment]
Hi  @gavinmdouglas, 

Thanks for the swift reply. I will proceed accordingly.

Have a lovely we, 
Best, 

Laure
