### ISSUE TITLE
Error - missing at least one of the four reference files in this specified directory: default_files/fungi/fungi_ITS

### ISSUE THREAD

**Issue by linfangxu** [picrust/picrust2#205]
Hi,everyon, I have a problem when running the following command:
 "place_seqs.py -s ITS.fasta -o placed_seqs.tre -p 10 -t sepp --ref_dir default_files/fungi/fungi_ITS --intermediate intermediate/place_seqs"

The screen shows:
The following expected file(s) could not be found:
default_files/fungi/fungi_ITS/fungi_ITS.raxml_info

Error - missing at least one of the four reference files in this specified directory: default_files/fungi/fungi_ITS

but I cann't find the file fungi_ITS.raxml_info.
what should I do?

**Comment by gavinmdouglas** [comment]
Hey @linfangxu,

Unfortunately the experimental fungi database can only be used with EPA-ng at the moment, not with SEPP. You can see here for a similar issue that was reported: https://github.com/picrust/picrust2/issues/180


Cheers,

Gavin
