### ISSUE TITLE
norm_functional_contrib- Error or misunderstaning

### ISSUE THREAD

**Issue by ragavishn** [picrust/picrust2#206]
I have run picrust2 pipeline for my smaples and I notice that the sum of 'norm_taxon_func_contrib' for a given function is not equal to 1. am I missing something here? Can you please clarify how this is being calculated? Our understanding is  

'norm_taxon_func_contrib'  = taxon_fn_abun / (sum of taxon_fn abun for the given fn)

Thank you.

**Comment by gavinmdouglas** [comment]
Hey @ragavishn,

Yes that should be what that column corresponds to for each sample and function. Would you mind sharing the table where you are noticing this problem?

If you don't mind sharing it, you can email it to me here: <img width="144" alt="gmail_screenshot" src="https://user-images.githubusercontent.com/12489683/133443620-f6b8f550-2a5f-44c5-a49e-008f0f526b54.png">


Thanks,

Gavin

**Comment by ragavishn** [comment]
Hi Gavin,

Thank you so much for taking your time to look into this.  Please find below the values I get when i sum the columns norm_func_contrib by function. I have emailed you my EC_metagenome_out/pred_metagenome_contrib.tsv file as well. Please let me know if I have missed something. Thank you.

function        norm_taxon_function_contrib
EC:1.1.1.1      1.0007563418716223
EC:1.1.1.100    5.874426127552522
EC:1.1.1.103    0.7118477678873769
EC:1.1.1.108    0.0001659706257272136
EC:1.1.1.11     0.8416089934812513
EC:1.1.1.122    0.00030970298766573297
EC:1.1.1.125    1.1444731716377892
EC:1.1.1.130    0.0184457626485505

**Comment by ragavishn** [comment]
I will try to upload the  original input file. Last column (norm_func_contrib) alone was not calculated past 100 rows. I am afraid its more of an pandas.groupby fn issue as it works for small datasets and your test data.  
Thank you again for your time and great work!

**Comment by gavinmdouglas** [comment]
My apologies @ragavishn, I just realized that I had totally forgotten about this... I thought it had been resolved, but it seems not be the case. I'm looking into it now and I believe this is a bug unfortunately, at least for larger tables.

**Comment by gavinmdouglas** [comment]
Thanks again - this is now fixed in the latest version (v2.5.0): https://github.com/picrust/picrust2/releases, which should soon be available through conda.
