### ISSUE TITLE
seq.qza and not fna

### ISSUE THREAD

**Issue by gafnialmog** [picrust/picrust2#208]
Hi,

I am intrested in testing the picrust2 toturial an my own data, this time i am **not** using the QIIME 2 plugin. 

To do so, I need a biom table and a seq.fna , However the "moving picture toturial" on qiime2 produces qza files noly. 

Can i modify this script to use qza?
place_seqs.py -s study_seqs.fna -o placed_seqs.tre -p 1 --intermediate placement_working

Or can I convert qza to fna?

What do I need to do to get the files needed?

*Maybe a diffrent possiblty is to use the inffered tree rooted or unrooted by converting the rooted-tree.qza to a tre format?

**Comment by gavinmdouglas** [comment]
Hey there,

.qza files are compressed zip files that contain the actual files. They are in this format to keep the provenance, but you can get the actual raw files by exporting them as shown here:  https://github.com/LangilleLab/microbiome_helper/wiki/Amplicon-SOP-v2-(qiime2-2020.8)#10-exporting-the-final-abundance-profile-and-sequence-files


Hopefully that helps!

Gavin
