### ISSUE TITLE
using PICRUSt2 pipeline, but it show  command not found: -r

### ISSUE THREAD

**Issue by Lin1111111111** [picrust/picrust2#210]
Hi, 
I've successfully built PICRUst2 and I have tested the pytest it is working.
When I try to run picrust2_pipeline.py  I get the following:

picrust2_pipeline.py -s aligned-dna-sequences.fasta  -i feature-table.biom -o picrust2_out_pipeline -p 20 \ 
-r default_files/prokaryotic/pro_ref/pro_ref  --in_traits COG,EC,KO,PFAM,TIGRFAM

but it shows:

picrust2_pipeline.py: error: unrecognized arguments:  
zsh: command not found: -r

Thank you for any assistance you can provide,

sincerely,

**Comment by Lin1111111111** [comment]
Hi @gavinmdouglas,
thank you very much for the prompt response, but it still can not work.
Before using this pipeline, I had used the Qiime2  pipelines, it had been succeeded.
But the final file is the pathway abundance table, and I want to know the  EC number of abundances.
So I tried the other pipeline, but it still can't work.
{ picrust2_pipeline.py -s aligned-dna-sequences.fasta -i otu_all_levers.txt -o picrust2_result -p 16 }
Stopping - no ASV ids overlap between input FASTA and sequence abundance table
I have used this ''biom convert -i BIOM -o BIOM.tsv --to-tsv'', and the biom file is from qiime2 pipeline.
Do you have any advice for me?

Thank you for any assistance you can provide,
sincerely,

**Comment by gavinmdouglas** [comment]
Hi @Lin1111111111,

The EC numbers are actually output by default with the QIIME 2 plugin actually. See: https://github.com/picrust/picrust2/wiki/q2-picrust2-Tutorial

The pathways are output as well, but so are the KOs and EC numbers.


Cheers,

Gavin

**Comment by Lin1111111111** [comment]
Hi @gavinmdouglas 
thank you very much for your advice.
I will try again.
Thank you sincerely.
