### ISSUE TITLE
Integrating the picrust2 into usegalaxy

### ISSUE THREAD

**Issue by EngyNasr** [picrust/picrust2#211]
Dear @gavinmdouglas 

I am currently trying to integrate picrust2 into useGalaxy.eu, however the following issues were faced while running the tool using its biconda package and the test data provided:

- in place_seqs, the --placement_tool when epa-ng is selected, I got the following errors: 
`Error running this command:
epa-ng --tree /home/nasr/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa placement_working/ref_seqs_hmmalign.fasta --query placement_working/study_seqs_hmmalign.fasta --chunk-size 5000 -T 1 -m /home/nasr/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w placement_working/epa_out --filter-acc-lwr 0.99 --filter-max 100
`
- in pathway_pipeline, the --no_regroup option when set to true, I got the following:
`Stopping, because no pathways were identified. This can especially happen when either a test input file with few gene families is input or when gene family regrouping is not done properly.
`
- shuffle prediction, the tool doesn't output the files in the output directory specified in the --outdir argument

Any suggestions to solve these issues.

Thanks a lot,
Engy

**Comment by gavinmdouglas** [comment]
Hi @EngyNasr,

It's hard to troubleshoot these issues without more information. Do you know if whether running `pytest` (to run the test scripts) works in the environment you're working in?


Thanks,

Gavin

**Comment by EngyNasr** [comment]
Hi @gavinmdouglas 

Thanks a lot for reply, sorry for not explaining enough.

I am currently trying to run picrust2 through command line after installing it using its bioconda package. 

For the first issue, of epa-ng, after activating picrust conda package, I used the test_data provided [here](https://github.com/picrust/picrust2/tree/master/tests/test_data/place_seqs)  to run place_seqs.py command, and I got the following error in the image below: 

![Screenshot from 2021-11-04 15-14-10](https://user-images.githubusercontent.com/7595309/140330480-e9d395b0-0d15-445a-ba35-b4ddc22b9473.png)

Then I tried running again with the argument --redo, but the argument does not exist in place_seqs.py command 

If I can solve it here, it will be also solved in my wrapper which do the same steps internally

**Comment by gavinmdouglas** [comment]
Hey @EngyNasr,

No worries at all!

Sorry for the confusion, the ```--redo``` option that it's talking about is actually only for epa-ng directly and isn't a picrust2 option. The confusion arises because picrust2 is wrapping epa-ng and that's the error that's being output when it's trying to run it through a system call. You would have to remove that folder manually before re-running the ```place_seqs.py``` command.

Also, to better help you troubleshoot you can download the PICRUSt2 repo from this github repository and then run ```pytest``` in the main directory. This will run all of the tests for the tool and will give clearer insight into what isn't working.


Cheers,

Gavin

**Comment by EngyNasr** [comment]
Thank you so much for your reply :) 

I removed it and still have an error with the command as follows
![Screenshot from 2021-11-04 15-53-16](https://user-images.githubusercontent.com/7595309/140337046-7c90b69d-2b8d-4680-a624-5fe7e434a601.png)

I will download picrust2 repo for more troubleshooting 

Regarding the second problem with pathway_pipeline, the --no_regroup option, I guess that's only because of the test_data.

And for the last issue, shuffle prediction, supposedly there is an argument (-o) where you determine where you would like the output to be stored, however the resulted output are saved in main directory of the input file instead. That is not a big issue I know :) 

Thanks again for helping.

If you can still guide me with the epa-ng, I would be grateful

**Comment by gavinmdouglas** [comment]
Thanks for reporting these problems. How much memory do you have on your system? The EPA-NG step needs to read in the reference tree even if only a small number of query sequences are provided, which means that memory limits could be behind this problem.


Cheers,

Gavin
