### ISSUE TITLE
pathway_pipeline.py killed

### ISSUE THREAD

**Issue by MartinBioinf** [picrust/picrust2#212]
Hello, I have trouble running pathway_pipeline.py, it always get killed probably due to large dataset consisted of 2M reads. Should I filter out rare ASV? Is it possible to do with some Picrust2 command or should I do it in Mothur where I processed raw reads from seqenation? Does the filtering influence output in some way?  Thank you for your answer.

**Comment by gavinmdouglas** [comment]
Hi there,

You can use the ```--min_reads``` and ```--min_samples``` options to filter out rare ASVs (which will be combined into a single "RARE" category). You could also do the filtering beforehand, which would make the whole pipeline run faster.

Yes the filtering will affect the output, as likely the placement of ASVs will be different and, depending on the total percent of rare ASVs, they could represent a decent proportion of the overall functional potential and so removing them could affect the overall profiles.


Cheers,

Gavin
