### ISSUE TITLE
Databases update tutorial

### ISSUE THREAD

**Issue by Cybernewbye** [picrust/picrust2#213]
Dear Gavin
I wonder if a tutorial on how to update default_files (e.g. Ko descriptions, reactions and even 16S database) is available.

Thank you

**Comment by gavinmdouglas** [comment]
Hey there,

There isn't a tutorial on how to do that sorry! You can see this discussion thread how tips on how this could be done though: https://groups.google.com/g/picrust-users/c/-Gd0FbkbZPo/m/DHtAlUDpAwAJ?utm_medium=email&utm_source=footer&pli=1


Cheers,

Gavin
