### ISSUE TITLE
q2 picrust2 the final step

### ISSUE THREAD

**Issue by Lin1111111111** [picrust/picrust2#214]
Hi,
I want to know how to get the EC numbers to MetaCyc reactions.
I only have the EC numbers but I want to add functional descriptions.
My file is "ec_metagenome.qza".

Thank you for any assistance you can provide,

sincerely,

**Comment by gavinmdouglas** [comment]
Hey @Lin1111111111,

Do you want to get the MetaCyc reactions or pathways? The pathways should be the final file output. There isn't a way to do get the reactions with the QIIME 2 version, but if you run the pathway_pipeline.py script on the EC number table after you export it to be a basic tab-delimited file and if you specify a folder for intermediate files to be saved, then the regrouped EC numbers to reaction table will be present.


Cheers,

Gavin

**Comment by Lin1111111111** [comment]
Hi @gavinmdouglas,
Thank your advice.
So I should run done this 
 "qiime picrust2 full-pipeline \
   --i-table mammal_biom.qza \
   --i-seq mammal_seqs.qza \
   --output-dir q2-picrust2_output \
   --p-placement-tool sepp \
   --p-threads 1 \
   --p-hsp-method pic \
   --p-max-nsti 2 \
   --verbose"
and the next step is "picrust2_pipeline.py -s dna-sequences.fasta  -i feature-table.biom -o picrust2_out_pipeline -p 20 \
    -r default_files/prokaryotic/pro_ref/pro_ref --in_traits COG,EC,KO,PFAM,TIGRFAM" right?


Thank you sincerely.

**Comment by gavinmdouglas** [comment]
Hi @Lin1111111111,

No that first command is how you run the QIIME 2 plugin for PICRUSt2 while the second one is how you run PICRUSt2 on its own (outside of QIIME 2). So basically you would do one or the other, but not both.

**Comment by Lin1111111111** [comment]
Hi @gavinmdouglas
thank you very much for your advice.
May I ask which "pathway_pipeline.py" I should use after q2 picrust2 that could help me get the regrouped EC numbers?


Thank you sincerely.

**Comment by gavinmdouglas** [comment]
Hey @Lin1111111111,

I don't think I follow your question, sorry. I would recommend you take a look at the tutorial and start at the top: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.4.1). Note that this tutorial is just for the standard way of running it, which is outside of QIIME 2.

Hopefully that clarifies your questions on how to run the tool!


Gavin

**Comment by Lin1111111111** [comment]
Hi @gavinmdouglas,
thank you very much for your response.
I will try the PICRUSt2-Tutorial-(v2.4.1).


Thank you sincerely.😄

Lin

**Comment by MdUmar-tech** [comment]
How did u get this file 
mammal_biom.qza
from raw data , i used to get .biom file but i didnt find biom.qza file any where, kindly help in this regards
