### ISSUE TITLE
Collapsing Metacyc pathways in the pathway abundance file

### ISSUE THREAD

**Issue by Georgie-ru** [picrust/picrust2#216]
Hi Gavin

How do I collapse the pathways from PICRUSt2 to different levels (i.e. levels 1, 2 and 3) like PICRUSt 1 has options for? Thanks

Georgina

**Comment by gavinmdouglas** [comment]
Hey Georgina,

You can't do that by default anymore actually. You can find more details and a workaround for KEGG pathways here: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-categorize_by_functionpy-like-in-picrust1


Cheers,

Gavin

**Comment by Georgie-ru** [comment]
Thanks Gavin

**Comment by MonicaSteffi** [comment]
> 

Hi,
I have collapsed KO terms into different levels, thanks to the script. Is there any way to do the same on the pathway output?
I got KO mapping files from
https://www.dropbox.com/s/a5o4li0irsqupt3/picrust1_KO_BRITE_map.tsv?dl=1. Is there any mapping files for pathways like 1CMET2-PWY too?

**Comment by gavinmdouglas** [comment]
KOs are not linked to the MetaCyc pathways directly. But you could do something like collapsing to superpathways, which someone was recently discussing here: https://groups.google.com/g/picrust-users/c/Ve0NmGf37Vw/m/s2L4OrHGAAAJ?utm_medium=email&utm_source=footer&pli=1

I don't have any scripts handy to do that though, but it would be very similar to the KO BRITE collapsing.


Cheers,

Gavin
