### ISSUE TITLE
Does Picrust2 still need Qiime2-2021.2 

### ISSUE THREAD

**Issue by ARW-UBT** [picrust/picrust2#218]
Hi, 
can Picrust2 be installed in more recent versions of Qiime2? The Qiime2 library entry still recommends q2-2021.2 as the basis for it.

Best,

**Comment by gavinmdouglas** [comment]
Hey @ARW-UBT,

Unfortunately PICRUSt2 doesn't work with the latest version of QIIME 2 due to some dependency incompatibilities. This is something I keep meaning to address and hopefully will get to soon.


Sorry for the inconvenience,

Gavin
