### ISSUE TITLE
TypeError: attrib() got an unexpected keyword argument 'convert'

### ISSUE THREAD

**Issue by Johnny-zuo** [picrust/picrust2#219]
When I install the picrust2 from source and run the pytest, I met TypeError: attrib() got an unexpected keyword argument 'convert'.
I tried to change the version of attrs from 21.2.0 to 19.1.0 (or 18.3.0), it could run pytest, and showed another problem. The result showed 2 failed, 47 passed in 89.54 seconds. I carfully checked the information, and found two errors: FileNotFoundError: [Errno 2] No such file or directory: 'place_seqs.py' : 'place_seqs.py'; FileNotFoundError: [Errno 2] No such file or directory:  'picrust2_pipeline.py': 'picrust2_pipeline.py'. 
How can I solve this problem?

**Comment by gavinmdouglas** [comment]
Hey @Johnny-zuo,

I haven't seen that problem before - how did you install the tool? I would suggest you try re-installing it in a new conda environment and see if that solves the problem.


Cheers,

Gavin

**Comment by Johnny-zuo** [comment]
> Hey @Johnny-zuo,
> 
> I haven't seen that problem before - how did you install the tool? I would suggest you try re-installing it in a new conda environment and see if that solves the problem.
> 
> Cheers,
> 
> Gavin

**Comment by Johnny-zuo** [comment]
Thanks @gavinmdouglas 
I re-installed it in a new conda environment and it did work!
Thank you for kind help!
