### ISSUE TITLE
No data from run_minpath.py for KO results

### ISSUE THREAD

**Issue by itiago** [picrust/picrust2#22]
Hi
I wanted to run the minpath for KO results obtained from 
hsp.py -i KO -t kiwis.tre -o KO_kiwis_predicted -p 6 --chunk_size 300

and I run the command bellow, but the out put gave a txt with nothing besides the headline, despite KO_kiwis_predicted.tsv had 14.8MB:

run_minpath.py -i /home/igor/Desktop/KIWIS/Metagenome_prediction_KO/pred_metagenome_strat.tsv \
>                -m /home/igor/picrust2/MinPath/ec2metacyc_picrust_prokaryotic.txt \
>                -o kiwis_KO \
>                --intermediate IntermediateFiles_wikis_KO \
>                -p 4

**Comment by gavinmdouglas** [comment]
The problem you're running into is that the input mapping file ```/home/igor/picrust2/MinPath/ec2metacyc_picrust_prokaryotic.txt``` maps E. C. numbers (not KOs) to MetaCyc pathways. This is the only mapping file I have packaged with PICRUSt2 currently.

Gavin
