### ISSUE TITLE
Error: No objects to concatenate

### ISSUE THREAD

**Issue by Biancabrown** [picrust/picrust2#230]
Hello,

I've been using picrust2 (standalone version) for a while now, and I recently received the error message below. It doesn't seem like there is anything wrong with my biom and representative sequence files because I ran picrust2 using another set of files, and it ran fine. 

The issue is that I'm unsure what the error means. Does it mean that picrust2 cannot assign a pathway to my sequences, or is there something wrong with the actual files? 

 Thanks

Standard error of the above failed command:
Traceback (most recent call last):
  File "miniconda3/envs/picrust2/bin/pathway_pipeline.py", line 272, in <module>
    main()
  File "miniconda3/envs/picrust2/bin/pathway_pipeline.py", line 173, in main
    unstrat_abun_per_seq = pathway_pipeline(
  File "/Users/bbrown/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/pathway_pipeline.py", line 351, in pathway_pipeline
    in_metagenome = regroup_func_ids(in_metagenome, in_format,
  File "miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/pathway_pipeline.py", line 1187, in regroup_func_ids
    raw_new_ids_combined = pd.concat(raw_new_ids_dfs, sort=False)
  File "/Users/bbrown/miniconda3/envs/picrust2/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "miniconda3/envs/picrust2/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 294, in concat
    op = _Concatenator(
  File "miniconda3/envs/picrust2/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 351, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by gavinmdouglas** [comment]
Hi @Biancabrown,

I'm not sure why that error is occurring. What exact command are you using and what version of PICRUSt2? Can you send me the header of the input FASTA file?


Thanks,

Gavin

**Comment by Biancabrown** [comment]
Hi Gavin, 

See below. 

Thanks

version:  2.4.2

code:
picrust2_pipeline.py -s repseq.fna -i late.biom  -o picrust_late_out -p 1

header:
>TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGTCATGCAAGTCTGAAGTGAAAGCCCGGGGCTCACCCCCGGGACTGCTTTGGAAACTGTAAGACTAGAGTGCAGGAGAGGTAAGTGGAATTCCTAG
TACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGACGGTCATGCAAGTCTGAAGTGAAAGCCCGGGGCTCACCCCCGGGACTGCTTTGGAAACTGTAAGACTAGAGTGCAGGAGAGGTAAGTGGAATTCCTAG
>TACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAGAGGGCGAGTAGGCGGATCTGCAAGTCAGATGTGAAAGCCCGGGGCTCAACCCCGGGACTGCTTTGGAAACTGTTAAACTAGAGTGCAGGAGAGGTAAGCGGAATTCCTAG
TACGTAGGTGGCAAGCGTTGTCCGGATTTACTGGGTGTAGAGGGCGAGTAGGCGGATCTGCAAGTCAGATGTGAAAGCCCGGGGCTCAACCCCGGGACTGCTTTGGAAACTGTTAAACTAGAGTGCAGGAGAGGTAAGCGGAATTCCTAG
>TACGTAGGTTGCAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGCGTGTAGGCGGAGATGCAAGTTGGGAGTGAAATCCATGGGCTCAACCCATGAACTGCTTCCAAAACTGTATCCCTTGAGTATCGGAGAGGCAAGCGGAATTCCTAG
TACGTAGGTTGCAAGCGTTGTCCGGATTTACTGGGTGTAAAGGGCGTGTAGGCGGAGATGCAAGTTGGGAGTGAAATCCATGGGCTCAACCCATGAACTGCTTCCAAAACTGTATCCCTTGAGTATCGGAGAGGCAAGCGGAATTCCTAG

**Comment by gavinmdouglas** [comment]
Are you missing ">" in the headerlines? That would be an issue and otherwise you could try simplifying the fasta headers as perhaps the long sequence ids is causing the problem.


Cheers,

Gavin

**Comment by Biancabrown** [comment]
Hi Gavin, 

Thanks for the suggestions!

It's neither of those things. I wasn't missing a ">", and changing the headers (and the biom file so they matched) resulted in the same error. Moreover, I'm **able** to run picrust2 using other subsets of the data. Something about the ASVs that make up this specific subset causes this error. 

Is it possible that PICRUSt2 cannot assign these ASVs pathways? Unclear if that's in the realm of possibilities.

-Bianca

**Comment by gavinmdouglas** [comment]
Not being able to assign any pathways shouldn't be a problem. If you don't mind sharing the input files with me I can help troubleshoot better!


You can email them to me at <img width="144" alt="gmail_screenshot" src="https://user-images.githubusercontent.com/12489683/150358524-e53e6c94-381e-44f0-8049-3726242342eb.png">

**Comment by gavinmdouglas** [comment]
Closed due to inactivity - please let me know if you're still troubleshooting this though
