### ISSUE TITLE
How to add higher level description of pathways? 

### ISSUE THREAD

**Issue by yangzw6** [picrust/picrust2#231]
Hello,
     After add the description, I find only the lowest level of function annotation could be shown. I remember the picrust1 can add the higher level, could it still work in the picrust2 and how to do this work?

**Comment by gavinmdouglas** [comment]
Hi @yangzw6,

No there isn't a way to do that with PICRUSt2 as the focus is on MetaCyc pathways rather than KEGG pathways as in PICRUSt1.


Cheers,

Gavin
