### ISSUE TITLE
ASVs poorly aligned?

### ISSUE THREAD

**Issue by marwa38** [picrust/picrust2#233]
Hello ,, isn't that too many ASVs to lose?
My ASVs was aligned against SILVA using assignTaxonomy() & addSpecies() in R and I used dada2 for denoising. 

```
picrust2_pipeline.py -s ASVs.fa -i ASVs_counts.tsv -o picrust2_out_pipeli ne -p 19

Warning - 363 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences).  These input sequences will not be placed and will be excluded from downstream st  eps.
```
![image](https://user-images.githubusercontent.com/68851733/151223870-28cbb79b-7e2f-4a16-96e4-6cd347c9ac6f.png)

```
**55 of 2474 ASVs were above the max NSTI cut-off of 2.0 and were removed.

55 of 2474 ASVs were above the max NSTI cut-off of 2.0 and were removed.
**
```

Thanks; your advice/comment is much appreciated.

**Comment by gavinmdouglas** [comment]
Hi there,

What is the taxonomy of some of the ASVs that can't be aligned? What do they match if you run BLASTn online?


Cheers,

Gavin
