### ISSUE TITLE
Interpreting shuffled predictions

### ISSUE THREAD

**Issue by msmcfarlin** [picrust/picrust2#234]
Hello,

I just wanted to check on how I should be using my shuffled predictions.

I am using the corncob package for differential abundance testing of pathways between 4 groups. From the PICRUST2 predictions I found a total of 50 pathways were significantly different between some or all of the 4 groups. 

I then ran the same differential abundance testing on the 5 shuffled pathway files, the path_abun_unstrat_rep files. From these files, I found that a few of the significantly different pathways between groups were shared with the original PICRUST2 predictions.

The rep1 file shared 0 significant pathways between groups out of the 50 pathways with the original output.
The rep2 file shared 5/50 pathways with the original output.
The rep3 file shared 1/50 pathways with the original output.
The rep4 file shared 3/50 pathways with the original output.
The rep5 file shared 1/50 pathways with the original output.

All of the 10 shared significant pathways were unique, i.e. none of them were repeated across the 5 different shuffled predictions.

Is this how I should be using the shuffled files? And how would you suggest I interpret this?

Thank you so much for the amazing program and your assistance!

**Comment by gavinmdouglas** [comment]
The main question the shuffled predictions can help you answer is whether there is a higher number of significant pathways in the unshuffled data compared with the shuffled data. If there are similar numbers then I would have much less confidence in the results. You could perform a statistical test along on these lines if you performed enough replicates, but I intended it mainly as a sanity check. So how many pathways are significant for each replicate?

I think looking at which pathways are significant is another good sanity check, to ensure that certain pathways just aren't always significant, but I find the simpler metric of just how many pathways are significant to be simpler to interpret.

**Comment by msmcfarlin** [comment]
Hello,

Thank you for the response! 

The number of significant pathways from the replicates are...
-62 from rep1
-30 from rep2
-79 from rep3
-28 from rep4
-29 from rep5

Would it be useful to find the number of significant pathways per group for each replicate? Then use a goodness of fit test to check if the proportion of significant pathways per group is the same as the original data? 

I tried running this, and 3 of the 5 replicates have a different proportions of significant pathways per group compared two the original data. In 2 of the 5 replicates, the proportion of significant pathways per group do not differ. Any thoughts on how to interpret this?

Thank you so much for the assistance!

**Comment by gavinmdouglas** [comment]
It seems like the overall number of significant pathways is very similar to what you would expect under the null hypothesis (of the pathways just being significant due to random differences in pathway assignment to ASVs). So unless the particular pathways that are significant happen to agree with an a priori expectation then I would not have much confidence in those significant hits.


Cheers,

Gavin

**Comment by msmcfarlin** [comment]
Ok, that makes sense.

Would you recommend I instead try differential abundance analysis with the KO_output or EC_output rather than the pathways as you said you typically do in #144?

Thanks again!

**Comment by gavinmdouglas** [comment]
You could try the analysis with those tables as well, but I would recommend comparing with the shuffled tables again if that's possible as a sanity check.

**Comment by msmcfarlin** [comment]
Ok, I will try the KO_output files followed by the shuffled table analysis.

You mentioned earlier... 

> ...unless the particular pathways that are significant happen to agree with an a priori expectation then I would not have much confidence in those significant hits.

I have found differentially abundant taxa between groups. If I check if those taxa are contributing to significant pathways, like #146, would it make sense to keep those significant pathways and discard any that don't match significant taxa?

**Comment by gavinmdouglas** [comment]
That's not the expectation I meant - I meant if there were specific functions you were expecting to see differentially abundant based on prior literature or independent data. I think it would just be somewhat circular if you checked to see what the differentially abundant ASVs were predicted to encode, as those functions would also be more likely to be differentially abundant.

**Comment by msmcfarlin** [comment]
Oh ok, that makes sense. Thanks for the correction!

Do you have any suggestions on how I might improve prediction? My samples are bird fecal samples which are likely poorly represented in the reference genomes. Would there be any value in rerunning with some parameters changed like sequence placement with SEPP instead of EPA-NG?

**Comment by gavinmdouglas** [comment]
I don't think SEPP vs EPA-ng will make any meaningful difference (at least it hasn't in any tests I ran). I don't have any specific recommendations to help you improve the predictions unfortunately, but I think how you're using the shuffled predictions as a control is great!
