### ISSUE TITLE
Interpretation of metacyc superpathways

### ISSUE THREAD

**Issue by andrewd789** [picrust/picrust2#235]
Hi, I have a question about interpreting the pathways output from picrust2. 

I can match up the pathway identifiers in the `path_abun_unstrat.tsv.gz` output file with descriptions from `picrust2/default_files/description_mapfiles/metacyc_pathways_info.txt.gz`. I am unsure how to interpret certain "superpathways" in this output. 

For example, one pathway in the data is:
`GLYCOLYSIS-TCA-GLYOX-BYPASS`, which is the superpathway of glycolysis, pyruvate dehydrogenase, TCA, and glyoxylate bypass. 
Also in the data are the following:
`GLYCOLYSIS` - glyoxlate cycle
`TCA` - TCA cycle 1 (prokaryotic)  
`GLYOXYLATE-BYPASS` - glyoxylate cycle
`TCA-GLYOX-BYPASS` - superpathway of glyoxylate bypass and TCA
etc.

Each of these is a separate row of values in the results. The latter four pathways appear to be sub-pathways of the first (`GLYCOLYSIS-TCA-GLYOX-BYPASS`). However, the sub-pathway values don't sum to the value of the superpathway, leaving me puzzled about what they mean. 

How do these pathways relate to each other, and how should their respective values be interpreted? Why don't the sub-pathway values sum to the superpathway values?

Thanks!

Andrew.

**Comment by gavinmdouglas** [comment]
Hey Andrew,

The superpathway is actually treated as an independent pathway in our pathway reconstruction approach. So the abundance of this pathway is not just taken to be the sum of those other pathways. The abundance instead will be based on the harmonic mean abundance of the key reactions in the superpathway. 

Hopefully that helps!


Cheers,

Gavin

**Comment by andrewd789** [comment]
Hi Gavin,

Aha, thanks, that makes sense. Thanks for the quick answer! 

Andrew.

**Comment by jazberna1** [comment]
Hello Andrew,

Possibly also related to payhways depencdeny. I was wondering if picrust2 takes somehow into account cases where a given metacyc pathway has "variants" pathways asscociated to it. 

Many thanks
Jorge
