### ISSUE TITLE
 KO_pred_metagenome_unstrat into KEGG pathways (parent or level 2)?

### ISSUE THREAD

**Issue by marwa38** [picrust/picrust2#236]
Hi @gavinmdouglas 

In response to your kind reply in #144 `1. I personally mainly analyze the KO outputs, because I have less confidence in pathway predictions (you can see them each validated in the PICRUSt2 paper). However, a lot of researchers are more interested in pathway data because there are fewer features and they have clearer interpretations.` 

I was wondering if there is a possibility to convert KO_pred_metagenome_unstrat into KEGG pathways (parent or level 2) to make it more neat and less features? in a similar way as in this tutorial? https://github.com/picrust/picrust2/wiki/Add-descriptions so that I can run Welch test and correct the p-value in STAMP and then visualising it.

**Comment by gavinmdouglas** [comment]
Hi @marwa38,

Yes you can see how to do that using code outside of PICRUSt2 in the response to this FAQ: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-categorize_by_functionpy-like-in-picrust1


Cheers,

Gavin

**Comment by marwa38** [comment]
Thanks very much, @gavinmdouglas for your support 

So will I ran `categorize_by_function.py` on `KEGG_pathways_out` which is the output from 
`pathway_pipeline.py -i KO_metagenome_out/pred_metagenome_strat.tsv -o KEGG_pathways_out --no_regroup --map picrust2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv`

I am getting an error: `categorize_by_function.py command not found `
I am working in picrust2 environment and the codes I tried are 
`categorize_by_function.py`
also
`categorize_by_function.py KEGG_pathways_out/KEGG_path_abun_unstrat.tsv`

Regarding the R script; I can't find orig_ko_L3
![image](https://user-images.githubusercontent.com/68851733/152336313-83187ad0-935c-4b19-9087-bf6d82bcdf1b.png)
