### ISSUE TITLE
rounding the outputs before using STAMP?

### ISSUE THREAD

**Issue by marwa38** [picrust/picrust2#237]
Do I need to `round() ` the outputs I got from picrust2 for example pathway_unstart.tsv or KEGG_L3.tsv for STAMP?
I am not getting errors in STAMP but need to ask as I found this info here https://groups.google.com/g/picrust-users/c/otuOAFpu1s8/m/aPk6LbIvAwAJ
Many Thanks

**Comment by gavinmdouglas** [comment]
Hi @marwa38,

No it's not necessary to round the data prior to STAMP, as STAMP plots the relative abundance anyway (i.e., converts the data to percentages per sample).


Cheers,

Gavin
