### ISSUE TITLE
Minpath version

### ISSUE THREAD

**Issue by Deborahgn** [picrust/picrust2#241]
Hi!

I hope you're doing okay!

This is more of a question than a real issue. I was going through the picrust update and I saw you were still using the MinPath 1.2 version. I was wondering why you weren't using a newest version like 1.6 of MinPath? Is there some incompatibility with the newest version? 

Thanks in advance for your answer, 
Have a great day, 

Deb

**Comment by gavinmdouglas** [comment]
Hey Deb,

The only reason for that is that a forked version of MinPath 1.2 was edited by the HUMAnN team. We wanted to make sure that our pathway inference approach worked the same as their's, so we used the identical MinPath script.


All the best,

Gavin
