### ISSUE TITLE
KEGG_modules_to_ko map file incomplete

### ISSUE THREAD

**Issue by carlmed00** [picrust/picrust2#244]
It seems like the KEGG modules map file is incomplete. I try to run mapping using the file and found out that modules like Nitrification (M00528) and Denitrification (M00529) are not present in the file.

In addition, I tried to go check KO present in pathways and compare them to the module mapping file. For the lile of ko00910 in pathway mapping, it includes K01916 and K01914. Upon checking KEGG, ko00910 (Nitrogen Metabolism Pathway) does not include those two KOs. I am a bit confused now.

**Comment by gavinmdouglas** [comment]
Hey @carlmed00,

I can see why you're confused! The KEGG files packaged with PICRUSt2 are from the last open-source version, which is quite out-dated now. You could download the latest version of the files from the KEGG api (if they are used for academic work), but I cannot distribute them.


Cheers,

Gavin
