### ISSUE TITLE
Understanding pathway_pipeline.py 

### ISSUE THREAD

**Issue by carlmed00** [picrust/picrust2#245]
tried running pathway_pipeline.py using the KO_to_pathway mapping file included in latest picrust2 and an updated one using KEGG API.

Is there a criteria before a pathway is selected? (certain percentage of KO from the mapping file should be present in the table?)

For example, the mapping file from the latest picrust release contains 45KOs under ko00562 while the updated one from KEGG API, I was able to see 77 KOs under ko00562. In my table, 15KOs were matched in the 45KOs from picrust release and 16 from KEGG API map.

The generated pathway table contained ko00562 if I use the picrust2 release mapping but didn't contain in the pathway table if I use the mapping using KEGG API one.

**Comment by gavinmdouglas** [comment]
Hi there,

MinPath is used to call pathways as present - so it depends how many pathways a KO is involved with essentially, to determine how informative it is for a specific pathway. It definitely makes sense to see differences like that due to the differing KO to pathway mappings.


Cheers,

Gavin
