### ISSUE TITLE
How are KEGG module abundances and coverage calculated?

### ISSUE THREAD

**Issue by yakshiUPR** [picrust/picrust2#248]
Hi Gavin, 

Thanks again for such an awesome program. I have been using it for a while now. I recently started to look into KEGG modules, and figured out that I can generate a module table from the KO table generated by Picrust. I went ahead and produced the module abundances and coverage tables, however, I don't understand how Picrust is generating either of those tables. For instance, a module is composed of several KOs, some of them are essential, some of them have alternatives and some are not-essential. Are these KOs classifications taken into account when calculating the abundance and coverage? I know there are other programs like microbeannotator that calculate completeness of modules taking into consideration these classifications, but they do not compute the module abundance. 

Look forward to hear from you,
Yakshi

**Comment by gavinmdouglas** [comment]
Hey Yakshi,

No differences like this are not taken into account by the approach in PICRUSt2, at least for KEGG pathways and modules. They are taken into account for the MetaCyc pathways, but for the KEGG data they are treated as "bags of genes", all contributing equally. If you provide a structured mapfile of pathways to gene ids though it would automatically use that information, but at the time of producing PICRUSt2 I did not have access to such a file for the open-source KEGG files. The pathway approach is the same as used by HUMAnN2 (and I believe in the newer HUMAnN3 as well, but I'm not sure what all has changed). So I would refer to you to their documentation on how structured pathway mapfiles are denoted (and you can see the MetaCyc pathway to reaction mapfile in the PICRUSt2 repo for an example for how this is annotated).

See also: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#why-does-the-metacyc-pathway-mapfile-to-reactions-look-so-complicated


Cheers,

Gavin
