### ISSUE TITLE
Error in Installing Picrust2

### ISSUE THREAD

**Issue by carlmed00** [picrust/picrust2#250]
Is Picrust 2 supposed to be installed in root folder? I am currently using Picrust2 in WSL Ubuntu20.04 which automatically enters terminal in root.

However, when I try installing Picrust2 in WSL Ubuntu18.04, I get an error at the pip install line:

> (picrust2) carlmed@CarlLaptop:~/picrust2-2.4.2$ pip install --editable .
> Obtaining file:///home/carlmed/picrust2-2.4.2
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: numpy in /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages (from PICRUSt2==2.4.2) (1.22.3)
> Requirement already satisfied: h5py in /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages (from PICRUSt2==2.4.2) (3.6.0)
> Requirement already satisfied: joblib in /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages (from PICRUSt2==2.4.2) (1.1.0)
> Requirement already satisfied: biom-format in /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages (from PICRUSt2==2.4.2) (2.1.12)
> Requirement already satisfied: scipy>=1.3.1 in /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages (from biom-format->PICRUSt2==2.4.2) (1.8.0)
> Collecting cython
>   Downloading Cython-0.29.28-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 7.1 MB/s eta 0:00:00
> Requirement already satisfied: pandas>=0.20.0 in /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages (from biom-format->PICRUSt2==2.4.2) (1.4.2)
> Requirement already satisfied: click in /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages (from biom-format->PICRUSt2==2.4.2) (8.1.2)
> Requirement already satisfied: python-dateutil>=2.8.1 in /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages (from pandas>=0.20.0->biom-format->PICRUSt2==2.4.2) (2.8.2)
> Requirement already satisfied: pytz>=2020.1 in /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages (from pandas>=0.20.0->biom-format->PICRUSt2==2.4.2) (2022.1)
> Requirement already satisfied: six>=1.5 in /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas>=0.20.0->biom-format->PICRUSt2==2.4.2) (1.16.0)
> Installing collected packages: cython, PICRUSt2
>   Running setup.py develop for PICRUSt2
>     error: subprocess-exited-with-error
> 
>     × python setup.py develop did not run successfully.
>     │ exit code: 1
>     ╰─> [7 lines of output]
>         running develop
>         running egg_info
>         /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
>           warnings.warn(
>         /home/carlmed/anaconda3/envs/picrust2/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>           warnings.warn(
>         error: [Errno 13] Permission denied
>         [end of output]
> 
>     note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by gavinmdouglas** [comment]
Hi @carlmed00,

No it should not be installed in a root directory (and instead should be installed in a conda environment, which is a local environment). Are you currently in a conda environment? You can also try adding the `--user` tag to the pip command, as mentioned here: https://stackoverflow.com/questions/25816674/pip-is-not-able-to-install-packages-correctly-permission-denied-error
