### ISSUE TITLE
KEGG description for KO ids

### ISSUE THREAD

**Issue by Lor-AM** [picrust/picrust2#251]
I have run the picrust2 pipeline for both EC nos and KO nos. I completed the pathway prediction using pathway_pipeline.py -i pred_metagenome_unstrat.tsv.gz -o KEGG_pathways_out --no_regroup --map /home/******/picrust2-2.4.2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv . I wanted to add description to the KO nos with reference to KEGG. When I check picrust2/default_files/pathway_mapfiles/ there are two files one "KEGG_pathways_to_KO.tsv"
and the other "KEGG_modules_to_KO.tsv" . However there is no description given for each KO in either files. Do I need to create a file? Could you please assist me in this regard

**Comment by gavinmdouglas** [comment]
Hey @Lor-AM,

You would need to run `add_descriptions.py` with the `--custom_map_table` option pointing to the appropriate mapfiles in this directory: `https://github.com/picrust/picrust2/tree/master/picrust2/default_files/description_mapfiles`.

Hopefully that helps!


Cheers,

Gavin
