### ISSUE TITLE
interpretation of superpathway and pathways

### ISSUE THREAD

**Issue by jazberna1** [picrust/picrust2#254]
Hello PICRUSt team,

This is not and issue. I was wondering if you could please help me to interpret the following PICRUSt counts of MetaCyC pathways.
I have counts for the superpathway (PWY-6830) and two of its pathways (METH-ACETATE-PWY and METHANOGENESIS-PWY).
In this case the counts of the superpathway are lower compared to the pathways.

May I assume that the superpathway contribution accounts for reactions not present in the other two pathways?

```
code	description	counts
METH-ACETATE-PWY	methanogenesis from acetate	6.621408046
METHANOGENESIS-PWY	methanogenesis from H2 and CO2	1.861943248
PWY-6830	superpathway of methanogenesis	0.061400222
```

Thanks so much 
Jorge

**Comment by gavinmdouglas** [comment]
Hi Jorge,

In the default pathway to reaction file this is what PWY-6830 contains:

```
PWY-6830         (  RXN-8102 RXN-8103  +  RXN-8100 RXN-8101  +  RXN-8098 RXN-8099  +  FORMYLMETHANOFURAN-DEHYDROGENASE-RXN 2.3.1.101-RXN 3.5.4.27-RXN H2-METHYLENE-THMPT-DEHYDRO-RXN METHELENE-THMPT-OXI-RXN 2.1.1.86-RXN  +  ACETATEKIN-RXN PHOSACETYLTRANS-RXN ACETYLSYNCLTH-RXN ( 1.2.7.4-RXN , ( RXN-12908 -MTRMBARK-RXN ) )  +  RXN-8095 RXN-8096  )  METHYL-COM-HTP-RXN
```

Whereas the other two are:

```
METH-ACETATE-PWY         ACETATEKIN-RXN PHOSACETYLTRANS-RXN ACETYLSYNCLTH-RXN ( 1.2.7.4-RXN , ( RXN-12908 -MTRMBARK-RXN ) )

METHANOGENESIS-PWY       FORMYLMETHANOFURAN-DEHYDROGENASE-RXN 2.3.1.101-RXN 3.5.4.27-RXN H2-METHYLENE-THMPT-DEHYDRO-RXN METHELENE-THMPT-OXI-RXN 2.1.1.86-RXN
```

So you can see that both of the latter terms are nested within the PWY-6830 definition, but that there are other reactions that must be lowering the abundance value.



Cheers,

Gavin
