### ISSUE TITLE
q2-picrust2 do not produce output file but no error reported

### ISSUE THREAD

**Issue by wangyd666** [picrust/picrust2#255]
Hi, everyone
I used the following command to produce my prediction results. However, the output file can not be produced no matter I changed the output parameter. How can I solve this ? By the way , I found the output results printed on the screen when I changed the --quiet to --verbose.
qiime picrust2 full-pipeline \
>    --i-table qiime2-file/table-no-mitochondria-no-chloroplast-F.qza \
>    --i-seq qiime2-file/sequences-with-phyla-no-mitochondria-no-chloroplast.qza \
>    --output-dir q2-picrust2_output \
>    --p-placement-tool sepp \
>    --p-threads 1 \
>    --p-hsp-method pic \
>    --p-max-nsti 2 \
>    --quiet
output printed on the screen  
>>>pathway-570[571; TYRFUMCAT-PWY] fam=5 unique-fam=3
pathway-571[572; UBISYN-PWY] fam=10
>>>pathway-571[572; UBISYN-PWY] fam=10 unique-fam=0
pathway-572[573; UDPNAGSYN-PWY] fam=5
>>>pathway-572[573; UDPNAGSYN-PWY] fam=5 unique-fam=0
pathway-573[574; VALDEG-PWY] fam=8
   unique fam-2687 2688 1.2.1.25-RXN
   unique fam-2688 2689 MEPROPCOA-FAD-RXN
   unique fam-2689 2690 METHYLACYLYLCOA-HYDROXY-RXN
   unique fam-2690 2691 3-HYDROXYISOBUTYRYL-COA-HYDROLASE-RXN
   unique fam-2691 2692 3-HYDROXYISOBUTYRATE-DEHYDROGENASE-RXN
   unique fam-2692 2693 RXN-11213
   unique fam-2693 2694 2.6.1.22-RXN
>>>pathway-573[574; VALDEG-PWY] fam=8 unique-fam=7
pathway-574[575; VALSYN-PWY] fam=4
>>>pathway-574[575; VALSYN-PWY] fam=4 unique-fam=0
now write mps file..
original ortholog=1662 found-in-the-fam-list=1662 found-in-the-fam-mapped-to-pathway=1662
End of PrintMPS

**Comment by gavinmdouglas** [comment]
Hmm sorry I'm not sure what the issue is based on this message. How much memory do you have on the server you're using?

You could also try running the standalone version outside of QIIME 2, which would likely give you a more informative error (and retain intermediate files up until the pathway reconstruction step).


Cheers,

Gavin

**Comment by wangyd666** [comment]
@gavinmdouglas  
Hi, gavin 
I found the error in the pathway_pipeline.py . Errors were reported as follows: (I run the pathway_pipeline.py  using the example data) . How deal with it ?
 Error running this command:
/home/ubuntu/miniconda3/envs/qiime2/lib/python3.8/site-packages/picrust2/MinPath/MinPath12hmp.py -any /tmp/tmpflphzin2/minpath_running/101CHE6WT_minpath_in.txt -map /tmp/tmpflphzin2/parsed_mapfile.tsv -report /tmp/tmpflphzin2/minpath_running/101CHE6WT_minpath_report.txt -details /tmp/tmpflphzin2/minpath_running/101CHE6WT_minpath_details.txt -mps /tmp/tmpflphzin2/minpath_running/101CHE6WT_minpath.mps

**Comment by wangyd666** [comment]
@gavinmdouglas  It worked when I add the parameter --skip_minpath.  What is the difference between the result with and without this parameter?

**Comment by gavinmdouglas** [comment]
Hi @wangyd666,

That parameter means that MinPath isn't run: so all pathways with any reactions present are called as present. Otherwise, MinPath is run to identify which pathways are most likely to be present. Sorry I'm not sure what the MinPath error is - what version of PICRUSt2 are you running?


Cheers,

Gavin

**Comment by wangyd666** [comment]
@gavinmdouglas  Hi, gavin
It worked when I updated glpk using the command :conda install -c conda-forge glpk.

I compared my error reports about my data and example data and changed the MinPathhmp.py permission (chomod 777,may be unuseful). After run pathway_pipeline.py,  it reported the error that  ''Standard error of the above failed command: Error when running glpsol from MinPath.'' 

Hope for help others facing the same problem as me 

Thanks  for your response !
