### ISSUE TITLE
Can I separate the microbial data set into rare or abundant taxa and conduct picrust2 analysis separately   ？

### ISSUE THREAD

**Issue by YuZhang-learner** [picrust/picrust2#258]
Dear all，
I want to analyze the differences between rare and abundant species, including function. Can I divide the data into rare and abundant species and conduct picrust2 separately? So I can compare the numbers of the two subcommunities in the same pathway.

**Comment by gavinmdouglas** [comment]
Hey @YuZhang-learner, it would be best to generate the stratified output (mentioned in the tutorial), which you can then analyze based on the different sets of ASVs you're interested in. You might also just want to look at the output of `hsp.py` specifically, as it sounds like you just want to compare the predicted genome annotations for rare and abundant ASVs.


Cheers,

Gavin

**Comment by YuZhang-learner** [comment]
> Gavin

Hi，Gavin，thanks for you reply.  But I still have some doubts. Is there a big difference between these two way (split ASV table before or after picrust2)? Because I have a lot of samples and a lot of sequences. As you said, I run the picrust2 at the whole data set before splitting, and the stratified output file is 5.7G. My computer can't make such a large calculation. If it's just a small difference that doesn't affect the overall result, can I split dataset before running picrust2?

**Comment by YuZhang-learner** [comment]
@[gavinmdouglas](https://github.com/gavinmdouglas) Alternatively, can I extract a one-to-one list of ASV and Pathway from stratified Output? So I can merge it with the unstratified file and split it into different dateset according to asv?

**Comment by gavinmdouglas** [comment]
You can get a table of pathways predictions per ASV if you use the `--per_sequence_contrib` option. Is that what you're looking for?


Cheers,

Gavin

**Comment by YuZhang-learner** [comment]
> Hi@[gavinmdouglas](https://github.com/gavinmdouglas) Gavin，thanks for you reply. But I still have some doubts. Is there a big difference between these two way (split ASV table before or after picrust2)? Because I have a lot of samples and a lot of sequences. As you said, I run the picrust2 at the whole data set before splitting, and the stratified output file is 5.7G. My computer can't make such a large calculation. If it's just a small difference that doesn't affect the overall result, can I split dataset before running picrust2?
Hi@[gavinmdouglas](https://github.com/gavinmdouglas), what do you think this question?

**Comment by gavinmdouglas** [comment]
Ah sorry - the placements will differ a little depending on what set of ASVs are aligned together, so there will be some variation there. It would be better to run the place_seqs.py and hsp.py steps with all of the data and then specify different biom tables with different subsets of ASVs at the next stages. Does that make sense?

**Comment by YuZhang-learner** [comment]
Hi@[gavinmdouglas](https://github.com/gavinmdouglas)@[gavinmdouglas](https://github.com/gavinmdouglas). 
Thank you for your patience. I seem to understand what you mean. 
place_seqs.py \
-s all_tax_rep_seqs.fna \
-o out.tre -p 20 \
--intermediate intermediate/place_seqs

 
hsp.py \
-i 16S \
-t out.tre \
-o marker_predicted_and_nsti.tsv.gz \
-p 20 \
-n

This two step run my whole dataset sequence "all_tax_rep_seqs.fna".


metagenome_pipeline.py \
-i rare_otu.biom \
-m marker_predicted_and_nsti.tsv.gz \
-f EC_predicted.tsv.gz \
-o EC_metagenome_out --strat_out

However, this step starts with the OTU table that I get part of the data set, for example "rare_otu.biom". When I have run all the following code, I will run another data set "abundant_otu.biom" from this step?

**Comment by YuZhang-learner** [comment]
@[gavinmdouglas](https://github.com/gavinmdouglas)Thank you very much for your quick reply！

**Comment by YuZhang-learner** [comment]
Hi, Gavin. I have a newquestion.

 
> Hi@[gavinmdouglas](https://github.com/gavinmdouglas), Thank you for your patience. I seem to understand what you mean. Is it as follows ?
> 
> place_seqs.py -s all_tax_rep_seqs.fna -o out.tre -p 20 --intermediate intermediate/place_seqs
> 
> hsp.py -i 16S -t out.tre -o marker_predicted_and_nsti.tsv.gz -p 20 -n
> 
> This two step run my whole dataset sequence "all_tax_rep_seqs.fna".
> 
> metagenome_pipeline.py -i rare_otu.biom -m marker_predicted_and_nsti.tsv.gz -f EC_predicted.tsv.gz -o EC_metagenome_out --strat_out
> 
> However, this step starts with the OTU table that I get part of the data set, for example "rare_otu.biom". When I have run all the following code, I will run another data set "abundant_otu.biom" from this step?

If I get PICRUST results for rare, abundant, and all taxa using the method we discussed above, how do I compare? Can the results of rare and abundant taxa be translated into relative abundance？ For example, I want to calculate the contribution of rare taxa to a particular metabolic function, that is, the ratio of rare taxa to all taxa in a given metabolic function.

**Comment by gavinmdouglas** [comment]
Hi there,

One thing you could do is calculate the stratified community-wide abundance tables (see the `--stratified` option). This will give you information on how much to the community-wide abundance of a function each individual ASV is predicted to contribute.


Cheers,

Gavin
