### ISSUE TITLE
correct pvalues for the inferred pathways?

### ISSUE THREAD

**Issue by marwa38** [picrust/picrust2#261]
Hello amazing people 

Could you please let me know if you think it is advisable to use correct the pvalues on the inferred functional (KEGG) pathways produced form picrust2?
I am using STAMP.

Thanks in advance 
M

**Comment by gavinmdouglas** [comment]
Hi there,

If you are performing an independent test on each pathway, then yes it makes sense to perform multiple-test correction (e.g., Bonferroni or Benjamini-Hochberg). This is true for all data types in most circumstances!


Cheers,

Gavin
