### ISSUE TITLE
Stopping - no sequence ids overlap between all three of the input files.

### ISSUE THREAD

**Issue by Valentin-Bio** [picrust/picrust2#263]
Hello developer! I experienced what seems to be a frequently asked question but the solutions offered ( https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-do-i-troubleshoot-valueerror-no-sequence-ids-overlap-between-all-three-of-the-input-files ) seems to not be my problem

I made a ASVs.biom file from DADA2-phyloseq analysis and I started following your well documented tutorial (thanks so much for it). The issue is that when I come the the community metagenome prediction using the following command:

`metagenome_pipeline.py -i ASVs.biom -m marker_predicted_and_nsti.tsv.gz -f EC_predicted.tsv.gz -o EC_metagenome_out --strat_out`

I get the "Stopping - no sequence ids overlap between all three of the input files." message. 

My IDs seems to be the same named as "ASV#" across all my three files. it may be that a white space is after an id but not sure if it is my case. I took a look into each file and it may be the case that the ids are not in the same order along the rows maybe that can be the problem but not sure.

If it helps , I attach here my working files. (I'm attaching the txt version of my biom file because GitHub is not allowing me to upload a biome file )
[EC_predicted.tsv.gz](https://github.com/picrust/picrust2/files/9080260/EC_predicted.tsv.gz)
[marker_predicted_and_nsti.tsv.gz](https://github.com/picrust/picrust2/files/9080257/marker_predicted_and_nsti.tsv.gz)
[ASVs_table.txt](https://github.com/picrust/picrust2/files/9080270/ASVs_table.txt)

Thanks for your time :)

**Comment by gavinmdouglas** [comment]
Was this resolved @Valentin-Bio ? If so, would you mind sharing what the problem was?

Thanks!

Gavin
