### ISSUE TITLE
_queue.Empty:   parallel.py", line 822, in dispatch_one_batch 

### ISSUE THREAD

**Issue by george-weingart** [picrust/picrust2#264]
Hello,
Trying to run Picrust2 for the first time and getting an error.
The running script is as follows:

#!/bin/bash
iDir="/galaxy-central/tools/galaxy-upgrade/galaxy_picrust2/test_data/workflow"
sDir="/galaxy-central/tools/galaxy-upgrade/galaxy_picrust2/test_data"
picrust2_pipeline.py -s $sDir/study_seqs_test.fasta -i $iDir/workflow_seq_abun.biom -o picrust2_out --processes 10 --stratified --per_sequence_contrib

And the error is as follows:

(galaxy_venv) root@5cc594913c8f:/galaxy-central/tools/galaxy-upgrade/galaxy_picrust2# ./run_picrust2.sh 

All ASVs were below the max NSTI cut-off of 2.0 and so all were retained for downstream analyses.

All ASVs were below the max NSTI cut-off of 2.0 and so all were retained for downstream analyses.

Error running this command:
pathway_pipeline.py --input picrust2_out/EC_metagenome_out/pred_metagenome_unstrat.tsv.gz --out_dir picrust2_out/pathways_out --map /galaxy-central/tools/picrust2/picrust2/default_files/pathway_mapfiles/metacyc_path2rxn_struc_filt_pro.txt --intermediate picrust2_out/intermediate/pathways --proc 10 --regroup_map /galaxy-central/tools/picrust2/picrust2/default_files/pathway_mapfiles/ec_level4_to_metacyc_rxn.tsv --per_sequence_contrib --per_sequence_abun picrust2_out/EC_metagenome_out/seqtab_norm.tsv.gz --per_sequence_function picrust2_out/EC_predicted.tsv.gz

Standard error of the above failed command:
Traceback (most recent call last):
  File "/galaxy_venv/lib/python3.7/site-packages/joblib/parallel.py", line 822, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/tool_deps/_conda/lib/python3.7/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/galaxy_venv/bin/pathway_pipeline.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/galaxy-central/tools/picrust2/scripts/pathway_pipeline.py", line 272, in <module>
    main()
  File "/galaxy-central/tools/picrust2/scripts/pathway_pipeline.py", line 187, in main
    verbose=args.verbose)
  File "/galaxy-central/tools/picrust2/picrust2/pathway_pipeline.py", line 492, in pathway_pipeline
    print_opt=verbose)
  File "/galaxy-central/tools/picrust2/picrust2/pathway_pipeline.py", line 776, in per_sequence_contrib_levels
    for sequence in overlapping_sequence_ids)
  File "/galaxy_venv/lib/python3.7/site-packages/joblib/parallel.py", line 1043, in __call__
    if self.dispatch_one_batch(iterator):
  File "/galaxy_venv/lib/python3.7/site-packages/joblib/parallel.py", line 833, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "/galaxy-central/tools/picrust2/picrust2/pathway_pipeline.py", line 776, in <genexpr>
    for sequence in overlapping_sequence_ids)
  File "/galaxy_venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3461, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/galaxy_venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/galaxy_venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['02905cfb87861c837dde629596d9272b'] not in index"

(galaxy_venv) root@5cc594913c

**Comment by gavinmdouglas** [comment]
Hi George,

I'm not sure what's going on here, but it is likely related to the `--per-sequence-contrib` option requiring a lot of memory. How much memory do you have allocated for this job?


Cheers,

Gavin

**Comment by george-weingart** [comment]
Hi Gavin,
Yup,  that was it - it completed it OK.

As you probably saw,  I am implementing Picrust2 in our Galaxy Test system.

Which files are the ones that a typical user would be interested in ?

That is, assuming the input job looks as I described before:

#!/bin/bash

iDir="/galaxy-central/tools/galaxy-upgrade/galaxy_picrust2/test_data/workflow"

sDir="/galaxy-central/tools/galaxy-upgrade/galaxy_picrust2/test_data"

picrust2_pipeline.py -s $sDir/study_seqs_test.fasta -i
$iDir/workflow_seq_abun.biom -o picrust2_out --processes 10 --stratified



Thanks!

George Weingart PhD
Huttenhower Lab
Harvard School of Public Health

(galaxy_venv) ***@***.***:/galaxy-central/tools/galaxy-upgrade/galaxy_picrust2/picrust2_out#
find . -print

.

./intermediate

./intermediate/place_seqs

./intermediate/place_seqs/query_align.stockholm

./intermediate/place_seqs/ref_seqs_hmmalign.fasta

./intermediate/place_seqs/study_seqs_hmmalign.fasta

./intermediate/place_seqs/epa_out

./intermediate/place_seqs/epa_out/epa_info.log

./intermediate/place_seqs/epa_out/epa_result.jplace

./intermediate/place_seqs/epa_out/epa_result_parsed.jplace

./intermediate/pathways

./intermediate/pathways/regrouped_infile.tsv

./intermediate/pathways/parsed_mapfile.tsv

./intermediate/pathways/minpath_running

./intermediate/pathways/minpath_running/s1_minpath_in.txt

./intermediate/pathways/minpath_running/s2_minpath_in.txt

./intermediate/pathways/minpath_running/s1_minpath_report.txt

./intermediate/pathways/minpath_running/s1_minpath_details.txt

./intermediate/pathways/minpath_running/s2_minpath_report.txt

./intermediate/pathways/minpath_running/s2_minpath_details.txt

./out.tre

./marker_predicted_and_nsti.tsv.gz

./EC_predicted.tsv.gz

./KO_predicted.tsv.gz

./EC_metagenome_out

./EC_metagenome_out/seqtab_norm.tsv.gz

./EC_metagenome_out/weighted_nsti.tsv.gz

./EC_metagenome_out/pred_metagenome_unstrat.tsv.gz

./EC_metagenome_out/pred_metagenome_contrib.tsv.gz

./KO_metagenome_out

./KO_metagenome_out/seqtab_norm.tsv.gz

./KO_metagenome_out/weighted_nsti.tsv.gz

./KO_metagenome_out/pred_metagenome_unstrat.tsv.gz

./KO_metagenome_out/pred_metagenome_contrib.tsv.gz

./pathways_out

./pathways_out/path_abun_unstrat.tsv.gz

./pathways_out/path_abun_contrib.tsv.gz
(galaxy_venv) ***@***.***
:/galaxy-central/tools/galaxy-upgrade/galaxy_picrust2/picrust2_out#

**Comment by gavinmdouglas** [comment]
Ideally all of these files would be returned:

```
./intermediate/place_seqs/epa_out/epa_result_parsed.jplace

./out.tre

./marker_predicted_and_nsti.tsv.gz

./EC_predicted.tsv.gz

./KO_predicted.tsv.gz

# Note that this file should be the same in the KO_metagenome_out directory too - so only one needs to be retained
./EC_metagenome_out/seqtab_norm.tsv.gz

./EC_metagenome_out/weighted_nsti.tsv.gz

./EC_metagenome_out/pred_metagenome_unstrat.tsv.gz

./EC_metagenome_out/pred_metagenome_contrib.tsv.gz

./KO_metagenome_out/weighted_nsti.tsv.gz

./KO_metagenome_out/pred_metagenome_unstrat.tsv.gz

./KO_metagenome_out/pred_metagenome_contrib.tsv.gz

./pathways_out/path_abun_unstrat.tsv.gz

./pathways_out/path_abun_contrib.tsv.gz

```

Otherwise, the files in each output directory would be the typical files that are analyzed.


Cheers,

Gavin
