### ISSUE TITLE
Error in readChar(file, file.info(file)$size) :    cannot allocate memory block of size 16777216 Tb

### ISSUE THREAD

**Issue by qbdong122** [picrust/picrust2#267]
I met this question when I run picrust2 following command: picrust2_pipeline.py -s study_seqs.fna -i study_seqs.biom -o picrust2_out_pipeline -p 12
Here is error info:
```
Error running this command:
hsp.py --tree LLD_out_pipeline/out.tre --output LLD_out_pipeline/marker_predicted_and_nsti.tsv.gz --observed_trait_table /public/home/p282664/soft/picrust2/picrust2/default_files/prokaryotic/16S.txt.gz --hsp_method mp --edge_exponent 0.5 --seed 100 --calculate_NSTI --processes 1

Standard error of the above failed command:

Error running this command:
Rscript ~/soft/picrust2/picrust2/Rscripts/castor_nsti.R LLD_out_pipeline/out.tre  /tmp/tmpu_7rb2nq/known_tips.txt /tmp/tmpu_7rb2nq/nsti_out.txt

Standard error of the above failed command:
Error in readChar(file, file.info(file)$size) : 
  cannot allocate memory block of size 16777216 Tb
Calls: read_tree -> readChar
Execution halted
```

How do I solve this?

**Comment by gavinmdouglas** [comment]
Hi there,

Sorry for the late response. 

It looks like an enormous amount of memory is being allocated for that command. How many tips are in your input tree? 

It looks like someone else ran into a similar problem with a different tree file: https://stackoverflow.com/questions/34874007/cannot-allocate-memory-block-using-r-plot-phylo


Would you mind sending over your tree file to me at <img width="144" alt="gmail_screenshot" src="https://user-images.githubusercontent.com/12489683/184425879-7b20aba8-71ee-4ddd-96e1-a15f1f31ae40.png"> ? I can help troubleshoot what's going on if so.

**Comment by gavinmdouglas** [comment]
Closing for now due to inactivity.
