### ISSUE TITLE
add_description workflow in metacyc (similar to KEGG)?

### ISSUE THREAD

**Issue by marwa38** [picrust/picrust2#268]
Hi 
I used `add_description` to infer enriched functional KEGG pathways, it is not clear though whether this is L1 or L2 or L3 
Could you please let me know if I can run something similar for metacyc? when I checked the pathway mapfiles available I found 
```
metacyc_rxn_to_level4ec
ec_level4_to_metacyc_rxn
metacyc_pathways_structured_filtered
```
Which one I should use?

Here are my detailed codes in case you would like to have look. 
```
# cd picrust2_out_pipeline beforehand
# pathway_pipeline.py -i KO_metagenome_out/pred_metagenome_unstrat.tsv -o KEGG_pathways_out --no_regroup --map /home/r01mt19/picrust2-2.4.2/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv
# gunzip KEGG_pathways_out/path_abun_unstrat.tsv.gz
# add_descriptions.py -i KEGG_pathways_out/path_abun_unstrat.tsv --custom_map_table /home/r01mt19/picrust2-2.4.2/picrust2/default_files/description_mapfiles/KEGG_pathways_info.tsv  -o KEGG_pathways_out/KEGG_path_abun_unstrat_descrip.tsv
# edit output desc file (as all descriptoin files) remove first column and rename second column "pathway"
## then use STAMP
# KEGG_path_abun_unstrat_descrip_ed along with the same metadata 
```

Thanks 
Marwa

**Comment by gavinmdouglas** [comment]
Hi there,

The KEGG pathways refer to L3 I believe in KEGG BRITE.

For adding the metacyc pathway details, you can just specify “METACYC” and it will automatically use a default file. See this part of the tutorial:

https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.5.0)#add-functional-descriptions <https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.5.0)#add-functional-descriptions>


Cheers,

Gavin
