### ISSUE TITLE
About fungi prediction, what's the source of genomes functions and ITS seqs? I don't found the ids present at "fungi_ITS.fna.gz" header in IMG database. Fungi prediction is recommended with picrust2?

### ISSUE THREAD

**Issue by caligarimga** [picrust/picrust2#269]

**Comment by gavinmdouglas** [comment]
Hi @caligarimga,

That database (created from a subset of the 1000 fungi database) is described in the supplementary materials of the picrust2 paper: https://www.nature.com/articles/s41587-020-0548-6

No it's actually not recommended - you can see in our validations of that database in our manuscript (again see the supplementary materials), that it worked better than random, but was still extremely noisy. 


Cheers,

Gavin

**Comment by caligarimga** [comment]
Thank u Gavin!
