### ISSUE TITLE
mamba env create -f picrust2-env.yaml error

### ISSUE THREAD

**Issue by nmacknight** [picrust/picrust2#271]
Hello, 

When running: `mamba env create -f picrust2-env.yaml`

I receive this response/error:
_____________________________________________________

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
r/osx-arm64                                                 Using cache
r/noarch                                                    Using cache
bioconda/osx-arm64                                          Using cache
bioconda/noarch                                             Using cache
anaconda/osx-arm64                                          Using cache
anaconda/noarch                                             Using cache
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change
pkgs/main/osx-arm64                                           No change
pkgs/r/osx-arm64                                              No change

Looking for: ["biom-format[version='>=2.1.10']", 'cython', 'epa-ng=0.3.8', 'gappa=0.8.0', 'glpk=4.65', "h5py[version='>=3.1.0']", "hmmer[version='>=3.1b2,<=3.2.1']", "jinja2[version='>=2.11.3']", "joblib[version='>=1.0.1']", "numpy[version='>=1.19.5']", "pandas[version='>=1.1.5']", "pytest[version='>=4.4.1']", "pytest-cov[version='>=2.6.1']", "python[version='>=3.5,<3.9']", "r-base[version='>=3.5.1']", 'r-castor=1.7.2', "scipy[version='>=1.2.1']", 'sepp=4.3.10']

Encountered problems while solving:
  - nothing provides requested biom-format >=2.1.10
  - nothing provides requested epa-ng 0.3.8**
  - nothing provides requested gappa 0.8.0**
  - nothing provides requested hmmer >=3.1b2,<=3.2.1
  - nothing provides requested r-castor 1.7.2**
  - nothing provides requested sepp 4.3.10**
_____________________

The tutorial does not provide guidance on how to install these dependencies. 

Thank you for your time.

**Comment by gavinmdouglas** [comment]
Hey @nmacknight,

All of those dependencies are meant to be installed with that mamba command.

I would try:

- Updating mamba and retrying
- Updating conda and retrying the command, but with `mamba` replaced with `conda`
- Installing with conda from bioconda

**Comment by nmacknight** [comment]
Hi Gavin, 


**Updating mamba and retrying**
I initially installed Mamba using:
`conda install mamba -n base -c conda-forge`

My Current Version of Mamba and Conda are:
`mamba --version`
mamba 0.25.0
conda 4.14.0


**Updating conda and retrying the command, but with mamba replaced with conda**

I then updated conda with: `conda update conda`
Then Verified Conda version with: `conda --version`
To get the same version as before: conda 4.14.0

I attempted the command again, replacing mamba for conda:
`conda env create -f picrust2-env.yaml`

And received a functionally similar error that brought me to this forum:

"Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - biom-format[version='>=2.1.10']
  - hmmer[version='>=3.1b2,<=3.2.1']
  - epa-ng=0.3.8
  - sepp=4.3.10
  - r-castor=1.7.2
  - gappa=0.8.0
"

**Installing with conda from bioconda**
Using: `mamba create -n picrust2 -c bioconda -c conda-forge picrust2=2.5.0` Which I received from: https://github.com/picrust/picrust2/wiki/Installation

Everything was looking okay until this error:
"Encountered problems while solving:
  - nothing provides epa-ng 0.3.8.* needed by picrust2-2.5.0-pyhdfd78af_0"

So then I tried Installing epa-ng from github using:
```
wget https://github.com/Pbdas/epa-ng/archive/v0.3.8.tar.gz
tar xvzf  v0.3.8.tar.gz
```
And then adding my PATH to this directory but still I receive the "nothing provides epa-ng 0.3.8* needed by picrust2-2.5.0...."

Tricky.

**Comment by gavinmdouglas** [comment]
Hi @nmacknight,

I'm unable to reproduce this issue.

I think what's happening here might be related to the  `channel_priority` setting.

E.g., you could try setting:
```
conda config --set channel_priority flexible
```

As mentioned here: https://github.com/rapidsai/cuml/issues/4016
