### ISSUE TITLE
Generating a KEGG module table from the KO table

### ISSUE THREAD

**Issue by RaniaAIsmail** [picrust/picrust2#275]
Hi Gavin,

Thank you so much for this great program. I'm trying to generate a KEGG module table from the KO table generated by PICRUSt2, but I could see that generating this table using PICRUSt command doesn't take into account the differences between the key and optional KOs. 
I know it may not be a part of PICRUSt2 project, but would you by any means offer R code/Linux code that can implement a more stringent module prediction pipeline with computing the abundance for each module?

Many thanks,
Rania

**Comment by gavinmdouglas** [comment]
Hi there,

I don't have a structured mapfile linking optional and required KOs to modules, but in principle  if one was formatted the same as the MetaCyc pathway to EC mapfile (which is the default file, https://github.com/picrust/picrust2/blob/master/picrust2/default_files/pathway_mapfiles/metacyc_pathways_structured_filtered, and does contain optional and required reactions), then you could simply specify it as the mapfile to use when running picrust2 with KOs.

I have no plans to work on this project further, so this is not something that I will have time to do unfortunately. It is also complicated by the fact that I do not believe it is legal to distribute the latest version of KEGG files. So I don't think I would be able to include such a mapfile in the PICRUSt2 repository, at least not based on a recent KEGG version.


Hopefully that helps,

Gavin
