### ISSUE TITLE
Error picrust2 picrust2_pipeline.py

### ISSUE THREAD

**Issue by ramostapiai** [picrust/picrust2#281]
Hello,

I have installed Picrust2, I have used it before I have installed with conda without problems, but now something is wrong when I try to run new inferences with the error at the end. I hope you can help me.
Best,

Standard output of the above failed command:

Standard error of the above failed command:
hmmalign --trim --dna --mapali /Users/bionacho/Documents/picrust2-master/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --informat FASTA -o picrust2_out_16S/intermediate/place_seqs/query_align.stockholm /Users/bionacho/Documents/picrust2-master/picrust2/default_files/prokaryotic/pro_ref/pro_ref.hmm sequences_16S.fasta

Traceback (most recent call last):
  File "/Users/bionacho/miniconda3/envs/picrust2/bin/place_seqs.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/bionacho/Documents/picrust2-master/scripts/place_seqs.py", line 111, in <module>
    main()
  File "/Users/bionacho/Documents/picrust2-master/scripts/place_seqs.py", line 87, in main
    place_seqs_pipeline(study_fasta=args.study_fasta,
  File "/Users/bionacho/Documents/picrust2-master/picrust2/place_seqs.py", line 52, in place_seqs_pipeline
    hmmalign_out = read_stockholm(out_stockholm, clean_char=True)
  File "/Users/bionacho/Documents/picrust2-master/picrust2/util.py", line 207, in read_stockholm
    if line[0:2] != "//":
UnboundLocalError: local variable 'line' referenced before assignment

**Comment by gavinmdouglas** [comment]
Ah that error is happening because it's not able to read anything at all for the alignment file. Can you post the top of the sequence file you are inputting?


Thanks,

Gavin

**Comment by ramostapiai** [comment]
Hi, 
Thanks for the replay. Sorry for the delay and sure i put follow the fasta ii used.

>ASV2
CCTACGGGTGGCAGCAGTGGGGAATTGTTCGCAATGGGCGCAAGCCTGACGACGCAACGCCGCGTGGAGGATGAAGGTCTTCGGATTGTAAACTCCTGTTGCCCGGGACGAATGGCTTCAACCTAATACGTTGGAGATTGACGGTACCGGGTGAGGAAGCCCCGGCTAACTCTGTGCCAGCAGCCGCGGTAATACAGAGGGGGCAAGCGTTGTTCGGAATTACTGGGCGTAAAGGGCGCGTAGGCGGCCTTCTAAGTCGAACGTGAAATCCCCGGGCTCAACCCGGGAACTGCGTCCGATACTGGAAGGCTTGAATCCGGGAGAGGGATGTGGAATTCCAGGTGTAGCGGTGAAATGCGTAGATATCTGGAGGAACACCGGTGGCGAAGGCGACATCCTGGACCGGTATTGACGCTGAGGCGCGAAAGCCAGGGGAGCAAACGGGATTAGATACCCTAGTAGTC
>ASV3
CCTACGGGGGGCAGCAGTGGGGAATTGTTCGCAATGGGCGCAAGCCTGACGACGCAACGCCGCGTGGAGGATGAAGGTCTTCGGATTGTAAACTCCTGTTGCCCGGGACGAATGGCTTCAACCTAATACGTTGGAGATTGACGGTACCGGGTGAGGAAGCCCCGGCTAACTCTGTGCCAGCAGCCGCGGTAATACAGAGGGGGCAAGCGTTGTTCGGAATTACTGGGCGTAAAGGGCGCGTAGGCGGCCTTCTAAGTCGAACGTGAAATCCCCGGGCTCAACCCGGGAACTGCGTCCGATACTGGAAGGCTTGAATCCGGGAGAGGGATGTGGAATTCCAGGTGTAGCGGTGAAATGCGTAGATATCTGGAGGAACACCGGTGGCGAAGGCGACATCCTGGACCGGTATTGACGCTGAGGCGCGAAAGCCAGGGGAGCAAACGGGATTAGATACCCTAGTAGTC
>ASV4
CCTACGGGGGGCAGCAGTGGGGAATTGTTCGCAATGGGCGCAAGCCTGACGACGCAACGCCGCGTGGAGGATGAAGGTCTTCGGATTGTAAACTCCTGTTGCCCGGGACGAATGGCTTCAACCTAATACGTTGGAGATTGACGGTACCGGGTGAGGAAGCCCCGGCTAACTCTGTGCCAGCAGCCGCGGTAATACAGAGGGGGCGAGCGTTGTTCGGAATTACTGGGCGTAAAGGGCGCGTAGGCGGCCTTCTAAGTCGAACGTGAAATCCCCGGGCTCAACCCGGGAACTGCGTCCGATACTGGAAGGCTTGAATCCGGGAGAGGGATGCGGAATTCCAGGTGTAGCGGTGAAATGCGTAGATATCTGGAGGAACACCGGTGGCGAAGGCGGCATCCTGGACCGGTATTGACGCTGAGGCGCGAAAGCCAGGGGAGCAAACGGGATTAGATACCCTTGTAGTC
>ASV5
CCTACGGGAGGCAGCAGTGGGGAATTGTTCGCAATGGGCGCAAGCCTGACGACGCAACGCCGCGTGGAGGATGAAGGTCTTCGGATTGTAAACTCCTGTTGCCCGGGACGAATGGCTTCAACCTAATACGTTGGAGATTGACGGTACCGGGTGAGGAAGCCCCGGCTAACTCTGTGCCAGCAGCCGCGGTAATACAGAGGGGGCGAGCGTTGTTCGGAATTACTGGGCGTAAAGGGCGCGTAGGCGGCCTTCTAAGTCGAACGTGAAATCCCCGGGCTCAACCCGGGAACTGCGTCCGATACTGGAAGGCTCGAATCCGGGAGAGGGATGCGGAATTCCAGGTGTAGCGGTGAAATGCGTAGATATCTGGAGGAACACCGGTGGCGAAGGCGGCATCCTGGACCGGTATTGACGCTGAGGCGCGAAAGCCAGGGGAGCAAACGGGATTAGATACCCCTGTAGTC
>ASV6
CCTACGGGAGGCAGCAGTGGGGAATTGTTCGCAATGGGCGCAAGCCTGACGACGCAACGCCGCGTGGAGGATGAAGGTCTTCGGATTGTAAACTCCTGTTGCCCGGGACGAATGGCTTCAACCTAATACGTTGGAGATTGACGGTACCGGGTGAGGAAGCCCCGGCTAACTCTGTGCCAGCAGCCGCGGTAATACAGAGGGGGCAAGCGTTGTTCGGAATTACTGGGCGTAAAGGGCGCGTAGGCGGCCTTCTAAGTCGAACGTGAAATCCCCGGGCTCAACCCGGGAACTGCGTCCGATACTGGAAGGCTTGAATCCGGGAGAGGGATGTGGAATTCCAGGTGTAGCGGTGAAATGCGTAGATATCTGGAGGAACACCGGTGGCGAAGGCGACATCCTGGACCGGTATTGACGCTGAGGCGCGAAAGCCAGGGGAGCAAACGGGATTAGATACCCCAGTAGTC

**Comment by ramostapiai** [comment]
Thank you very much for the reply. I checked the stream input fasta file and realized that my R function didn't save it in fasta format. I converted it again and everything worked. 

All the best
