### ISSUE TITLE
i get "1 failed, 60 passed" when i run the tests to verify the installation after installed picrust2-2.5.0 from source

### ISSUE THREAD

**Issue by liulanzhou** [picrust/picrust2#282]

**Comment by liulanzhou** [comment]
Thank you for reading my problem, can you help me resolve this question.
when i run the tests to verify the installation after installed picrust2-2.5.0 from source, i got the short test summary info is "FAILED tests/test_place_seqs.py::place_seqs_tests::test_run_place_seqs_pipeline_sepp - SystemExit: 1".i have two computers,i install picrust2-2.5.0 on a computer one month ago, it is perfect. however, when i install  picrust2-2.5.0 on another computer, i get "5 failed, 56 passed" when i run the tests to verify the installation after installed picrust2-2.5.0 from source several days ago. Then i thought for it ，i modify the document "picrust2-env.yaml" that form https://github.com/picrust/picrust2/archive/v2.5.0.tar.gz. the original picrust2-env.yaml contian 
"dependencies:
- biom-format >=2.1.10
- cython
- epa-ng=0.3.8
- gappa=0.8.0
- glpk=4.65
- h5py >=3.1.0
- hmmer >=3.1b2,<=3.2.1
- jinja2 >=2.11.3
- joblib >=1.0.1
- numpy >=1.19.5
- pandas >=1.1.5
- pytest >=4.4.1
- pytest-cov >=2.6.1
- python >=3.5,<3.9
- r-base >=3.5.1
- r-castor=1.7.2
- scipy >=1.2.1
- sepp=4.3.10"
then i modify the dependencies, the modified dependencies like below as shown below
"dependencies:
- biom-format =2.1.12
- cython=0.29.31
- epa-ng=0.3.8
- gappa=0.8.0
- glpk=4.65
- h5py =3.7.0
- hmmer =3.1b2
- jinja2 =3.1.2
- joblib =1.1.0
- numpy =1.23.1
- pandas =1.4.3
- pytest =7.1.2
- pytest-cov =3.0.0
- python =3.8.13
- r-base =4.1.3
- r-castor=1.7.2
- scipy =1.8.1
- sepp=4.3.10"

then i execute the install code and test code again, i got "1 failed, 60 passed" .i guess the only failed is because the version of    dependencies,like the other 4 failed resolved by myself.

thank you for read my problem entirely, I would appreciate it if you could help me. i am sorry for my English is poor that maybe take some confusement.

**Comment by gavinmdouglas** [comment]
Can you confirm that you are installing the tool in a new conda environment?

You could try re-installing in a conda environment after running these commands:

```
conda update conda
conda clean --all
```

**Comment by liulanzhou** [comment]
> Can you confirm that you are installing the tool in a new conda environment?
> 
> You could try re-installing in a conda environment after running these commands:
> 
> ```
> conda update conda
> conda clean --all
> ```

**Comment by liulanzhou** [comment]
Thanks much for your advisement and help.
i try to re-install my windows subsystem for linux and re-install my miniconda3,
then execute the commands that 
(base) abc@LAPTOP-JJ9SVUPM:/mnt/d/ubuntu$ **conda update conda**
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done
(base) abc@LAPTOP-JJ9SVUPM:/mnt/d/ubuntu$ **conda clean --all**
There are no unused tarball(s) to remove.
Will remove 1 index cache(s).
Proceed ([y]/n)? y

There are no unused package(s) to remove.
There are no tempfile(s) to remove.
There are no logfile(s) to remove.
(base) abc@LAPTOP-JJ9SVUPM:/mnt/d/ubuntu$

than i Install picrust2-2.5.0 from source referring **https://github.com/picrust/picrust2/wiki/Installation**
but it occur **5 failed, 56 passed, 14 warnings** when run the tests to verify the installation
========= short test summary info =========
FAILED tests/test_pathway_pipeline.py::run_minpath_tests::test_strat_default_pipeline_wide - AssertionError: DataF...
FAILED tests/test_pathway_pipeline.py::run_minpath_tests::test_strat_per_genome_pipeline - AssertionError: DataFra...
FAILED tests/test_pathway_pipeline.py::run_minpath_tests::test_strat_per_genome_pipeline_strat_input - AssertionEr...
FAILED tests/test_pathway_pipeline.py::run_minpath_tests::test_unstrat_default_pipeline - AssertionError: DataFram...
FAILED tests/test_place_seqs.py::place_seqs_tests::test_run_place_seqs_pipeline_sepp - SystemExit: 1
========= 5 failed, 56 passed, 14 warnings in 93.35s (0:01:33) =========

then i remove picrust2 environment with command "conda deactivate" and "conda remove -n picrust2 --all"

i modify the document "picrust2-env.yaml" that form https://github.com/picrust/picrust2/archive/v2.5.0.tar.gz. 
the original picrust2-env.yaml contian
"dependencies:

biom-format >=2.1.10
cython
epa-ng=0.3.8
gappa=0.8.0
glpk=4.65
h5py >=3.1.0
hmmer >=3.1b2,<=3.2.1
jinja2 >=2.11.3
joblib >=1.0.1
numpy >=1.19.5
pandas >=1.1.5
pytest >=4.4.1
pytest-cov >=2.6.1
python >=3.5,<3.9
r-base >=3.5.1
r-castor=1.7.2
scipy >=1.2.1
sepp=4.3.10"

then i modify the dependencies, the modified dependencies like below as shown below
"dependencies:
biom-format =2.1.12
cython=0.29.31
epa-ng=0.3.8
gappa=0.8.0
glpk=4.65
h5py =3.7.0
hmmer =3.1b2
jinja2 =3.1.2
joblib =1.1.0
numpy =1.23.1
pandas =1.4.3
pytest =7.1.2
pytest-cov =3.0.0
python =3.8.13
r-base =4.1.3
r-castor=1.7.2
scipy =1.8.1
sepp=4.3.10"

then i execute the install code and test code again, i got "**1 failed, 60 passed**" .
========= short test summary info ======
FAILED tests/test_place_seqs.py::place_seqs_tests::test_run_place_seqs_pipeline_sepp - SystemExit: 
========= 1 failed, 60 passed in 92.11s (0:01:32) ===========

as far as i am concerned, the only failed is resulted in the version of dependencies and soft in picrust environment probably.

thank you for read my problem entirely, I would appreciate it if you could help me.

**Comment by gavinmdouglas** [comment]
Thanks @liulanzhou,

Yes it looks like there is an incompatibility with the newest versions of pandas and/or numpy with PICRUSt2. I'll look into making this fix when I get a chance, but for the meantime you should be able to revert to older versions of those packages.


Cheers,

Gavin

**Comment by liulanzhou** [comment]
Hi Gavin,
Thanks very much for your work and help. i try many methods to make this problem resolved, but failed. i am looking forward to you can fix this problem on the picrust2-v2.5.0, and more hope you group release an updated version for picrust2. the picrust2 is wonderful  for prediction of metagenome functions, we like it very much. morely, i want to offer an advice for avoiding this incompatibility problem that newest versions of softs and their dependences, just my personal view, by specify the specific version of softs and their dependences, like " numpy =1.19.5" rather than "numpy >=1.19.5". i think that maybe resolve similar incompatibility problems like i meet. however ,i am a new people for picrust2, may my advice is useless, thank you for reading my opinions.


Cheers,


liulanzhou


-----------------
| |
柳兰洲
|
|
***@***.***
|
---- Replied Message ----
| From | Gavin ***@***.***> |
| Date | 10/17/2022 03:05 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [picrust/picrust2] i get "1 failed, 60 passed" when i run the tests to verify the installation after installed picrust2-2.5.0 from source (Issue #282) |

Thanks @liulanzhou,

Yes it looks like there is an incompatibility with the newest versions of pandas and/or numpy with PICRUSt2. I'll look into making this fix when I get a chance, but for the meantime you should be able to revert to older versions of those packages.

Cheers,

Gavin

**Comment by gavinmdouglas** [comment]
Sorry to hear that you're having trouble making it work @liulanzhou !

I'll make that update when I get a chance - I definitely agree that specifying bounded version ranges that can be used makes the most sense to make sure installation protocols are stable. Some people don't like that approach, because it limits what other tools can be compatible with a project, but I think this situation is more important to avoid!


Thanks again and sorry for the inconvenience,

Gavin

**Comment by liulanzhou** [comment]
Thanks for your attention and acceptance, Gavin.
I am very honored to provide the picrust2 item with some suggestions for improvement, hope you and your group can make picrust2 better. On behalf of the majority of relevant scientific researchers, I would like to thank you for your great work.


Thanks again,


liulanzhou
| |
柳兰洲
|
|
***@***.***
|
---- Replied Message ----
| From | Gavin ***@***.***> |
| Date | 10/18/2022 21:10 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [picrust/picrust2] i get "1 failed, 60 passed" when i run the tests to verify the installation after installed picrust2-2.5.0 from source (Issue #282) |

Sorry to hear that you're having trouble making it work @liulanzhou !

I'll make that update when I get a chance - I definitely agree that specifying bounded version ranges that can be used makes the most sense to make sure installation protocols are stable. Some people don't like that approach, because it limits what other tools can be compatible with a project, but I think this situation is more important to avoid!

Thanks again and sorry for the inconvenience,

Gavin

**Comment by liulanzhou** [comment]
Hi Gavin,
When I found the new version PICRUSt2 v2.5.1, I was very excited and immediately tried to install it. However, i still got " 1 failed, 60 passed, 1 warning" when i run the tests to verify the installation after installed picrust2-2.5.1 from source. I guess it have some bug like the PICRUSt2 v2.5.0, namely the only failed is resulted in the version of dependencies and soft in picrust environment probably. I try to fix it but failed, can you help me to resolve it?

The warnings summary and the short test summary info like follows:
============= warnings summary =============
tests/test_pathway_pipeline.py::run_minpath_tests::test_strat_per_genome_pipeline_strat_input
  /mnt/d/ubuntu/picrust2-2.5.1/picrust2/pathway_pipeline.py:1195: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
    regrouped_table = pd.pivot_table(raw_new_ids_combined,

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============= short test summary info =============
FAILED tests/test_place_seqs.py::place_seqs_tests::test_run_place_seqs_pipeline_sepp - SystemExit: 1
============= 1 failed, 60 passed, 1 warning in 96.23s (0:01:36) =============

Thank you very much for your work!

Cheers,

liulanzhou

**Comment by gavinmdouglas** [comment]
Hi @liulanzhou,

You can ignore that warning, the actual failed test is related to placing sequences with SEPP. I wasn't able to replicate any issues like that - perhaps you have a different version of SEPP already in your $PATH? Either way, as long as you place sequences with EPA-ng instead, you shouldn't run into any errors.


Cheers,

Gavin

**Comment by liulanzhou** [comment]
Hi @gavinmdouglas ,

I am successful when avoiding use SEPP, thank you very much. And, i hope your team can fix it in the future and make it perfect, thanks.

Cheers,

liulanzhou
