### ISSUE TITLE
Invalid model name error

### ISSUE THREAD

**Issue by dhwanidesai** [picrust/picrust2#283]
Hi,
I tried to run the picrust2_pipeline.py with an ASV table and a coresponding fasta file. I got the follwoing error:
"
Error running this command:
place_seqs.py --study_fasta ASVs_BB_no_mito_no_chloro.fasta --ref_dir /home/larochelabdhwani1/miniconda/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref --out_tree picrust2_out_pipeline_no_chloro_no_mito_stratified-191022/out.tre --processes 10 --intermediate picrust2_out_pipeline_no_chloro_no_mito_stratified-191022/intermediate/place_seqs --min_align 0.8 --chunk_size 5000 --placement_tool epa-ng

Standard error of the above failed command:

Error running this command:
epa-ng --tree /home/larochelabdhwani1/miniconda/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa picrust2_out_pipeline_no_chloro_no_mito_stratified-191022/intermediate/place_seqs/ref_seqs_hmmalign.fasta --query picrust2_out_pipeline_no_chloro_no_mito_stratified-191022/intermediate/place_seqs/study_seqs_hmmalign.fasta --chunk-size 5000 -T 10 -m /home/larochelabdhwani1/miniconda/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w picrust2_out_pipeline_no_chloro_no_mito_stratified-191022/intermediate/place_seqs/epa_out --filter-acc-lwr 0.99 --filter-max 100

Standard output of the above failed command:
INFO Selected: Output dir: picrust2_out_pipeline_no_chloro_no_mito_stratified-191022/intermediate/place_seqs/epa_out/
INFO Selected: Query file: picrust2_out_pipeline_no_chloro_no_mito_stratified-191022/intermediate/place_seqs/study_seqs_hmmalign.fasta
INFO Selected: Tree file: /home/larochelabdhwani1/miniconda/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre
INFO Selected: Reference MSA: picrust2_out_pipeline_no_chloro_no_mito_stratified-191022/intermediate/place_seqs/ref_seqs_hmmalign.fasta
INFO Selected: Filtering by accumulated threshold: 0.99
INFO Selected: Maximum number of placements per query: 100
INFO Selected: Specified model file: /home/larochelabdhwani1/miniconda/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model

Standard error of the above failed command:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid model name: 
"
What am I doing wrong here?

I am using picrust2 version 2.4.1

Please let me know if I need to post any other info regarding the run.

regards,
Dhwani

**Comment by gavinmdouglas** [comment]
Hey Dhwani,

Would you mind sharing your input FASTA file? I'm thinking maybe there is something about the header-lines that is causing problems, or perhaps IUPAC nucleotide characters that are causing problems for the alignment.


Thanks,

Gavin

**Comment by dhwanidesai** [comment]
Hi Gavin,
I think it was a problem with older versions of epa-ng and gappa in my /home/<>/bin folder which was being called by default.
I removed them and that error disappeared.

You can close the issue now.

Thanks!

regards,
Dhwani
________________________________

**Comment by gavinmdouglas** [comment]
Oh ok good to know.

I hope all is well with you and yours, Dhwani!


Gavin
