### ISSUE TITLE
PICRUSt2 with other database(e.g. cowpi)

### ISSUE THREAD

**Issue by sangmok920622** [picrust/picrust2#284]
Hi, I leave a question about changing the reference database for metagenome prediction in PICRUSt2.

Actually, I want to change the DB to cowpi, a rumen-specialized database.

Is there any option or parameter that can change the reference DB??

I feel really grateful if anyone can give me some advice.

Thanks in advance!

**Comment by gavinmdouglas** [comment]
Hi @sangmok920622 , 

Please see this FAQ for how to run non-default databases: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-a-custom-or-non-default-database-such-as-the-fungi-18s-and-its-databases


Hopefully that answers your question!


Gavin

**Comment by sangmok920622** [comment]
> Hi @gavinmdouglas ,

Thanks for your quick reply.
I think the method for run the non-default DB that you mentioned seems to prepare many additional input files.
Since I already get precalculated files for cowpi, I will use picrust1 first.
If it doesn't work, I will re-try the methods you suggested.

Thanks again.
