### ISSUE TITLE
warning line 341 "metagenome_pipeline.py"

### ISSUE THREAD

**Issue by csmiguel** [picrust/picrust2#286]
I get the following warning when running `metagenome_pipeline.py`. The expected output is generated.

.../`anaconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/metagenome_pipeline.py:341: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.`

On a MacBook Pro 2018 with Catalina.

**Comment by gavinmdouglas** [comment]
Hi there,

Thanks for posting this! This is now resolved in v2.5.1.


Gavin
