### ISSUE TITLE
Running PICRUSt on ITS sequences

### ISSUE THREAD

**Issue by jspychalla** [picrust/picrust2#288]
Hello 

I am running PICRUSt2 on ITS samples 

I ran the code 
place_seqs.py -s study_seqs.fna -o/--out_tree default_files/fungi 

I think for the place_seqs command I need to specify a fungal reference sequence since all of my sequences were poorly aligned to a reference sequence. 

I know I need to specify something like --ref_dir default_files/fungi in the above code. I visited this page on custom reference files: https://github.com/picrust/picrust2/wiki/Sequence-placement

It confused me a bit. Do I need to build my own fungal reference files? Can I download fungal reference files from another place? 

Thank you for your time and help.

**Comment by gavinmdouglas** [comment]
Hi there,

This FAQ answer should help: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-a-custom-or-non-default-database-such-as-the-fungi-18s-and-its-databases

Please pay special attention to the warning that the fungal predictions are expected to be much noisier than for prokaryotes, so they should be used very cautiously.


Cheers,

Gavin
