### ISSUE TITLE
Calling in ITS reference

### ISSUE THREAD

**Issue by jspychalla** [picrust/picrust2#289]
Hi, 
I'm new to working in terminal and I am trying to run one of the first commands of the PICRUSt pipeline. Below is the line I run and the error message I get. 

picrust2 % place_seqs.py -s study_seqs.fna -o/--out_tree--ref_dir default_files/fungi/fungi_ITS 
usage: place_seqs.py [-h] -s PATH [-t epa-ng|sepp] [-r PATH] -o PATH
                     [-p PROCESSES] [--intermediate PATH]
                     [--min_align MIN_ALIGN] [--chunk_size CHUNK_SIZE]
                     [--verbose] [-v]
place_seqs.py: error: unrecognized arguments: default_files/fungi/fungi_ITS

What am I doing wrong when trying to call in the reference directory? 

Thank you for your time

**Comment by jspychalla** [comment]
https://github.com/picrust/picrust2/issues/180

From this thread I see that if it is run with EPA-NG it works fine. What is EPA-NG?

**Comment by gavinmdouglas** [comment]
Hi there,

The first error `place_seqs.py: error: unrecognized arguments: default_files/fungi/fungi_ITS` indicates that the script thinks that `default_files/fungi/fungi_ITS` is a flag (e.g., `-r`), when it is actually a path you are trying to input. So you must be missing a flag name or perhaps missing whitespace between arguments and variables.

EPA-NG is a read placement tool, which is used to place input ASVs into the reference tree.


Cheers,

Gavin

**Comment by jspychalla** [comment]
Hi, 
Thank you so much. I am really new to this. As you said it was not recognizing the path as a path. --ref_dir should be the appropriate flag right? I exited out of the terminal window and now it's not even recognize the place_seqs.py command. I am in the correct folder though. 


jamiespychalla@Jamies-MBP picrust2 % place_seqs.py -s study_seqs.fna -o/--out_tree--ref_dir default_files/fungi/fungi_ITS
zsh: command not found: place_seqs.py
(base) jamiespychalla@Jamies-MBP picrust2 % ls
MinPath			default_files		place_seqs.py
Rscripts		fungi_ITS		study_seqs.biom
__init__.py		metagenome_pipeline.py	study_seqs.fna
__pycache__		pathway_pipeline.py	util.py
default.py		pipeline.py		wrap_hsp.py

**Comment by gavinmdouglas** [comment]
Hi there,

It looks like you are confused about the $PATH variable in linux, and how to call local files vs those in your $PATH. I would suggest looking into tutorials on this topic.

In this case, you'll need to activate the conda environment where you installed picrust2 to be able to use it correctly.


Thanks,

Gavin

**Comment by jspychalla** [comment]
Hi thanks, 
I activated the conda environment when I had installed picrust2. I did not realize this was something I had to do each time I opened up the terminal. I will give the tutorials a look. 

Cheers, 
Jamie
