### ISSUE TITLE
Getting Reverse Complementary Seqs

### ISSUE THREAD

**Issue by jspychalla** [picrust/picrust2#290]
Hi there, 
   
When I run place_seqs.py -s grape_seqs.fna -o out.tre --ref_dir /Users/jamiespychalla/Desktop/picrust2/picrust2/default_files/fungi/fungi_ITS. 

I get the warning that my input sequences are poorly aligned to reference sequences and that 508 out of my 520 sequences will not be used downstream. 

1.  When I change --min_align to 0.75 and to 0.7 I get that 454 and 377 input sequences aligned poorly respectively. 

2.  I saw on a previous board that running picrust_pipeline.py seqtk seq - r outs.fa.format.fasta > otus_rc.fa can get the reverse complements which can help with alignment issues. 

3. I am running picrust step by step (place.seqs, hsp, etc. ) instead of just the of simply the picrust.pipeline.py, since I need to do fungi specific things at some steps.  How can I get the reverse complements running it step by step? 

Thank you so much for your time,
Jamie

**Comment by gavinmdouglas** [comment]
Het @jspychalla,

`seqtk` is a separate tool, so you can just run it outside of picrust2: https://github.com/lh3/seqtk. In other words, you can run it and then run the step-by-step approach that you want.


Cheers,

Gavin
