### ISSUE TITLE
PICRUSt2 Data and STAMP 

### ISSUE THREAD

**Issue by jspychalla** [picrust/picrust2#293]
I was able to visualize by PICRUSt2  unstratified pathway abundance  data with STAMP. Can I put this picrust2 output directly into STAMP? Or do I first need to perform so sort of normalization on the PICRUSt2 output data? 

Thank you for your time!

**Comment by gavinmdouglas** [comment]
Hi there,

I believe STAMP will automatically convert features per sample to relative abundances, meaning that you may not need to do a transformation. However, I would convert the data beforehand to relative abundances yourself, just so you know it's working with the data correctly.


Cheers,

Gavin
