### ISSUE TITLE
use --per_sequence_contrib but find some functions have empty 'norm_taxon_function_contrib'

### ISSUE THREAD

**Issue by ZhengXiaoxuan11542** [picrust/picrust2#294]
Hi, 

I used the '--per_sequence_contrib' command to get the importance of each sequence in the particular pathway and ran it successfully as follows: `pathway_pipeline.py -i pred_metagenome_unstrat.tsv.gz -o metacyc_pathways_out_per_seq -m ~/picrust2-2.4.2/picrust2/default_files/pathway_mapfiles/metacyc_path2rxn_struc_filt_pro.txt --per_sequence_contrib --per_sequence_function EC_predicted.tsv.gz --per_sequence_abun seqtab_norm.tsv.gz`.
II was provided with four files, which are ‘path_abun_contrib.tsv.gz’, 'path_abun_predictions.tsv.gz', 'path_abun_unstrat_per_seq.tsv.gz' and 'path_abun_unstrat.tsv.gz'.
However, when I opened the output file ‘path_abun_contrib.tsv.gz’, I found that the column 'norm_taxon_function_contrib' of some functions (e.g. A) was empty , all the relevant sequences under the A pathways did not have this value.
I'm wondering if this is because this could be a 'cross-feeding' pathway? Or am I focusing on the wrong file? Or is it a code error?

Thanks!

**Comment by gavinmdouglas** [comment]
Hi there,

There was an issue with that column that was fixed in v2.5.0: https://github.com/picrust/picrust2/releases/tag/v2.5.0

If you update to the latest version you should get the correct values for that column.


Cheers,

Gavin
