### ISSUE TITLE
Missing default_files

### ISSUE THREAD

**Issue by stevens-1** [picrust/picrust2#297]
Hello，

I need to use picrust2 flora function prediction, so I was carried out in accordance with the official suggest installation (https://github.com/picrust/picrust2/wiki/Installation), which is strange, whether from conda installation or added manually download the installation package, Always prompt missing default_files. But I noticed that all I installed was version 2.5.1. I have no way to solve this problem at present. 

This is the prompt for running pytest.
Error running this command:
run_sepp.py --tree /mnt/e/try/picrust2-2.5.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --raxml /mnt/e/try/picrust2-2.5.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.raxml_info --cpu 1 --molecule dna --outdir /tmp/tmpakj3c2x1/sepp_out -seed 297834 --alignment /mnt/e/try/picrust2-2.5.1/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --fragment /tmp/tmpakj3c2x1/study_seqs_filtered.fasta

Next I try to run my own data：
![Snap 2023-03-13 at 20 23 05](https://user-images.githubusercontent.com/77218948/224701271-a7720c8d-96ff-4064-b7db-2aabeed1cc5f.png)
I found that some of these missing files were not included in the installation package and therefore could not be added manually.

I hope I can get some help. Thank you

**Comment by gavinmdouglas** [comment]
Hi there,

I'm not sure what would be causing this issue, but you already tried downloading the default files manually (see: https://github.com/picrust/picrust2/tree/master/picrust2/default_files) and adding them to that location?

**Comment by stevens-1** [comment]
Yes. There are a total of five files in the package default_files/prokaryotic/pro_ref, which are: pro_ref.fna、pro_ref.hmm、pro_ref.model、pro_ref.raxml_info、pro_ref.tre. However the missing files pro_ref.fna.gz, pro_ref.fasta.gz, and pro_ref.fasta, which appear in the error message, are themselves non-existent.

I tried the following:
I suspected that there was an error in the default_files during installation, so I went to the file location and replaced the original file with the default_files in the installation package, but nothing changed.
I've tried it on a server and a PC, and I still can't get it to work.

What else can I do to try to solve this problem at the moment? I look forward to your reply!

**Comment by gavinmdouglas** [comment]
Hi @stevens-1, these files: `pro_ref.fna.gz, pro_ref.fasta.gz, and pro_ref.fasta` are alternative names for `pro_ref.fna`, and are not required.

Do you get the same error on both computers when you leave `-r` out? Also, with the `-r` option have you tried specifying the absolute path to where the files are located?

**Comment by stevens-1** [comment]
Thank you very much for your answer. After I added the -r parameter and specified the file path, I was able to run successfully！
