### ISSUE TITLE
Error with epa-ng

### ISSUE THREAD

**Issue by yliu3089** [picrust/picrust2#299]
Hi
  I am new to picrust2. I just tried to run through it according to your tutorial https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.1.4-beta) with v2.5.1. Everything works well until I started to run  `place_seqs.py -s ../seqs.fna -o out.tre -p 1 \ --intermediate intermediate/place_seqs`. It gives me the error message: 
`Error running this command`
`epa-ng --tree /home/yzl497/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa intermediate/place_seqs/ref_seqs_hmmalign.fasta --query intermediate/place_seqs/study_seqs_hmmalign.fasta --chunk-size 5000 -T 32 -m /home/yzl497/miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w intermediate/place_seqs/epa_out --filter-acc-lwr 0.99 --filter-max 100` . 
I tried to use -p 1, 4, 8, 16, 17, 32, but all gave me the same error message. Do you have any suggestions how to fix it? Thank you.

**Comment by gavinmdouglas** [comment]
That normally happens if you don't have sufficient RAM to run EPA-ng, which usually requires at least 16 GB of RAM. You can try using SEPP for placement (`--placement_tool sepp`) instead, which uses less memory.
