### ISSUE TITLE
Error in running epa-ng

### ISSUE THREAD

**Issue by HWChang** [picrust/picrust2#301]
Hi!

Thank you for developing and maintaining picrust2.

I am trying to use picrust2 on our server and running into the following error message:
epa-ng --tree /picrust2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa /storage1/fs1/mcolonna/Active/HWChang/IL22BP/intermediate/place_seqs/ref_seqs_hmmalign.fasta --query /storage1/fs1/mcolonna/Active/HWChang/IL22BP/intermediate/place_seqs/study_seqs_hmmalign.fasta --chunk-size 5000 -T 1 -m /picrust2/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w /storage1/fs1/mcolonna/Active/HWChang/IL22BP/intermediate/place_seqs/epa_out --filter-acc-lwr 0.99 --filter-max 100

The way I try to installed picrust2 is by using docker with the following command:
bsub -Is -G mcolonna -M 32GB -a 'docker(biomehub/picrust2)' /bin/bash

Then I try to run picrust2 with the following command when I get the error message:
place_seqs.py -s /storage1/fs1/mcolonna/Active/HWChang/IL22BP/IL22BP_asv_seq_mod.fna -o /storage1/fs1/mcolonna/Active/HWChang/IL22BP/picrust2_out/out.tre --intermediate /storage1/fs1/mcolonna/Active/HWChang/IL22BP/intermediate/place_seqs

For troubleshooting the problem, I try the  
(1) check the intermediate file stored under "/storage1/fs1/mcolonna/Active/HWChang/IL22BP/intermediate/place_seqs/epa_out"
I can the both epa_info.log and epa_result.jplace. There is on obvious error message in "epa_info.log". But the file size of epa_result.jplace is zero

(2) use TEPP instead
I ran
place_seqs.py -s /storage1/fs1/mcolonna/Active/HWChang/IL22BP/IL22BP_asv_seq_mod.fna -o /storage1/fs1/mcolonna/Active/HWChang/IL22BP/picrust2_out/out.tre --intermediate /storage1/fs1/mcolonna/Active/HWChang/IL22BP/intermediate/place_seqs -t sepp

But I received the following the error message:
usage: place_seqs.py [-h] -s PATH [-r PATH] -o PATH [-p PROCESSES]
                     [--intermediate PATH] [--chunk_size CHUNK_SIZE]
                     [--print_cmds] [-v]
place_seqs.py: error: unrecognized arguments: -t sepp

I felt like I missed something obvious. I would be appreciated it if you could point me in the right direction.

**Comment by gavinmdouglas** [comment]
Hi there,

What version are you using? Please make sure you're using the latest version -- that option wasn't present a few versions ago.


Gavin

**Comment by HWChang** [comment]
Hi Gavin, 

Thank you so much for the reply. It was the versioning issue. I change to another docker imagine that has a more recent version of the PICRUSt2 and it works.

Thanks!
