### ISSUE TITLE
what is the mean of the column name“taxon_rel_abun/genome_function_count/taxon_function_abun/taxon_rel_function_abun” in the    KEGG_pathways_out/path_abun_contrib.tsv.gz/path_abun_contrib.tsv

### ISSUE THREAD

**Issue by liulanzhou** [picrust/picrust2#303]
HI, CAN YOU HELP ME ?what is the mean of the column name“taxon_rel_abun/genome_function_count/taxon_function_abun/taxon_rel_function_abun” in the    KEGG_pathways_out/path_abun_contrib.tsv.gz/path_abun_contrib.tsv?

THANKS

**Comment by gavinmdouglas** [comment]
Hi there, 

Did you see the definitions of those columns in this tutorial? 

https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.5.2)#generate-metagenome-predictions


Cheers,

Gavin
