### ISSUE TITLE
add_descriptions.py does not work for stratified file

### ISSUE THREAD

**Issue by mammerlin** [picrust/picrust2#305]
Hi, 
I generate the stratified table by using this command,
picrust2_pipeline.py -s ASV.fasta  -i ASV.csv --stratified --per_sequence_contrib --processes 36 -o ASV_per_sequence_contrib 

By using add_descriptions.py, description can be added into unstratified file, but not stratified (contribution) file.

add_descriptions.py   -i KO_metagenome_out/pred_metagenome_unstrat.tsv.gz   -m METACYC   -o KO_metagenome_out/pred_metagenome_unstrat_descrip.tsv.gz
add_descriptions.py   -i KO_metagenome_out/pred_metagenome_contrib.tsv.gz   -m METACYC   -o KO_metagenome_out/pred_metagenome_contrib.tsv.gz_descrip.tsv.gz

The differenece between these two files is that path_abun_contrib.tsv.gz has an extra column(=sample) in the first position.
After I move the column "function" to the first postion, add_descriptions.py works well.

I was wondering if you will fix this bug in next release version.

![image](https://user-images.githubusercontent.com/35716885/234744312-396f73db-d394-447e-a9b3-0cd00227dc44.png)

**Comment by gavinmdouglas** [comment]
Thanks for pointing this out! I personally do not like have redundant information in the same file, and would want the description for each function in a separate map-file rather than repeated for each instance of the function id in a file, which unnecessarily increases the file size (i.e., I would rather just read in the map-files here separately: https://github.com/picrust/picrust2/tree/master/picrust2/default_files/description_mapfiles). However, I will consider at least clarifying this in the next release, or making the change you suggest.


Cheers,

Gavin

**Comment by mammerlin** [comment]
> Thanks for pointing this out! I personally do not like have redundant information in the same file, and would want the description for each function in a separate map-file rather than repeated for each instance of the function id in a file, which unnecessarily increases the file size (i.e., I would rather just read in the map-files here separately: https://github.com/picrust/picrust2/tree/master/picrust2/default_files/description_mapfiles). However, I will consider at least clarifying this in the next release, or making the change you suggest.
> 
> Cheers,
> 
> Gavin

Hi Gavin,
Thank you for the quickly reply.
As a data analyst, I agree with your opinion. I did imported the description_mapfile and merged it with pred_metagenome_contrib.tsv.gz_descrip.tsv.gz in R for downstream analysis.
I am pointing this out because I would like to introduce this excellent tool to people who are not familiar with programming. It would be better to reduce the steps to generate the final file. Thank you for considering my suggestion.

Regards,
mammer
