### ISSUE TITLE
Question about Taxonomic info

### ISSUE THREAD

**Issue by 21312zhy** [picrust/picrust2#306]
Hi, 

I noticed that some of my ASVs in the output files did not have taxonomic info when aligned to SILVA database but they did get the functional prediction, so I would like to know if it's possible to retrieve the reference genome info of the aligned ASVs? Or do you have other suggestions for retrieving the taxonomic info of these ASVs? Thank you!

Best,

**Comment by gavinmdouglas** [comment]
Hey there,

I would not recommend this, as this approach has not been validated and would not be comparable to standard taxonomic classifications in the field. However, if you are determined, you could look at the ‘out.tre’ file (described here: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.5.2)#place-reads-into-reference-tree), which contains the query ASVs in the same tree as the reference genomes. You could parse that tree to see the genome id that is closest in branch length to your query ASV(s) of interest. However, it would be easier to run a BLASTn approach (and exclude uncultured database sequences) if you just want to see what known taxon is the best hit (although again this would have to be validated in some way if you wanted to use a hard identity cut-off, and would be hard to compare with standard methods in the field).


Cheers,

Gavin

**Comment by 21312zhy** [comment]
Hi Gavin, thank you for the reply! Looks like blastn will be the quick solution. Appreciate your help!

Best,
