### ISSUE TITLE
Command error about picrust2 ?

### ISSUE THREAD

**Issue by linshizuowei** [picrust/picrust2#307]
Hi, when I use  picrust2, seems like thers is an error from gappa, error info described as below:
"
task: name=NFCORE_AMPLISEQ:AMPLISEQ:PICRUST (rep-seq.fasta,feature-table.tsv); work-dir=/data1/zhangjinxin/3/work/23/a845460a864d3d91c5183cd7658a05
error [nextflow.exception.ProcessFailedException]: Process NFCORE_AMPLISEQ:AMPLISEQ:PICRUST (rep-seq.fasta,feature-table.tsv) terminated with an error exit status (1)
5月-15 07:51:04.640 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_AMPLISEQ:AMPLISEQ:PICRUST (rep-seq.fasta,feature-table.tsv)'

Caused by:
Process NFCORE_AMPLISEQ:AMPLISEQ:PICRUST (rep-seq.fasta,feature-table.tsv) terminated with an error exit status (1)

Command executed:

#If input is QIIME2 file, than (1) the first line and (2) the first character (#) of the second line need to be removed
if [ "QIIME2" == 'QIIME2' ]
then
tail -n +2 "feature-table.tsv" > "feature-table.tsv.tmp" && mv "feature-table.tsv.tmp" "feature-table.tsv"
fi

picrust2_pipeline.py
-t epa-ng --remove_intermediate
-s rep-seq.fasta
-i feature-table.tsv
-o all_output
-p 6
--in_traits EC,KO
--verbose

#Add descriptions to identifiers
add_descriptions.py -i all_output/EC_metagenome_out/pred_metagenome_unstrat.tsv.gz -m EC -o EC_pred_metagenome_unstrat_descrip.tsv
add_descriptions.py -i all_output/KO_metagenome_out/pred_metagenome_unstrat.tsv.gz -m KO -o KO_pred_metagenome_unstrat_descrip.tsv
add_descriptions.py -i all_output/pathways_out/path_abun_unstrat.tsv.gz -m METACYC -o METACYC_path_abun_unstrat_descrip.tsv

echo "This Picrust2 analysis is based on filtered reads from QIIME2" > "This Picrust2 analysis is based on filtered reads from QIIME2.txt"
echo -e "picrust -t epa-ng --remove_intermediate" > "picrust.args.txt"

cat <<-END_VERSIONS > versions.yml
"NFCORE_AMPLISEQ:AMPLISEQ:PICRUST":
python: $(python --version 2>&1 | sed 's/Python //g')
picrust2: $( picrust2_pipeline.py -v | sed -e "s/picrust2_pipeline.py //g" )
END_VERSIONS

Command exit status:
1

Command output:
INFO Time spent placing: 38s
INFO Elapsed Time: 52s

Invocation: gappa examine graft --jplace-path /tmp/tmp8uspczvl/epa_out/epa_result_parsed.jplace --fully-resolve --out-dir /tmp/tmp8uspczvl/epa_out
Command: gappa examine graft

Input:
--jplace-path /tmp/tmp8uspczvl/epa_out/epa_result_parsed.jplace

Settings:
--fully-resolve true
--name-prefix

Output:
--out-dir /tmp/tmp8uspczvl/epa_out
--file-prefix
--file-suffix

Newick Tree Output:
--newick-tree-quote-invalid-chars
false

Global Options:
--allow-file-overwriting false
--verbose false
--threads 88
--log-file

Run the following command to get the references that need to be cited:
gappa tools citation Czech2020-genesis-and-gappa

Started 2023-05-15 19:51:02

Found 1 jplace file

Finished 2023-05-15 19:51:02

Command error:
INFO Time spent placing: 38s
INFO Elapsed Time: 52s

Invocation: gappa examine graft --jplace-path /tmp/tmp8uspczvl/epa_out/epa_result_parsed.jplace --fully-resolve --out-dir /tmp/tmp8uspczvl/epa_out
Command: gappa examine graft

Input:
--jplace-path /tmp/tmp8uspczvl/epa_out/epa_result_parsed.jplace

Settings:
--fully-resolve true
--name-prefix

Output:
--out-dir /tmp/tmp8uspczvl/epa_out
--file-prefix
--file-suffix

Newick Tree Output:
--newick-tree-quote-invalid-chars
false

Global Options:
--allow-file-overwriting false
--verbose false
--threads 88
--log-file

Run the following command to get the references that need to be cited:
gappa tools citation Czech2020-genesis-and-gappa

Started 2023-05-15 19:51:02

Found 1 jplace file

Finished 2023-05-15 19:51:02
"

It seems that there is no detailed error message，Is this an error about gappa ?
any help would be greatly appreciated. Thank yo

**Comment by gavinmdouglas** [comment]
Hi there,

It's not clear to m what the issue is from that log, but this is partially
because it was run as a custom nextflow workflow. For troubleshooting it
would be better to run each command separately.


Cheers,

Gavin

**Comment by linshizuowei** [comment]
> 

ok , I will try to run each command separately for troubleshooting, thank you very much.
