### ISSUE TITLE
 How to use a custom KEGG database? 

### ISSUE THREAD

**Issue by BenWu1224** [picrust/picrust2#313]
Hello, I am a beginner in using Picrust2. I previously attempted to use the KEGG database but found out that it is now a paid service, so I abandoned the idea. However, I have recently obtained a legally obtained KEGG database through school funding, but it is apparent that the overall format is significantly different from the default MetaCyc database in the pathway_mapfile I have checked. The KEGG database I obtained mainly consists of ''ko.list'', which is a table linking pathways to KOs, and ''xxxx.conf'', which contains details within each pathway. I would like to ask if any experienced users have successfully converted this type of database into a usable format. Thank you all for your responses.

Note:  .conf  contains lots of 'circ (483,230) 4	/dbget-bin/www_bget?C00668	C00668 (alpha-D-Glucose 6-phosphate)', which is quite different from metacyc database.  And ko.list contains lots of ''path:ko00010	ko:K00138'' .

**Comment by gavinmdouglas** [comment]
Hi there,

You can see the pathway mapfile for the last openly available version of KEGG here: https://github.com/picrust/picrust2/blob/master/picrust2/default_files/pathway_mapfiles/KEGG_pathways_to_KO.tsv

So if you formatted your files in this format as well it should be straight-forward to plug into PICRUSt2.


Cheers,

Gavin
