### ISSUE TITLE
how long should full pipeline command run?

### ISSUE THREAD

**Issue by mayagabitzsch** [picrust/picrust2#316]
hello, I have a huge data set that I just started running through picrust2. I know that it will take a long time, but im curious about an actual estimate. its over 10,000. I started the program and the terminal says its on hmmalign. No issues so far thankfully. I am running it on my mac which does not have a big RAM and did p 1

**Comment by gavinmdouglas** [comment]
Hi there,

I believe the runtime should be a couple of hours at most if I am remembering correctly.

**Comment by R-Wright-1** [comment]
I am just closing this as it doesn't seem that there's an issue here. Please let me know if I need to reopen it.
