### ISSUE TITLE
de-novo clustered ASVs as input sequences in picrust2

### ISSUE THREAD

**Issue by scmicrosys** [picrust/picrust2#317]
Hello, 

I am looking for some recommendations regarding the usage of de-novo clustered ASVs as input sequences in picrust2. 

Many thanks, 
silviac

**Comment by gavinmdouglas** [comment]
Hi there,

The approach is actually agnostic to how the data is generated -- it just takes in a FASTA of 16S sequences so they can certainly be de novo clustered.

**Comment by R-Wright-1** [comment]
I am just closing this as it doesn't seem that there's an issue. Please let me know if it needs to be reopened.
