### ISSUE TITLE
3,751 input sequences aligned poorly to reference sequences and removed.

### ISSUE THREAD

**Issue by hereformore** [picrust/picrust2#318]
Is this normal? in total i have around 9,000 input sequences. I'm not sure if 3,751 being removed/aligning poorly means I am doing something wrong or if that level of filtering is normal? 

MY first time using picrust2, and wondering if I am inputing the data wrong or something?
```

(picrust2) picrust2_out_pipeline % place_seqs.py -s ../seqs.fna -o out.tre -p 1 \ 
              --intermediate intermediate/place_seqs
**Warning - 3751 input sequences aligned poorly to reference sequences** (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences). These input sequences will not be placed and will be excluded from downstream steps.
```

**Comment by gavinmdouglas** [comment]
Hi there,

You can check out this related FAQ response, which might help: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#why-am-i-getting-the-error-stopping---all-x-input-sequences-aligned-poorly-to-reference-sequences 

That does seem like a red-flag that so many sequences are thrown out, so perhaps there is an issue with the headers for those sequences.

**Comment by R-Wright-1** [comment]
I am just closing this as there hasn't been any follow-up for a while. Please let me know if it needs to be reopened.
