### ISSUE TITLE
hsp.py verbosity

### ISSUE THREAD

**Issue by xvazquezc** [picrust/picrust2#32]
Hi there,

Would it be a possible to add a verbose option, a progress indicator or something along these lines? Right now `hsp.py` is completely silent and it does not write on the output location until it finishes, so it's hard to know if it's even running, esp. when I do it remotely on a server as I can't at least hear the computer.

Cheers

**Comment by gavinmdouglas** [comment]
This is a good suggestion! I'll add it as a request.

**Comment by gavinmdouglas** [comment]
I don't think this is doable unfortunately since most of the computation time is outside of PICRUSt2 so I'm closing this for now.
