### ISSUE TITLE
Issue with using picrust2 pipeline for ITS sequences

### ISSUE THREAD

**Issue by dixi06** [picrust/picrust2#322]
I am new to  pricrust2.  I used the following code for fungi ITS sequences and get this error. Please let me know what is wrong?

 picrust2_pipeline.py -s rep-seq4.fasta -i asv_its2_picrust.txt -o picrustout_Its2 -p 1 -r /home/AAFC-AAC/modid/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/fungi/fungi_ITS
Warning - non-default reference files specified with default pathway mapfile of prokaryote-specific MetaCyc pathways (--pathway_map option). This usage may be unintended.
Warning - 5586 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences). These input sequences will not be placed and will be excluded from downstream steps. 

Error running this command:
hsp.py --tree picrustout_Its2/out.tre --output picrustout_Its2/marker_predicted_and_nsti.tsv.gz --observed_trait_table /home/AAFC-AAC/modid/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/16S.txt.gz --hsp_method mp --edge_exponent 0.5 --seed 100 --calculate_NSTI --processes 1

Standard error of the above failed command:

Error running this command:
Rscript /home/AAFC-AAC/modid/miniconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/Rscripts/castor_hsp.R picrustout_Its2/out.tre /scratch/tmpskpeal0m/subset_tab_0 mp 0.5 FALSE FALSE /scratch/tmpe0vi_9bb/predicted_counts.txt /scratch/tmpe0vi_9bb/predicted_ci.txt 100

Standard error of the above failed command:
Error: None of the reference ids within the function abundance table are found within the input tree. This can occur when malformed or mismatched custom reference files are used.
Execution halted

**Comment by gavinmdouglas** [comment]
Hi there,

You can see that at the hsp.py step that you're pointing to the 16S-linked function table. Make sure that you change the appropriate parameters, as described here: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-run-a-custom-or-non-default-database-such-as-the-fungi-18s-and-its-databases

Please also note the warning in that FAQ answer about the ITS predictions!


Cheers,

Gavin

**Comment by R-Wright-1** [comment]
I am just closing this issue as there hasn't been any follow-up for a while. Please let me know if this needs to be reopened.
