### ISSUE TITLE
metagenome_pipeline.py  - flag to reduce amount of memory used

### ISSUE THREAD

**Issue by RachBioHaz** [picrust/picrust2#323]
HI, is it at all possible to add a flag to set batch size to process data when running PICRUSt locally?  I'm running picrust2 and until recently I was able to process my data without issue. Now generating metagenome predictions (metagenome_pipeline.py) for KO  data is so memory intensive that the process is killed.

I am running PICRUSt in a conda environment set up in Windows (WSL2/Ubuntu) and have 32.0 GB  RAM (31.8 GB usable). 

Thanks

**Comment by R-Wright-1** [comment]
Hi there, I'm not sure about the possibilities of doing this in the future, however, I wanted to mention that if you don't need the standalone PICRUSt2 version for any particular functionality, then the memory requirements of the version run within QIIME2 are lower. Also, incase you are not already, it may be worth performing an initial prevalence/abundance filter to limit the number of ASVs that are going into the analysis.

**Comment by R-Wright-1** [comment]
I am just closing this issue as there hasn't been any follow-up for a while. Please let me know if this needs to be reopened.
