### ISSUE TITLE
PicRust2 Error : number of statistically significant pathways exceeds the database's query limit. 

### ISSUE THREAD

**Issue by sm-arosh** [picrust/picrust2#326]
Hello,
I was trying to use ggpicrust2 in order to assess differentially abundant pathways predicted by picryst. It all ran fine and gave this error in the end. I'm attaching the files I used and hoping that someone can assist me on how to solve this.
![PicRust2_query](https://github.com/picrust/picrust2/assets/146560092/815a069a-5aab-4e9a-a8c3-b416b0af8595)
I couldn't find any parameter to increase the p-value to 0.01, so I'm lost on how to overcome this. I'm adding the links to the files that I used and also the code.
ko : https://drive.google.com/file/d/1UBDAXcxRg_ypo2JjfVY4nAAP9fW4g2E2/view?usp=sharing
metadata: https://drive.google.com/file/d/1swls-F91PiHfqsnjqIJQ7H2MpqTlVz7l/view?usp=sharing

Code:
kegg_abundance <- "feature-table-ko-new.csv"
metadata <- read_tsv("metadata_final.tsv")
results_file_input <- ggpicrust2(file = kegg_abundance,
                                 metadata = metadata,
                                 group = "Diabetes_typ",
                                 pathway = "KO",
                                 daa_method = "Maaslin2",
                                 ko_to_kegg = TRUE,
                                 p.adjust = "fdr",
                                 order = "pathway_class",
                                 p_values_bar = TRUE,
                                 #reference = "ND",
                                 x_lab = "pathway_name")

**Comment by sm-arosh** [comment]
#Update:
I was able to run LinDA using-
ko_abundance <- "feature-table-ko.tsv"
kegg_abundance <- ko2kegg_abundance(file = ko_abundance)
but still kind of same error with no annotated pathway in the table.
![Picrustq3](https://github.com/picrust/picrust2/assets/146560092/543a6ce7-f270-4a9d-9518-6640a1bdc1b0)
![Picrustq4](https://github.com/picrust/picrust2/assets/146560092/6a21e40d-e2be-4237-84fe-9e1e46dc2f25)
![Picrustq-sig](https://github.com/picrust/picrust2/assets/146560092/9f4d919e-e213-4acf-8927-ad051ad15717)

**Comment by R-Wright-1** [comment]
I'm afraid that I'm not familiar with ggpicrust2 as it was made by different developers and I haven't personally used it. You could try asking this question in their github page [here](https://github.com/cafferychen777/ggpicrust2)?

**Comment by cafferychen777** [comment]
Hello,

Firstly, I would like to extend my gratitude to the PICRUSt2 developer and maintainers @R-Wright-1 for their hard work on the tool and for pointing you to the right direction.

@sm-arosh,
Thank you for reaching out with your concern. I understand the error you've encountered while using ggpicrust2. To help address this, I'd recommend you follow the troubleshooting workflow provided in the ggpicrust2 documentation. You can find it here: [https://github.com/cafferychen777/ggpicrust2#if-an-error-occurs-with-ggpicrust2-please-use-the-following-workflow](https://github.com/cafferychen777/ggpicrust2#if-an-error-occurs-with-ggpicrust2-please-use-the-following-workflow).

After trying the suggested workflow, if the issue persists, please let me know and provide more details if possible. I'm here to assist you.

Best regards,

Chen YANG

**Comment by Valencia-0302** [comment]
> Hello, I was trying to use ggpicrust2 in order to assess differentially abundant pathways predicted by picryst. It all ran fine and gave this error in the end. I'm attaching the files I used and hoping that someone can assist me on how to solve this. ![PicRust2_query](https://private-user-images.githubusercontent.com/146560092/275405271-815a069a-5aab-4e9a-a8c3-b416b0af8595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwODg5NTcsIm5iZiI6MTcwMjA4ODY1NywicGF0aCI6Ii8xNDY1NjAwOTIvMjc1NDA1MjcxLTgxNWEwNjlhLTVhYWItNGU5YS1hOGMzLWI0MTZiMGFmODU5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwOVQwMjI0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDRmZGYxMDg2NGNlOWEwZTY4NmU3YWJlOWZkODlkMTlkNTY2MDBhZjNmMTZiMTVhNDlhMzQyYTU0NDcxNWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9ucCzY010Ep8vsm9gMMaTeI2czDBOO3SrnaMQTVF52Q) I couldn't find any parameter to increase the p-value to 0.01, so I'm lost on how to overcome this. I'm adding the links to the files that I used and also the code. ko : https://drive.google.com/file/d/1UBDAXcxRg_ypo2JjfVY4nAAP9fW4g2E2/view?usp=sharing metadata: https://drive.google.com/file/d/1swls-F91PiHfqsnjqIJQ7H2MpqTlVz7l/view?usp=sharing
> 
> Code: kegg_abundance <- "feature-table-ko-new.csv" metadata <- read_tsv("metadata_final.tsv") results_file_input <- ggpicrust2(file = kegg_abundance, metadata = metadata, group = "Diabetes_typ", pathway = "KO", daa_method = "Maaslin2", ko_to_kegg = TRUE, p.adjust = "fdr", order = "pathway_class", p_values_bar = TRUE, #reference = "ND", x_lab = "pathway_name")

Hey
Excuse me, have you solved this problem?

**Comment by R-Wright-1** [comment]
I'm just closing this issue here as it related to ggpicrust2 and not PICRUSt2. Thanks @cafferychen777 for keeping an eye on here, too!
