### ISSUE TITLE
picrust2 installation

### ISSUE THREAD

**Issue by WillErickson1** [picrust/picrust2#327]
Hello can I install picrust2 using this command :conda create -n picrust2 -c bioconda -c conda-forge picrust
2=2.5.2 instead of mamba create -n picrust2 -c bioconda -c conda-forge picrust2=2.5.2
because I don't have mamba on my linux. does the installation of picrust2 using  conda takes too much time ?

**Comment by R-Wright-1** [comment]
You don't necessarily need to install mamba, and could use the conda command instead - as mentioned on the install page, though, it may take a long time. If you're trying to avoid using mamba then you could also try using the install from source instructions and replacing mamba with conda there.

**Comment by lingvv** [comment]
Hello! If your installation process is referring to this
https://github.com/picrust/picrust2/wiki/Installation 

You may replace `mamba` with `conda` instead

The original code:
`mamba env create -f picrust2-env.yaml`

Replacement Code:
`conda env create -n picrust2 --file picrust2-env.yaml`

Hope this helps!

**Comment by R-Wright-1** [comment]
I am just closing this issue as there hasn't been any follow-up for a while. Please let me know if this needs to be reopened.
