### ISSUE TITLE
picrust2_outputs

### ISSUE THREAD

**Issue by WillErickson1** [picrust/picrust2#328]
Hello, I hope you could help me 
I runned this command line : picrust2_pipeline.py -s study_seqs.fna -i study_seqs.biom -o picrust2_out_pipeline -p 1
![image](https://github.com/picrust/picrust2/assets/147614812/e7657a51-bd25-4519-8ffb-fbe4b7943060)

my question is where I can find metacyc abundance output files ? does it in pathways_out ?

**Comment by R-Wright-1** [comment]
Hi there, yes, the metacyc abundance output file is `pathways_out/path_abun_unstrat.tsv.gz`. You can see the answers to some questions about the pathway abundances [here](https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#pathway-level-inference-1).

**Comment by R-Wright-1** [comment]
I am just closing this issue as there hasn't been any follow-up for a while. Please let me know if this needs to be reopened.
