### ISSUE TITLE
Installing problem into MacBook Air m1 terminal

### ISSUE THREAD

**Issue by kumarrupin** [picrust/picrust2#331]
I have tried from both bioconda and from source both way are not working for me
[Screenshot 2023-11-09 at 11.39.20 AM.pdf](https://github.com/picrust/picrust2/files/13305073/Screenshot.2023-11-09.at.11.39.20.AM.pdf)
[Screenshot 2023-11-09 at 12.19.02 PM.pdf](https://github.com/picrust/picrust2/files/13305077/Screenshot.2023-11-09.at.12.19.02.PM.pdf)

**Comment by kumarrupin** [comment]
This error come while installing from bioconda


(base) rupin@RUPINs-MacBook-Air ~ % conda create -n picrust2 -6 bioconda - conda-forge picrust2=2.5.2
[Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes. Press CTRL-C to abort. failed
PackagesNotFoundError: The following packages are not available from current channels:
- hmmer[version='>=3.1b2, ≤3.2.1'1
Current channels:
- https://conda.anaconda.org/bioconda/osx-arm64
- https://conda.anaconda.org/bioconda/noarch
- https://conda.anaconda.org/conda-forge/osx-arm64
- https://conda.anaconda.org/conda-forge/noarch
https://repo.anaconda.com/pkgs/main/osx-arm64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/osx-arm64
https://repo.anaconda.com/pkgs/r/noarch
To search for alternate channels that may provide the conda package you're looking for, navigate to
https://anaconda.org
and use the search bar at the top of the page.
(base) rupin@RUPINs-MacBook-Air ~



this error comes while installing from source


(base) rupin@RUPINs-MacBook-Air picrust2-2.5.2 % conda env create -f picrust2-envyam]
conda activate picrust2 pip install -editable •
Collecting package metadata (repodata.json): done
Solving environment: failed
ResolvePackageNotFound:
- biom-format[version='>=2.1.10' ]
- r-castor[version='>=1.7.2']
- epa-ng=0.3.8
- gappa=0.8.0
- hmmer[ version='>=3.1b2, <=3.2.1']
- sepp=4.3.10
Focan ast a tEsoverable environments water com into ens?.
You can list all discoverable environments with
Obtaining file:///Users/rupin/picrust2-2.5.2
Preparing metadata (setup. py) ... done
Requirement already satisfied: numpy in /Users/rupin/miniconda3/lib/python3.11/site-packages (from PICRUSt2==2.5.2) (1.26.1)
Requirement already satisfied: h5py in /Users/rupin/miniconda3/lib/python3.11/site-packages (from PICRUSt2==2.5.2) (3.10.0)
Requirement already satisfied: joblib in /Users/rupin/miniconda3/lib/python3.11/site-packages (from PICRUSt2==2.5.2) (1.3.2)
Requirement already satisfied: biom-format in /Users/rupin/miniconda3/lib/python3.11/site-packages (from PICRUSt2==2.5.2) (2.1.15)
Requirement already satisfied: click in /Users/rupin/miniconda3/lib/python3.11/site-packages (from biom-format=>PICRUSt2==2.5.2) (8.1.7)
Requirement already satisfied: scipy>=1.3.1 in /Users/rupin/miniconda3/lib/python3.11/site-packages (from biom-format->PICRUSt2==2.5.2) (1.11.3)
Requirement already satisfied: pandas>=0.20.0 in /Users/rupin/miniconda3/lib/python3.11/site-packages (from biom-format->PICRUSt2==2.5.2) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rupin/miniconda3/lib/python3.11/site-packages (from pandas>=0.20.0->biom-format->PICRUSt2==2.5.2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/rupin/miniconda3/lib/python3.11/site-packages (from pandas>=0.20.0->biom-format->PICRUSt2==2.5.2) (2023.3. post1)
Requirement already satisfied: tzdata>=2022.1 in /Users/rupin/miniconda3/lib/python3.11/site-packages (from pandas>=0.20.0->biom-format->PICRUSt2==2.5.2) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/rupin/miniconda3/lib/python3.11/site-packages (from python-dateuti1>=2.8.2-›pandas>=0.20.0->biom-format->PICRUSt2==2.5.2) (1.16.0)
Installing collected packages: PICRUSt2
Attempting uninstall: PICRUSt2
Found existing installation: PICRUSt2 2.5.2
Uninstalling PICRUSt2-2.5.2:
Successfully uninstalled PICRUSt2-2.5.2
Running setup.py develop for PICRUSt2
Successfully installed PICRUSt2-2.5.2 (base) rupin@RUPINs-MacBook-Air picrust2-2.5.2

**Comment by R-Wright-1** [comment]
Hi there, based on your second install from source and screenshot, it says that it is successfully installed. Are you sure that it's not installed?

**Comment by kumarrupin** [comment]
**Hi, but when i am activating it continuously showing -**

rupin@RUPINs-MacBook-Air picrust2-2.5.2 % conda activate picrust2

EnvironmentNameNotFound: Could not find conda environment: picrust2
You can list all discoverable environments with `conda info --envs`.






**even not found in conda info-----**
rupin@RUPINs-MacBook-Air picrust2-2.5.2 % conda info --envs
# conda environments:
#
base                     /Users/rupin/miniconda3
qiime2-2023.7            /Users/rupin/miniconda3/envs/qiime2-2023.7
qiime2-amplicon-2023.9     /Users/rupin/miniconda3/envs/qiime2-amplicon-2023.9
qiime2-shotgun-2023.9     /Users/rupin/miniconda3/envs/qiime2-shotgun-2023.9
qiime2-tiny-2023.9       /Users/rupin/miniconda3/envs/qiime2-tiny-2023.9

**Comment by kumarrupin** [comment]
By this command **mamba env create -f picrust2-env.yaml
conda activate picrust2
pip install --editable**    in between it showing



Could not solve for environment specs
The following packages are incompatible
├─ biom-format >=2.1.10  does not exist (perhaps a typo or a missing channel);
├─ epa-ng 0.3.8**  does not exist (perhaps a typo or a missing channel);
├─ gappa 0.8.0**  does not exist (perhaps a typo or a missing channel);
├─ hmmer >=3.1b2,<=3.2.1  does not exist (perhaps a typo or a missing channel);
├─ r-castor >=1.7.2  does not exist (perhaps a typo or a missing channel);
└─ sepp 4.3.10**  does not exist (perhaps a typo or a missing channel).

**Comment by blakemycake** [comment]
I was having a similar issue installing picrust2 on my macbook M1. I was able to resolve the issue by running my terminal in Rosetta, re-installing microconda, and following the instructions to download from source using the command below instead of the mamba command to create the environment:

CONDA_SUBDIR=osx-64 conda env create -f picrust2-env.yaml

**Comment by kumarrupin** [comment]
thanks ,it is installed  by your command. But after pytest command to test it it showing some file or directory are not found.

[screentshot.pdf](https://github.com/picrust/picrust2/files/13400027/screentshot.pdf)

../miniconda3/envs/picrust2/lib/python3.8/subprocess.py:1720: FileNotFoundError
====================================== short test summary info =======================================
FAILED tests/test_place_seqs.py::place_seqs_tests::test_run_place_seqs_pipeline_sepp - SystemExit: 1
FAILED tests/test_workflow.py::workflow_test::test_full_pipeline_tsv - FileNotFoundError: [Errno 2] No such file or directory: 'place_seqs.py'
FAILED tests/test_workflow.py::workflow_test::test_help_calls - FileNotFoundError: [Errno 2] No such file or directory: 'add_descriptions.py'
FAILED tests/test_workflow.py::workflow_test::test_picrust2_pipeline_script - FileNotFoundError: [Errno 2] No such file or directory: 'picrust2_pipeline.py'
FAILED tests/test_workflow.py::workflow_test::test_picrust2_pipeline_script_per_seq_contrib_strat - FileNotFoundError: [Errno 2] No such file or directory: 'picrust2_pipeline.py'
FAILED tests/test_workflow.py::workflow_test::test_picrust2_pipeline_script_per_seq_contrib_strat_skip_norm - FileNotFoundError: [Errno 2] No such file or directory: 'picrust2_pipeline.py'
============================== 6 failed, 55 passed in 93.27s (0:01:33) ===============================

**Comment by blakemycake** [comment]
Did you change your terminal so it's running in Rosetta? I think I had the same error when I first tried to install it using the command above. I'm not 100% sure why that happened but I believe uninstalling microconda and reinstalling it when running the terminal in Rosetta fixed the issue. You could also try using miniforge instead of microconda!

**Comment by R-Wright-1** [comment]
Apologies for my slow response on this. I've added what worked for me in here: #314 
Could you see if that works?

**Comment by R-Wright-1** [comment]
I'm just closing this issue as there hasn't been any further response.
