### ISSUE TITLE
help please : Error running picrust2_pipeline.py

### ISSUE THREAD

**Issue by saassli21** [picrust/picrust2#332]
@gavinmdouglas 
Hello,
I runned the script : **picrust2_pipeline.py** on 2 different datasets. On the first dataset ( fasta + biom) the script worked and I generated picrust2_out_pipeline folder .
But when I test it on my second dataset (genrated using the same qiime2 pipeline as the first dataset) I only generate this file : 
![image](https://github.com/picrust/picrust2/assets/131655435/367ea3d0-df85-452f-9114-a155dcd9f0ae)

and I have this error : 

**Error running this command:
place_seqs.py --study_fasta home/input_dataset/ASV-sequences_exp2.fasta --ref_dir /opt/conda/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref --out_tree picrust2_out_pipeline/out.tre --processes 4 --intermediate picrust2_out_pipeline/intermediate/place_seqs --min_align 0.8 --chunk_size 5000 --placement_tool epa-ng

Standard error of the above failed command:
Stopping - all 1633 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences).**

What I should do in this case ? how to solve the problem please ( my input files were generated using qiime2 pipeline : type of sequencing is single end and read size to conserve after quality PHRED check is 250)
- I don't have RAM issue or package version problems as in #75

**Comment by R-Wright-1** [comment]
Hi there, 
Have you checked [this FAQ answer](https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#why-am-i-getting-the-error-stopping---all-x-input-sequences-aligned-poorly-to-reference-sequences)? Are the sequences that you're trying to use definitely 16S sequences?

**Comment by R-Wright-1** [comment]
I'm just closing this issue as there hasn't been any follow-up for a while. Please let me know if it needs to be reopened.
