### ISSUE TITLE
running picrust2 on ITS

### ISSUE THREAD

**Issue by ScarlettPegany** [picrust/picrust2#336]
Hello,
I have previously used your tool on 16S, and it was truly fascinating. Currently, I am working with ITS and would like to incorporate picrust2 into my analysis.
I have already reviewed the FAQ section related to this topic 

![image](https://github.com/picrust/picrust2/assets/149370431/05c8160d-6a18-4936-91bf-fea064db8b5e)

, but I am still struggling to understand the specific changes I need to make. 
Currently, I am running picrust2_pipeline.py directly for 16S with the following command: (picrust2_pipeline.py -s study_seqs.fna -i study_seqs.biom -o picrust2_out_pipeline -p 1
)  . 
For ITS, I believe I need to modify the command to generate EC_metagenome_out 
I think  I need to add the following options to the previous command line: --custom_trait_tables, --marker_gene_table, and --reaction_func. However, I'm uncertain about what to replace XXXXX with in each case:

**picrust2_pipeline.py -s study_seqs.fna -i study_seqs.biom -o picrust2_out_pipeline -p 1 --custom_trait_tables XXXXXXX --marker_gene_table XXXXX --reaction_func XXXX**
and maybe adding this -r picrust2/picrust2/default_files/fungi/fungi_ITS ? 

**I tried this command based on this post #101 but I don't know if it's correct or not** 

picrust2_pipeline.py -s /lab/user/data/ubiome_local_test/picrust_ITS_mock_input/ASV-sequences.fasta -i /lab/user/data/ubiome_local_test/picrust_ITS_mock_input/feature-table.biom -o picrust2_out_pipeline -p 4 --custom_trait_tables /opt/conda/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/fungi/ec_ITS_counts.txt.gz --min_reads 1 -r /opt/conda/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/fungi/fungi_ITS --marker_gene_table /opt/conda/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/fungi/ITS_counts.txt.gz --pathway_map /opt/conda/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/pathway_mapfiles/metacyc_path2rxn_struc_filt_fungi_present.txt --reaction_func /opt/conda/envs/picrust2/lib/python3.8/site-packages/picrust2/default_files/fungi/ec_ITS_counts.txt.gz

**-Is there a way to generate KO_metagenome_out file as it's the case for 16s ?** 
![image](https://github.com/picrust/picrust2/assets/149370431/f2fa94fc-2c13-48d2-9b1b-8c1fc246e2c5)

I really hope that someone can help me with this :)

**Comment by R-Wright-1** [comment]
Hi there,

Yes, it looks like you've got that correctly for running PICRUSt2 with ITS. I'm afraid that there isn't currently a file that maps the fungal genomes to KO's as there is for 16S.

Best wishes,
Robyn

**Comment by R-Wright-1** [comment]
I'm just closing this issue as it seems that it's been resolved. Please let me know if it needs to be reopened.
