### ISSUE TITLE
metagenome contributions analysis

### ISSUE THREAD

**Issue by gonzalofe** [picrust/picrust2#337]
Hello. I've successfully used MaAsLin2 to identify significant correlations between taxa and pathways across different groups.

Specifically, I'm interested in delving deeper into understanding which taxa contribute to certain pathways in the context of specific groups. I have the pathway abundance contributions file generated by PICRUSt2.

Could you provide guidance on the most appropriate statistical analyses or approaches to discern and interpret taxon-pathway associations within a defined group? I want to ensure the analysis accounts for potential confounding effects

**Comment by R-Wright-1** [comment]
Hi there,

I'm afraid that what you're asking about, there aren't really many well defined approaches to doing this; robust methods for this are something that we're actively working on as a group. With that said, I can give some advice.

First, I think that when you're diving into this, it's important to remember that PICRUSt2 generates predictions, it doesn't tell you for certain which functions are present in samples. What we have typically done with amplicon sequencing datasets is analyse them taxonomically (e.g. alpha/beta diversity and differential abundance of taxa using multiple differential abundance tools). You can then use the functional predictions from PICRUSt2 in a similar way (and just as you would analyse taxonomic data at ASV/genus/family level, you can analyse the functional data at different levels, too). It is typically the differentially abundant functions that we have then identified the taxa that they come from, e.g. [Fig. 4 of this paper](https://bmcoralhealth.biomedcentral.com/articles/10.1186/s12903-023-02911-5#Sec8) that I did the analysis for. This used [JarrVis](https://github.com/dhwanidesai/JarrVis), a tool that Dhwani, in our lab, is working on. 

You may also find it useful to look at [POMS](https://github.com/gavinmdouglas/POMS/wiki), a tool that Gavin developed more for metagenome data, but the approach may be of interest to you. 

There is also the [ggpicrust2 tool](https://github.com/cafferychen777/ggpicrust2) (not created or maintained by us) that I haven't personally used, but I believe has some suggestions for this.

Sorry I can't give a more definitive answer, hopefully this is helpful, though!

Robyn

**Comment by R-Wright-1** [comment]
I'm just closing this issue as there hasn't been any followup for a while and there wasn't any particular issue here. Please let me know if it needs to be reopened. Please also feel free to post in the [PICRUSt users google group](https://groups.google.com/g/picrust-users) - maybe someone else in there has other suggestions.
