### ISSUE TITLE
EPA-NG not working

### ISSUE THREAD

**Issue by arghya1611** [picrust/picrust2#34]
Hi
I installed picrust2 on a Ubuntu16.06 VBox a few days back and the EPA-NG step in the sequence placement is not working. The installation was carried out as instructed without a single error. Pytest ran in all greens. I ran place.seqs with print_cmds and this is the error i am getting: 

(picrust2-dev) arghya250@arghya250-VirtualBox:~/Apps/picrust2$ place_seqs.py -s example_files/tutorial.fna -o OUTPUT.tre --threads 10 --intermediate placement_working
papara called as:
papara -t /home/arghya250/Apps/picrust2/default_files/prokaryotic/img_centroid_16S_aligned.tree -s ref_seqs.phylip -q /home/arghya250/Apps/picrust2/example_files/tutorial.fna -j 10 -n out 
gap rate: 1503347 21163428
gap rate: 0.0710351
rate matrix: [2,2]((-0.0710351,0.0710351),(0.928965,-0.928965))
p: [2,2]((0.99324,0.00675989),(0.0884027,0.911597))
references container instantiated as: papara::references<pvec_pgap, sequence_model::tag_dna>
edges: 32885
scoring scheme: -3 -1 2 -3
papara_core version 2.5
start scoring, using 10 threads
thread 5: 1.22437 gncup/s
thread 6: 1.23993 gncup/s
thread 1: 1.28678 gncup/s
thread 4: 1.26158 gncup/s
thread 3: 1.34938 gncup/s
thread 9: 1.31181 gncup/s
thread 8: 1.28195 gncup/s
thread 0: 1.33646 gncup/s
thread 2: 1.3424 gncup/s
thread 7: 1.26382 gncup/s
scoring finished: 9.65413
sweep: 98658 -> 0
38.1369
generating best scoring alignments
SUCCESS 38.1369
INFO Converting given FASTA file to BFAST format...
INFO Resulting bfast file was written to: placement_working/epa_out/study_seqs_papara.fasta.bfast
INFO Selected: Output dir: placement_working/epa_out/
INFO Selected: Query file: placement_working/epa_out/study_seqs_papara.fasta.bfast
INFO Selected: Tree file: /home/arghya250/Apps/picrust2/default_files/prokaryotic/img_centroid_16S_aligned.tree
INFO Selected: Reference MSA: placement_working/ref_seqs_papara.fasta
INFO Selected: Specified model: GTR+G
INFO    Rate heterogeneity: GAMMA (4 cats, mean),  alpha: 1 (ML),  weights&rates: (0.25,0.136954) (0.25,0.476752) (0.25,1) (0.25,2.38629) 
        Base frequencies (ML): 0.25 0.25 0.25 0.25 
        Substitution rates (ML): 0.5 0.5 0.5 0.5 0.5 1
INFO Selected: Reading queries in chunks of: 5000
INFO Selected: Using threads: 10
INFO     ______ ____   ___           _   __ ______
        / ____// __ \ /   |         / | / // ____/
       / __/  / /_/ // /| | ______ /  |/ // / __  
      / /___ / ____// ___ |/_____// /|  // /_/ /  
     /_____//_/    /_/  |_|      /_/ |_/ \____/ (v0.2.1-beta)
INFO Number of ranks: 1
INFO Output file: placement_working/epa_out/epa_result.jplace
Error running this command:
epa-ng --tree /home/arghya250/Apps/picrust2/default_files/prokaryotic/img_centroid_16S_aligned.tree --ref-msa placement_working/ref_seqs_papara.fasta --query placement_working/epa_out/study_seqs_papara.fasta.bfast --chunk-size 5000 -T 10 -m GTR+G -w placement_working/epa_out

Whats going wrong here ? Please help.

**Comment by gavinmdouglas** [comment]
Hi there,

Are you using the version of EPA-NG that’s packaged in the “placement_tools” folder of the picrust2 rep?


Best,

Gavin

**Comment by arghya1611** [comment]
Hi,
Yes all prerequisite were installed using versions packaged in picrust2 repo as downloaded en block.
Best,
Arghya

**Comment by gavinmdouglas** [comment]
Hi again,

Sorry you're running into this issue. What's the error reported when you run the below command?

```
epa-ng --tree /home/arghya250/Apps/picrust2/default_files/prokaryotic/img_centroid_16S_aligned.tree --ref-msa placement_working/ref_seqs_papara.fasta --query placement_working/epa_out/study_seqs_papara.fasta.bfast --chunk-size 5000 -T 10 -m GTR+G -w placement_working/epa_out
```

**Comment by arghya1611** [comment]
Hi
I ran the epa-ng separately as you suggested. I am getting the following VBox error. It seems like a memory issue in VBOx. My Vbox has a memory of 7052 MB dedicated to it as well as 6 processors. I know the recommended memory for picrust2 is 16GB. Having said that, should such a small dataset require so much memory? 

 ![epa-ng_error](https://user-images.githubusercontent.com/34534484/43912825-05cbc59e-9c21-11e8-91f8-75af75338cdd.png)

**Comment by gavinmdouglas** [comment]
Hi again,

That command should take around 13 GB. The reason is that it's using the default reference tree and FASTA file, which are very large and take up a lot of memory when running EPA-NG. Sorry I can't be of more help, but currently I'm not sure how to decrease the memory usage without using different reference files.


Gavin
