### ISSUE TITLE
Assign general function from KEGG pathway in pathways_out 

### ISSUE THREAD

**Issue by Dirrrrty** [picrust/picrust2#343]
I have the pathway output from PICRUST2 but the pathways are the specific pathway names such as 'COA-PWY' and 'ARGORNPROST-PWY' but I want to summarise them by their general functions like carbon metabolism, nitrogen metabolism etc. Currently I am searching each pathway in metacyc and biocyc and then looking for them in KEGG but surely there is a faster way to do this? I thought maybe there is a function in PICRUST2 or a package that works in conjunction with it to assign these general functions?
Any help please :)

**Comment by R-Wright-1** [comment]
I'm afraid that I'm not personally aware of any way to do this, unless you can find a mapping file somewhere on the metacyc/biocyc website. I imagine that some of the issue could be pathways used for multiple general functions. You could try posting in the [Google group](https://groups.google.com/g/picrust-users) though - that will get more eyes on your question and maybe someone else has come up with a way to do this :)
