### ISSUE TITLE
Gene family abundances per ASV rather than per sample

### ISSUE THREAD

**Issue by antonkratz** [picrust/picrust2#345]
> A different approach would be to look at the predicted genomes of ASVs generated by the hidden-state prediction step (which represents the gene family abundances per ASV rather than per sample).

I am seeking gene family abundances per ASV rather than per sample. I ran my analysis using the wrapper script like this:

> picrust2_pipeline.py --stratified -i exported_table/feature-table.biom -s exported_seqs/dna-sequences.fasta -o picrust2_out_pipeline2 -p 1

Where can I find the the predicted genomes of ASVs generated by the hidden-state prediction step?

**Comment by R-Wright-1** [comment]
Hi there,

You can find the per ASV predictions in `EC_predicted.tsv` - this shows how many copies of each EC number are predicted to be in each genome. 

Robyn
