### ISSUE TITLE
complex definition effect on abundance calculation

### ISSUE THREAD

**Issue by danpal96** [picrust/picrust2#348]
According to the FAQ:

> The structure follows the same definition as that for Kegg modules. Each structure is a list (space-delimited) of items with a comma to indicate alternatives, a plus to indicate a complex, and a minus sign at the beginning of an item to indicate this is not a key item in the pathway.

What exactly is a complex when talking about reactions and what is the effect of defining a complex on the abundance calculation?

**Comment by R-Wright-1** [comment]
Hi there,

As these were developed by the KEGG and HUMAnN projects, I'll just direct you to the appropriate parts of their documentation [here](https://www.genome.jp/kegg/module.html) and [here](https://github.com/biobakery/humann). I'm going to close this as it is not an issue, but if you'd like to discuss further then please use the [picrust-users Google group](https://groups.google.com/g/picrust-users) to do so.
