### ISSUE TITLE
Please help for picrust2 tutorial: cannot download the data set

### ISSUE THREAD

**Issue by paiboon-aut** [picrust/picrust2#349]
I and my friends would like to learn how to analyze the function of 16S microbial profile data using picrust2.

We have tried to download the data set from this command in the tutorial
"wget  http://kronos.pharmacology.dal.ca/public_files/picrust/picrust2_tutorial_files/chemerin_16S.zip".

We cannot download the data set from the following command.
Moreover, when we tried to go to  "http://kronos.pharmacology.dal.ca/public_files/picrust/picrust2_tutorial_files/chemerin_16S.zip" the link is not found.

![image](https://github.com/picrust/picrust2/assets/105876792/9a85e299-4233-4d0a-a45d-4449b91d2d98)

Please help us with this issue

**Comment by okcomputer** [comment]
Just wondering has there been any progress on this? I was trying to go through the tutorial as well.

**Comment by Jorn-Bethke** [comment]
Same question, I also was trying to go through the tutorial. Will the data be available again?

Best regards.,
Jorn

**Comment by R-Wright-1** [comment]
Hi all, we've managed to get it fixed this afternoon, so it should be working again now. I'll look at creating a copy of the files somewhere else so that we can't run into this issue in the future. 
Robyn
