### ISSUE TITLE
Running picrust on full geomes

### ISSUE THREAD

**Issue by annotatebio** [picrust/picrust2#350]
Would it be feasible to attempt to run Picrust on the full reference assemblies and their abundances, not just ASVs, in order to get KEGG annotations? Could the full script be used for that, or only selected submodules of it?

Thanks in advance

**Comment by R-Wright-1** [comment]
Hi there, I'm not sure if I quite understand the question - could you explain a little more? Do you mean running PICRUSt on full genomes?

**Comment by annotatebio** [comment]
Yes, indeed what I meant is if it's possible to run PICRUSt on full genomes, to get KEGG pathways annotations :)

**Comment by R-Wright-1** [comment]
Theoretically you could run it with just the 16S gene, but if you have the full genome then I would recommend just annotating the genome - PICRUSt generates predictions of what is in a genome, but it isn't for annotation. I would recommend something like [Prokka](https://github.com/tseemann/prokka) or [MicrobeAnnotator](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03940-5) for that. I don't think I've personally used MicrobeAnnotator, but I've used Prokka and it's probably much easier to run than PICRUSt!
