### ISSUE TITLE
ERROR collecting picrust2-2.5.2/tests/test_hsp.py

### ISSUE THREAD

**Issue by UeenHuynh** [picrust/picrust2#351]
import file mismatch:                                     
imported module 'tests.test_hsp' has this __file__ attribute:
  /home/minouhuynh/picrust/picrust2/tests/test_hsp.py     
which is not the same as the test file we want to collect:
  /home/minouhuynh/picrust/picrust2-2.5.2/tests/test_hsp.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules                                                      
___________ ERROR collecting picrust2-2.5.2/tests/test_metagenome_pipeline.py ___________
import file mismatch:                                     
imported module 'tests.test_metagenome_pipeline' has this __file__ attribute:
  /home/minouhuynh/picrust/picrust2/tests/test_metagenome_pipeline.py
which is not the same as the test file we want to collect:
  /home/minouhuynh/picrust/picrust2-2.5.2/tests/test_metagenome_pipeline.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules                                                      
____________ ERROR collecting picrust2-2.5.2/tests/test_pathway_pipeline.py _____________
import file mismatch: 
imported module 'tests.test_pathway_pipeline' has this __file__ attribute:
  /home/minouhuynh/picrust/picrust2/tests/test_pathway_pipeline.py
which is not the same as the test file we want to collect:
  /home/minouhuynh/picrust/picrust2-2.5.2/tests/test_pathway_pipeline.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
_______________ ERROR collecting picrust2-2.5.2/tests/test_place_seqs.py ________________
import file mismatch:
imported module 'tests.test_place_seqs' has this __file__ attribute:
  /home/minouhuynh/picrust/picrust2/tests/test_place_seqs.py
which is not the same as the test file we want to collect:
  /home/minouhuynh/picrust/picrust2-2.5.2/tests/test_place_seqs.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
__________________ ERROR collecting picrust2-2.5.2/tests/test_util.py ___________________
import file mismatch:
imported module 'tests.test_util' has this __file__ attribute:
  /home/minouhuynh/picrust/picrust2/tests/test_util.py
which is not the same as the test file we want to collect:
  /home/minouhuynh/picrust/picrust2-2.5.2/tests/test_util.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
________________ ERROR collecting picrust2-2.5.2/tests/test_workflow.py _________________
import file mismatch:
imported module 'tests.test_workflow' has this __file__ attribute:
  /home/minouhuynh/picrust/picrust2/tests/test_workflow.py
which is not the same as the test file we want to collect:
  /home/minouhuynh/picrust/picrust2-2.5.2/tests/test_workflow.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
================================ short test summary info ================================
ERROR picrust2-2.5.2/tests/test_hsp.py
ERROR picrust2-2.5.2/tests/test_metagenome_pipeline.py
ERROR picrust2-2.5.2/tests/test_pathway_pipeline.py
ERROR picrust2-2.5.2/tests/test_place_seqs.py
ERROR picrust2-2.5.2/tests/test_util.py
ERROR picrust2-2.5.2/tests/test_workflow.py
!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 6 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!
=================================== 6 errors in 0.54s ===================================
![Screenshot from 2024-07-27 22-28-22](https://github.com/user-attachments/assets/1d08fa4b-a775-4a02-9030-24c434c9e49f)

**Comment by gavinmdouglas** [comment]
Hi there, 

I'm not sure exactly what the issue is here -- did you also install a different version of PICRUSt2 in a folder called `picrust2`? Based on the error it sounds like there are cached files in __pycache__ directories that are pointing to test scripts in other folders. You could try deleting those cached folders, or starting over in a new folder and conda environment.


Cheers,

Gavin
