### ISSUE TITLE
tree file after place_seqs.py is not generated

### ISSUE THREAD

**Issue by TeeratatK** [picrust/picrust2#354]
Hi,

I used the command place_seqs.py -s study_seqs.fna -o placed_seqs.tre -p 1 --intermediate placement_working for sequence replacement. But the output file of the .tre is not generated while the output of sequence alignment is done.

Best,
Bas

**Comment by TeeratatK** [comment]
![Screenshot 2024-08-23 164252](https://github.com/user-attachments/assets/163aff5d-e122-485c-97e6-debd41fb6b8e)

**Comment by R-Wright-1** [comment]
Hi, I'm not sure how to help based on this - it looks like it hasn't finished running yet? Could you try running this again with the ```--verbose``` option? And show the exact command that you ran as well as the full output.

**Comment by TeeratatK** [comment]
Thanks for this response.

I ran sequence placement with command:
place_seqs.py -s Crusttemp16SASV.fa -o placed_seqs.tre -p 1 --intermediate placement_working_1 --verbose

![image](https://github.com/user-attachments/assets/c33ccfb1-1729-4fc4-bfab-06098ee63d51)

This is the output files
![image](https://github.com/user-attachments/assets/12a8307f-fb8c-432b-b487-063c95051648)

Best,
Bas

**Comment by R-Wright-1** [comment]
Hi, so that is actually saying that there was an error with running the epa-ng command. I would suggest trying to run only that command and trouble-shooting from there (i.e. do all of the files exist that it is trying to use?).

**Comment by TeeratatK** [comment]
Hi,
I try to run epa-ng separately. I got .jplace file, but the file size of epa_result.jplace is zero.

`epa-ng --tree ./picrust2-2.5.3/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre --ref-msa ./Bac_data/placement_working_1/ref_seqs_hmmalign.fasta --query ./Bac_data/placement_working_1/study_seqs_hmmalign.fasta --chunk-size 5000 -T 1 -m ./picrust2-2.5.3/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model -w ./Bac_data/placement_working_1/epa_out --filter-acc-lwr 0.99 --filter-max 100 --redo`

What do you think the problem caused by version that I used?

dendropy                  4.5.2              pyh3252c3a_0    bioconda
epa-ng                    0.3.8                hdcf5f25_4    bioconda

**Comment by TeeratatK** [comment]
Hi, 

I tried to reduce chunk size from 5000 to 100 for analysis and it works now. I think the problem is RAM required for running.

Thank you for your assistance,
Bas
