### ISSUE TITLE
Error : Stopping - no ASV ids overlap between input FASTA and sequence abundance table

### ISSUE THREAD

**Issue by ConstanceBtd** [picrust/picrust2#355]
Hello,

I am trying to run the picrust command following a [pipeline using R](https://shibalytics.com/teaching/16s/microbiome_analysis_part_v#functional-prediction-using-picrust2) . I have successfully created the file needed for picrust to run:
- raw_counts.tsv:
> head(raw_counts)
```
          V1         V2         V3         V4         V5         V6         V7
1    #OTU ID ASV_025481 ASV_035517 ASV_017949 ASV_019089 ASV_036065 ASV_002316
2 PJA2Pk01Rc          0          0          0          0          0          0
          V8         V9        V10        V11        V12        V13        V14
1 ASV_019784 ASV_019052 ASV_029594 ASV_009314 ASV_029588 ASV_001737 ASV_020566

```
- seq.fna:
```
>ASV_025481
TACGGAAGGGGCAAGCGTTGTTCGGAATCATTGGGCGTAAAGGGCGCGTAGGTGGTTCTGTATGTCTACTGTGAAAGCATGCGGCTCAACCGTGTTAGGTCGGTAGAAACTGCAGGACTTGAGGCTGGGAGGGGCTGGTGGAATTCCCTGTGTAGCGGTGAAATGCGTAGAGATGGGGGAGAACACTCGTGGCGAAGGCGGCCAGCTGGACCAGTTCTGACACTGAGGCGCGATAGCGTGGGGAGCAAACAGG
>ASV_035517
TACGGAAGGGGCAAGCGTTGTTCGGAATTATTGGGCGTAAAGGGCGCGTAGGTGGTTTTGTGTGTCTATCGTGAAAGCACGCGGCTCAACCGCGTTCCGTCGGTAGAAACTGCAGAACTAGAGACTGGGAGGGGCTGGTGGAATTCCCTGTGTAGCGGTGAAATGCGTAGAGATGGGGGAGAACACTCGTGGCGAAGGCGGCCAGCTAGACCAGTTCTGACACTGAGGCGCGATAGCGTGGGGAGCAAACAGG
>ASV_017949
TACGGAAGGGGCAAGCGTTGTTCGGAATTATTGGGCGTAAAGGGCGCGTAGGTGGCTTTGTGTGTCTATCGTGAAATCACGCAGCTCAACTGCGTTCCGTCGGTAGAAACTGCAGAGCTAGAGGCTGGGAGGGGCTGGTGGAATTCCCTGTGTAGCGGTGAAATGCGTAGAGATGGGGGAGAACACTCGTGGCGAAGGCGGCCAGCTGGACCAGTTCTGACACTGAGGCGCGATAGCGTGGGGAGCAAACAGG
>ASV_019089
TACGGAAGGGGCAAGCGTTGTTCGGAATTATTGGGCGTAAAGGGCGCGTAGGTGGCTTTGTGTGTCTATCGTGAAATCACGCAGCTTAACTGCGTTCCGTCGGTAGAAACTGCAGAGCTAGAGGCTGGGAGGGGCTGGTGGAATTCCCTGTGTAGCGGTGAAATGCGTAGAGATGGGGGAGAACACTCGTGGCGAAGGCGGCCAGCTGGACCAGTTCTGACACTGAGGCGCGATAGCGTGGGGAGCAAACAGG
>ASV_036065
TACGGAAGGGGCAAGCGTTGTTCGGAATCATTGGGCGTAAAGGGCGCGTAGGTGGTCTTGTGTGTCTTCCGTGAAAGCCCACAGCTCAACTGTGGTGTGTCGGGAGAAACTGCAGGACTTGAGGCTGGGAGGGGCTGGTGGAATTCCCTGTGTAGCGGTGAAATGCGTAGAGATGGGGGAGAACACTCGTGGCGAAGGCGGCCAGCTAGACCAGTTCTGACACTGAGGCGCGATAGCGTGGGGAGCAAACAGG

```
However, when I run picrust, I have the following error:  `Stopping - no ASV ids overlap between input FASTA and sequence abundance table`
I saw on previous issues that you suggested changing the name of the first column (from "#OTU ID" to "OTU_ID"), which I did but I still got the same error. Would you have an idea of where it could be coming from ?

Thanks !

Constance

**Comment by R-Wright-1** [comment]
Hi there,

I'm not exactly sure what the format of your file is based on that snippet, but it looks like you have ASVs as columns and samples as rows? Usually for running PICRUSt2 you need to have ASVs as rows and samples as columns. You can see some example files in the [tutorial page](https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.5.2)), however, I can't give any advice on the pipeline that you are using in R - I have never used that before and you should reach out to the person that made that if you need help with that.

**Comment by ConstanceBtd** [comment]
Hello,

Thank you so much for you answer : I didn't even notice that I had ASVs as columns instead of rows... It works now that I've transposed it!

Thanks!

Constance

**Comment by R-Wright-1** [comment]
Great, no problem!
