### ISSUE TITLE
Getting error 

### ISSUE THREAD

**Issue by Sam131992** [picrust/picrust2#359]
I got this error when I run the Picrust2 2.5.3 version.

Picrust2_pipeline.py -s dna-sequences.fasta -i feature-table.biom -o picrust2_out_2pipeline -p 1
Warning - 1 input sequences aligned poorly to reference sequences (--min_align option specified a minimum proportion of 0.8 aligning to reference sequences). These input sequences will not be placed and will be excluded from downstream steps.

This is the set of poorly aligned input sequences to be excluded: 9813f332cbc35d7f5b915b3650f12b97

Error running this command:
hsp.py --tree picrust2_out_2pipeline/out.tre --output picrust2_out_2pipeline/marker_predicted_and_nsti.tsv.gz --observed_trait_table /Users/subhikshaa/.conda/envs/picrust2/lib/python3.9/site-packages/picrust2/default_files/prokaryotic/16S.txt.gz --hsp_method mp --edge_exponent 0.5 --seed 100 --calculate_NSTI --processes 1

Standard error of the above failed command:

Error running this command:
Rscript /Users/subhikshaa/.conda/envs/picrust2/lib/python3.9/site-packages/picrust2/Rscripts/castor_nsti.R picrust2_out_2pipeline/out.tre /var/folders/tx/8vfw2kxn7nn9tc3p5jwnsgtc0000gn/T/tmp7qfdwzyn/known_tips.txt /var/folders/tx/8vfw2kxn7nn9tc3p5jwnsgtc0000gn/T/tmp7qfdwzyn/nsti_out.txt

Standard error of the above failed command:
Error: package or namespace load failed for ‘Rcpp’ in library.dynam(lib, package, package.lib):
 shared object ‘Rcpp.dylib’ not found
In addition: Warning messages:
1: package ‘castor’ was built under R version 4.4.1 
2: package ‘Rcpp’ was built under R version 4.4.1 
Execution halted

**Comment by R-Wright-1** [comment]
Hi there,

Could you just give some details on how you installed PICRUSt2 please? There have been a couple of similar issues recently, maybe you can look at the solutions there: #358 and #356.

Robyn

**Comment by R-Wright-1** [comment]
After some further investigation of similar issues, we've found that installing the R package `r-essentials` seems to fix similar issues. We've added this to the [installation page now](https://github.com/picrust/picrust2/wiki/Installation). Please feel free to re-open the issue if this doesn't fix your problem.

Robyn
