### ISSUE TITLE
Categorization like PICRUST1 - using R

### ISSUE THREAD

**Issue by EJS01** [picrust/picrust2#362]
Hi, is it okay for me to use the results of this R run even if the value at the end is "False"?

> identical(test_ko_L3_sorted, orig_ko_L3)
[1] FALSE  

[path_abun_unstrat.tsv.gz](https://github.com/user-attachments/files/17184133/path_abun_unstrat.tsv.gz)

[run 2 using Rcode_categorize like Picrust1 - Copy.docx](https://github.com/user-attachments/files/17184130/run.2.using.Rcode_categorize.like.Picrust1.-.Copy.docx)

**Comment by R-Wright-1** [comment]
Hello,

I'm afraid that I don't have personal experience with this script in PICRUSt1 and we don't really provide support for PICRUSt1 any longer. I don't know exactly what you're trying to compare here, but based on your variable names it looks like comparing KOs grouped to a higher level with the pathways output? I would just look at the pathways file as this methodology was developed for PICRUSt2 to be more accurate than simply mapping KOs to higher levels. In any case, if you want to ask the community about this output then I suggest asking your question (with some more information on what exactly you are trying to achieve) on the [PICRUSt users google group](https://groups.google.com/g/picrust-users).

Robyn
