### ISSUE TITLE
Error in matrix(0, nrow = Nclades, ncol = Nstates - common_state) :   invalid 'ncol' value (too large or NA)

### ISSUE THREAD

**Issue by Abelcanc3rhack3r** [picrust/picrust2#363]
Hi,
 hsp.py -t /oceanstor/home/e1103389/JGI_picrust/simulated_datasets/sim_0.5_2/placed_seqs.tre -o /oceanstor/home/e1103389/JGI_picrust/simulated_datasets/sim_0.5_2/marker_nsti_predicted.tsv  -p 15 -n --observed_trait_table /oceanstor/home/e1103389/JGI_picrust/simulated_datasets/sim_0.5_2/feature_table2.csv

and I got this error:

Error running this command:
Rscript /home/svu/e1103389/anaconda3/envs/picrust2/lib/python3.8/site-packages/picrust2/Rscripts/castor_hsp.R /oceanstor/home/e1103389/JGI_picrust/simulated_datasets/sim_0.5_2/placed_seqs.tre /var/tmp/pbs.628018.kylin/tmpb56_3wqq/subset_tab_0 mp 0.5 FALSE FALSE /var/tmp/pbs.628018.kylin/tmphyglu0hn/predicted_counts.txt /var/tmp/pbs.628018.kylin/tmphyglu0hn/predicted_ci.txt 100

Standard error of the above failed command:
Error in matrix(0, nrow = Nclades, ncol = Nstates - common_state) :
  invalid 'ncol' value (too large or NA)
Calls: lapply ... mp_study_probs -> hsp_max_parsimony -> cbind -> matrix
Execution halted

However, I ran feature_table2 as the trait table, it worked.
Here are the relevant files:
The tree is in the zip file.
[placed_seqs.zip](https://github.com/user-attachments/files/17291899/placed_seqs.zip)

FAILED:
[feature_table.csv](https://github.com/user-attachments/files/17291884/feature_table.csv)

WORKED:
[feature_table2.csv](https://github.com/user-attachments/files/17291905/feature_table2.csv)

**Comment by R-Wright-1** [comment]
Hi there,

I'm not really sure what you're trying to do here, but these two feature tables have different numbers of rows, so I assume that this is why it worked once but not the other time? As this doesn't seem to be an issue with the PICRUSt2 code, please feel free to post in the [PICRUSt-users google group](https://groups.google.com/g/picrust-users) if you'd like to ask further questions. You may also get further input from the wider community this way, too.

Robyn
