### ISSUE TITLE
How to estimate library size?

### ISSUE THREAD

**Issue by krcurtis** [picrust/picrust2#365]
Does PICRUST2 offer any way to estimate library size?  This might be helpful with different normalizations. It might also be helpful in deciding on sequencing depth for follow-up metagenomics sequencing. Thanks!

**Comment by R-Wright-1** [comment]
Hi there,
I'm not quite sure I understand the question - your library size would just be the number of reads, but as data has typically already had low abundance taxa removed prior to PICRUSt2, I'm not quite sure how this would be possible. You can see suggestions for how to normalise data in the [FAQ](https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#should-i-rarefy-or-transform-the-predictions-after-running-picrust2). I also don't think it would be straightforward for us to add a feature that would assist in estimating required sequencing depth for metagenomics as this would depend so heavily on the type of sample, host contamination, etc. I'm going to close this as it isn't an issue, but if you would like to post on the [PICRUSt2 users Google group](https://groups.google.com/g/picrust-users) then you may get input from others on this. 
Robyn
