### ISSUE TITLE
Inferring EC numbers corresponding to post-2018 update

### ISSUE THREAD

**Issue by michaelwasney** [picrust/picrust2#366]
Hello! Very nice software. I notice in your methods that you are using "Enyzme Commission (EC) numbers (as of 21 Jan 2016)." Would it be possible to infer EC number corresponding to the post-2018 update? Thanks!

**Comment by R-Wright-1** [comment]
Hi there,

The annotations were obtained from JGI/IMG and I'm currently working on an updated database that would use annotations of the GTDB genomes. I've obtained all of these (including EC numbers as annotated with [eggNOG-mapper](https://github.com/eggnogdb/eggnog-mapper/tree/2.1.12)) now and am currently testing how these work and how I'll incorporate them into PICRUSt2 (they require aligning separately to the archaea and bacteria as these have two separate trees within GTDB). I recently added to the [FAQ](https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-were-the-annotations-used-for-picrust2-predictions-generated-are-they-updated) about this.

Robyn

**Comment by R-Wright-1** [comment]
Hi,

I just wanted to update you that I have now made the new database available for testing. I'm not rolling it out for everyone yet, but if you're interested in trying it out and letting me know if you run into any issues, that would be great. I've added a Wiki page on installing and using this version [here](https://github.com/picrust/picrust2/wiki/Testing-the-updated-PICRUSt2-database). It now uses GTDB genomes from release 214 and I've annotated these using Eggnog v2.1.12 - you can read more about what is included in the Eggnog database [here](http://eggnog5.embl.de/#/app/home). 

Robyn

**Comment by michaelwasney** [comment]
Hey Robyn,

Amazing, thank you so much! This is really awesome. I'll give it a try in
the next couple of weeks and let you know how it runs!

Best,
Michael

**Comment by R-Wright-1** [comment]
That would be great, thanks!!
