### ISSUE TITLE
Pathway relative abundance

### ISSUE THREAD

**Issue by carbon14bond** [picrust/picrust2#367]
I am trying to look at changes in the relative abundance of different functional groups using the MetaCyc pathway outputs, e.g., using DENITRIFICATION-PWY or METHANOGENESIS-PWY to look at denitrifiers or methanogens, respectively. 

Now, to convert to relative abundance, I divided the pathway abundances from path_abun_unstrat.tsv by the sum of reads per sample from seqtab_norm.tsv. At first things looked correct, most pathways ranged from 0-1 as expected, but some pathways were >1, i.e., relative abundance over 100%? Is this because some ASVs are predicted to have multiple copies of a gene/pathway? Or is there a better way to achieve this, some output or option I missed? Is there a way to say, give me total percent abundance of ASVs predicted to contain pathway x, ignoring however many copies of those genes they may have? Would like to have percent abundance as 'percent of reads from ASVs which possess pathway x, out of the total number of reads'.

Thanks!

**Comment by R-Wright-1** [comment]
Hi there,

There are a [few questions in the FAQ](https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-are-the-metacyc-pathway-abundances-calculated) that get at this, but essentially the mapping from EC numbers to metacyc pathways is not 1:1 in terms of abundance. I'd suggest that to convert the path_abun_unstrat to relative abundance, you should divide the pathway abundances by the total for each column within that file. 

Best wishes,
Robyn
