### ISSUE TITLE
prerequisite installation issue

### ISSUE THREAD

**Issue by swathipen** [picrust/picrust2#41]
I followed the pre-requisite installation instructions and received several errors while running the make commands :

_cd epa-ng-0.2.1-beta-dev
make_

Running cmake
CMake Warning (dev) at CMakeLists.txt:119:
  Syntax Warning in cmake code at column 71

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The CXX compiler identification is GNU 4.8.5
-- The C compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:39 (message):
  GNU compiler too old! Minimum required: 4.9.2

-- Configuring incomplete, errors occurred!
See also "/users/spenumut/picrust2/placement_tools/epa-ng-0.2.1-beta-dev/build/CMakeFiles/CMakeOutput.log".
make: *** [build/CMakeCache.txt] Error 1

_cd gappa-0.0.0-dev_
_make_
Running CMake...
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Gappa build type: RELEASE
-- Static linking of system libraries: OFF
-- CLI11 not found
-- Downloading CLI11 from https://github.com/CLIUtils/CLI11/archive/bd890e24a1f081d6db1a59a0cc372eccc64e9e52.zip
-- Configuring done
-- Generating done
-- Build files have been written to: /gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download
gmake[1]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download'
gmake[2]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download'
gmake[3]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download'
Scanning dependencies of target CLI11
gmake[3]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download'
gmake[3]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download'
[ 11%] Creating directories for 'CLI11'
[ 22%] Performing download step (download, verify and extract) for 'CLI11'
-- Downloading...
   dst='/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download/CLI11-prefix/src/bd890e24a1f081d6db1a59a0cc372eccc64e9e52.zip'
   timeout='none'
-- Using src='https://github.com/CLIUtils/CLI11/archive/bd890e24a1f081d6db1a59a0cc372eccc64e9e52.zip'
-- Downloading... done
-- extracting...
     src='/users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download/CLI11-prefix/src/bd890e24a1f081d6db1a59a0cc372eccc64e9e52.zip'
     dst='/users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/libs/CLI11'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 33%] No patch step for 'CLI11'
[ 44%] No update step for 'CLI11'
[ 55%] No configure step for 'CLI11'
[ 66%] No build step for 'CLI11'
[ 77%] No install step for 'CLI11'
[ 88%] Performing test step for 'CLI11'
/bin/sh: DOWNLOAD_NO_PROGRESS 1: command not found
gmake[3]: *** [CLI11-prefix/src/CLI11-stamp/CLI11-test] Error 127
gmake[3]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download'
gmake[2]: *** [CMakeFiles/CLI11.dir/all] Error 2
gmake[2]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download'
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/CLI11Download'
-- Cannot build CLI11: 2
-- genesis not found
-- Downloading genesis from https://github.com/lczech/genesis/archive/6e1aa0665614df91ec51400356d339ca88c7134b.zip
-- Configuring done
-- Generating done
-- Build files have been written to: /gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload
gmake[1]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload'
gmake[2]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload'
gmake[3]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload'
Scanning dependencies of target genesis
gmake[3]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload'
gmake[3]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload'
[ 11%] Creating directories for 'genesis'
[ 22%] Performing download step (download, verify and extract) for 'genesis'
-- Downloading...
   dst='/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload/genesis-prefix/src/6e1aa0665614df91ec51400356d339ca88c7134b.zip'
   timeout='none'
-- Using src='https://github.com/lczech/genesis/archive/6e1aa0665614df91ec51400356d339ca88c7134b.zip'
-- Downloading... done
-- extracting...
     src='/users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload/genesis-prefix/src/6e1aa0665614df91ec51400356d339ca88c7134b.zip'
     dst='/users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/libs/genesis'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 33%] No patch step for 'genesis'
[ 44%] No update step for 'genesis'
[ 55%] No configure step for 'genesis'
[ 66%] No build step for 'genesis'
[ 77%] No install step for 'genesis'
[ 88%] Performing test step for 'genesis'
/bin/sh: DOWNLOAD_NO_PROGRESS 1: command not found
gmake[3]: *** [genesis-prefix/src/genesis-stamp/genesis-test] Error 127
gmake[3]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload'
gmake[2]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload'
gmake[2]: *** [CMakeFiles/genesis.dir/all] Error 2
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/genesisDownload'
-- Cannot build genesis: 2
-- sparsepp not found
-- Downloading sparsepp from https://github.com/greg7mdp/sparsepp/archive/6bfe3b4bdb364993e612d6bb729d680cf4c77649.zip
-- Configuring done
-- Generating done
-- Build files have been written to: /gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload
gmake[1]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload'
gmake[2]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload'
gmake[3]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload'
Scanning dependencies of target sparsepp
gmake[3]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload'
gmake[3]: Entering directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload'
[ 11%] Creating directories for 'sparsepp'
[ 22%] Performing download step (download, verify and extract) for 'sparsepp'
-- Downloading...
   dst='/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload/sparsepp-prefix/src/6bfe3b4bdb364993e612d6bb729d680cf4c77649.zip'
   timeout='none'
-- Using src='https://github.com/greg7mdp/sparsepp/archive/6bfe3b4bdb364993e612d6bb729d680cf4c77649.zip'
-- Downloading... done
-- extracting...
     src='/users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload/sparsepp-prefix/src/6bfe3b4bdb364993e612d6bb729d680cf4c77649.zip'
     dst='/users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/libs/sparsepp'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 33%] No patch step for 'sparsepp'
[ 44%] No update step for 'sparsepp'
[ 55%] No configure step for 'sparsepp'
[ 66%] No build step for 'sparsepp'
[ 77%] No install step for 'sparsepp'
[ 88%] Performing test step for 'sparsepp'
/bin/sh: DOWNLOAD_NO_PROGRESS 1: command not found
gmake[3]: *** [sparsepp-prefix/src/sparsepp-stamp/sparsepp-test] Error 127
gmake[3]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload'
gmake[2]: *** [CMakeFiles/sparsepp.dir/all] Error 2
gmake[2]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload'
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory `/gpfs_home/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build/sparseppDownload'
-- Cannot build sparsepp: 2
-- Configuring Genesis
-- CMake version 3.12.0
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Genesis version: v0.19.0
-- Building Genesis as a dependency
-- Build type: RELEASE
-- Unity build: FULL
-- C++ compiler: GNU 4.8.5 at /usr/bin/c++
-- C compiler  : GNU 4.8.5 at /usr/bin/cc
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for Threads
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found Threads: -pthread
-- Using Threads
-- Looking for OpenMP
-- Found OpenMP_C: -fopenmp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
-- Found OpenMP: -fopenmp
-- Using OpenMP
-- Building static lib
-- Finished configuring Genesis
-- CMAKE_EXE_LINKER_FLAGS   
-- GENESIS_LINK_LIBRARIES -pthread;genesis_lib_static
-- Configuring done
-- Generating done
-- Build files have been written to: /users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/build
Running make...
make -s -C build
Scanning dependencies of target genesis_lib_static
[  3%] Building CXX object libs/genesis/lib/genesis/CMakeFiles/genesis_lib_static.dir/__/__/__/__/genesis_unity_sources/lib/all.cpp.o
[  6%] Linking CXX static library ../../../../../libs/genesis/bin/libgenesis.a
[  6%] Built target genesis_lib_static
Scanning dependencies of target gappa
[  9%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/assign.cpp.o
[ 12%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/correlation.cpp.o
[ 15%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/dispersion.cpp.o
[ 18%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/edgepca.cpp.o
[ 21%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/graft.cpp.o
[ 24%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/kmeans.cpp.o
[ 27%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/kmeans_imbalance.cpp.o
[ 30%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/kmeans_phylogenetic.cpp.o
[ 33%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/krd.cpp.o
[ 36%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/nhd.cpp.o
[ 39%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/squash.cpp.o
[ 42%] Building CXX object CMakeFiles/gappa.dir/src/commands/analyze/visualize_color.cpp.o
[ 45%] Building CXX object CMakeFiles/gappa.dir/src/commands/prepare/chunkify.cpp.o
[ 48%] Building CXX object CMakeFiles/gappa.dir/src/commands/prepare/extract.cpp.o
[ 51%] Building CXX object CMakeFiles/gappa.dir/src/commands/prepare/phat.cpp.o
[ 54%] Building CXX object CMakeFiles/gappa.dir/src/commands/prepare/unchunkify.cpp.o
[ 57%] Building CXX object CMakeFiles/gappa.dir/src/main.cpp.o
[ 60%] Building CXX object CMakeFiles/gappa.dir/src/options/color/color_map.cpp.o
[ 63%] Building CXX object CMakeFiles/gappa.dir/src/options/color/color_norm.cpp.o
[ 66%] Building CXX object CMakeFiles/gappa.dir/src/options/color/single_color.cpp.o
[ 69%] Building CXX object CMakeFiles/gappa.dir/src/options/file_input.cpp.o
[ 72%] Building CXX object CMakeFiles/gappa.dir/src/options/file_output.cpp.o
[ 75%] Building CXX object CMakeFiles/gappa.dir/src/options/global.cpp.o
[ 78%] Building CXX object CMakeFiles/gappa.dir/src/options/jplace_input.cpp.o
[ 81%] Building CXX object CMakeFiles/gappa.dir/src/options/matrix_output.cpp.o
In file included from /users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/src/options/matrix_output.hpp:32:0,
                 from /users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/src/options/matrix_output.cpp:24:
/users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/libs/genesis/lib/genesis/utils/containers/matrix/writer.hpp: In constructor ‘genesis::utils::MatrixWriter<T>::MatrixWriter() [with T = double]’:
/users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/libs/genesis/lib/genesis/utils/containers/matrix/writer.hpp:72:5: error: conversion from ‘const char [2]’ to non-scalar type ‘std::string {aka std::basic_string<char>}’ requested
     MatrixWriter() = default;
     ^
/users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/src/options/matrix_output.cpp: In member function ‘void MatrixOutputOptions::write_matrix(const genesis::utils::Matrix<double>&, const std::vector<std::basic_string<char> >&, const std::vector<std::basic_string<char> >&, const string&) const’:
/users/spenumut/picrust2/placement_tools/gappa-0.0.0-dev/src/options/matrix_output.cpp:99:40: note: synthesized method ‘genesis::utils::MatrixWriter<T>::MatrixWriter() [with T = double]’ first required here 
     auto writer = MatrixWriter<double>();
                                        ^
make[3]: *** [CMakeFiles/gappa.dir/src/options/matrix_output.cpp.o] Error 1
make[2]: *** [CMakeFiles/gappa.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [build] Error 2

**Comment by gavinmdouglas** [comment]
Hey there,

The key error is: "GNU compiler too old! Minimum required: 4.9.2”. You’ll need to update your version of gcc to get EPA-NG working. Please note that I just released a QIIME2 plugin of PICRUSt2 that can be used with the q2-fragment-insertion QIIME2 plugin instead of using EPA-NG and GAPPA. There are less options with this plugin, but it should be much easier to install. See here for details: https://github.com/picrust/picrust2/wiki/q2-picrust2-Tutorial <https://github.com/picrust/picrust2/wiki/q2-picrust2-Tutorial>


Gavin
