### ISSUE TITLE
Error in the wiki

### ISSUE THREAD

**Issue by apcamargo** [picrust/picrust2#52]
In the Full Pipeline page of the Wiki it is written:

> `--per_sequence_contrib` - Run MinPath on the gene families contributed by each sequence (i.e. a predicted genome) individually. This will only matter `--per_sequence_contrib` is set.

I believe it should be:

> `--per_sequence_contrib` - Run MinPath on the gene families contributed by each sequence (i.e. a predicted genome) individually. This will only matter `--stratified` is set.

**Comment by gavinmdouglas** [comment]
Thanks for catching that!
