### ISSUE TITLE
q2 picrust2 Tutorial error

### ISSUE THREAD

**Issue by dong1984** [picrust/picrust2#57]
I am doing a q2 picrust2 Tutorial (https://github.com/picrust/picrust2/wiki/q2-picrust2-Tutorial)
A Plugin error occurs when I am doing fragment-insertion:
What I have done is following the tutorial line by line, how could I solve this?

I download those 3 file by:
mkdir q2-picrust2_test
cd q2-picrust2_test
wget http://kronos.pharmacology.dal.ca/public_files/tutorial_datasets/picrust2_tutorial_files/mammal_biom.qza
wget http://kronos.pharmacology.dal.ca/public_files/tutorial_datasets/picrust2_tutorial_files/mammal_seqs.qza
wget http://kronos.pharmacology.dal.ca/public_files/tutorial_datasets/picrust2_tutorial_files/mammal_metadata.tsv

Then I download another two file by:
wget http://kronos.pharmacology.dal.ca/public_files/tutorial_datasets/picrust2_tutorial_files/reference.fna.qza
wget http://kronos.pharmacology.dal.ca/public_files/tutorial_datasets/picrust2_tutorial_files/reference.tre.qza

All these five files were successfully downloaded into q2-picrust2_test folder, which is created at the beginning.

I run the q2-fragmentation insertion by:
qiime fragment-insertion sepp --i-representative-sequences mammal_seqs.qza 
–p-threads 1 --i-reference-alignment reference.fna.qza 
–i-reference-phylogeny reference.tre.qza 
–output-dir tutorial_placed_out
Then the error occurs here:

Plugin error from fragment-insertion:
Command ‘[‘run-sepp.sh’, ‘/tmp/qiime2-archive-pmh381na/38a5d748-739e-44d1-b547-a35c0c8b8f29/data/dna-sequences.fasta’, ‘q2-fragment-insertion’, ‘-x’, ‘1’, ‘-A’, ‘1000’, ‘-P’, ‘5000’, ‘-a’, ‘/tmp/qiime2-archive-yyddx_7u/87909524-fa4f-4b28-abd6-c7c89a3c7da7/data/aligned-dna-sequences.fasta’, ‘-t’, ‘/tmp/qiime2-archive-3jm7iibt/f4e69728-a745-4069-b432-3f14951089fd/data/tree.nwk’]’ returned non-zero exit status 1

Debug info has been saved to /tmp/qiime2-q2cli-err-cby4nvz1.log

**Comment by gavinmdouglas** [comment]
What version of QIIME2 are you using?

**Comment by dong1984** [comment]
qiime2-2018.11
fragment-insertion 4.3.5
q2-fragment-insertion 2018.11.0

**Comment by gavinmdouglas** [comment]
Is anything written to /tmp/qiime2-q2cli-err-cby4nvz1.log?

I would first recommend re-downloading the files in case they are malformed. You could then try re-installing qiime2-2018.11 (which includes q2-fragment-insertion).

**Comment by dong1984** [comment]
I failed to find the /tmp/qiime2-q2cli-err-cby4nvz1.log
I re-downloaded the files and also updated qiime2 to qiime2-2019.1, but same error there...
