### ISSUE TITLE
ValueError: No common OTUs between the otu table and the genome table, so can't predict metagenome.

### ISSUE THREAD

**Issue by jjmmii** [picrust/picrust2#6]
Hello, I am trying to follow your workflow, I have successfully "placed study sequences into a reference multiple-sequence alignment" and finish step 2 (hsp.py). But in step 3 (metagenome_pipeline.py), where does the study_seqs.biom come from? I tried creating what I think is study_seqs.biom by exporting seqtab.nochim as a BIOM file from DADA2. (because actually, I am trying to evade the OTU picking step by directly converting DADA2 output for use in PICRUSt, following [this](https://github.com/vmaffei/dada2_to_picrust) pipeline, but that is for PICRUSt1.) But when I run step 3 I get `ValueError: No common OTUs between the otu table and the genome table, so can't predict metagenome.`

Since metagenome_pipeline.py is a wrapper script for normalize_by_copy_number.py and predict_metagenomes.py, I read the PICRUSt1 page about [them](https://picrust.github.io/picrust/tutorials/metagenome_prediction.html), and seems that study_seqs.biom is analogous to your_otu_table.biom. If this is the case, does this mean I have to pick OTUs first? So PICRUSt2 is still a closed-reference OTU picking approach? Thank you very much for your attention.

P.S. I posted a separate question in the picrust-users Google group but feel this issue is more appropriate here, feel free to ask me to re-post this issue there if you think it's better.
Best,
Jamie

**Comment by gavinmdouglas** [comment]
Hey @jjmmii, no you do not need to pick OTUs first. The pipeline is meant to work with any sequences.  The input biom table to ```metagenome_pipeline.py``` needs to have observations with the same IDs as the sequences you made predictions for with ```hsp.py```.

So if the fasta file of sequences you placed into the tree looked like this:

```
>seq1
AGTGAGT
>seq2
AGGGGTC
>seq3
AGTCCCC
```

The biom table would need to be formatted like this:

``` 
# sample1 sample2 sample3
seq1 10 20 0
seq2 40 3 5
seq3 0 10 50
```

What are the observation ids in your current biom file?

**Comment by jjmmii** [comment]
Ah, I modified both my FASTA file and my BIOM table and got it working. Thank you @gavinmdouglas !
In detail, I initially thought STUDY_SEQs.fna is the output of DADA2's seqtab.nochim.robj, re-replicated by abundance per sample, converted into FASTA format. But actually it shouldn't be re-replicated. Here is seqtab.nochim.robj as displayed in R:
```
> seqtab.nochim
            TACGTAGGTGGCGAGCGTTATCCGGAATCATTGGGCGTAAAGGGTGCGCAGGTGGTACATTAAGTCCGAAGTAAAAGGCAGCAGCTCAACTGCTGTTGGCTTTGGAAACTGGTGAACTGGAGTGCAGGAGAGGGCGATGGAATTCCATGTGTAGCGGTAAAATGCGTAGATATATGGAGGAACACCAGTGGCGAAGGCGGTCGCCTGGCCTGCAACTGACACTGAGGCACGAAAGCGTGGGGAGCAAATAGGATTAGATACCCTAGTAGTCCACGCCGTAAACGATGAGAACTAAGTGTTGGGGAGACTCAGTGCTGCAGTTAACGCAATAAGTTCTCCGCCTGGGGAGTATGCACGCAAGTGTG
W0-PIS10005                                                                                                                                                                                                                                                                                                                                                                            38
W1-PIS10005                                                                                                                                                                                                                                                                                                                                                                            44
W4-PIS10005                                                                                                                                                                                                                                                                                                                                                                            17
            TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGGGAGCAGGCGGCAGCAAGGGTCTGTGGTGAAAGCCTGAAGCTTAACTTCAGTAAGCCATAGAAACCAGGCAGCTAGAGTGCAGGAGAGGATCGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGATATATGGAGGAACACCAGTGGCGAAGGCGACGATCTGGCCTGCAACTGACGCTCAGTCCCGAAAGCGTGGGGAGCAAATAGGATTAGATACCCTAGTAGTCCACGCCGTAAACGATGAGTACTAAGTGTTGGATGTCAAAGTTCAGTGCTGCAGTTAACGCAATAAGTACTCCGCCTGAGTAGTACGTTCGCAAGAATG
W0-PIS10005                                                                                                                                                                                                                                                                                                                                                                                35
W1-PIS10005                                                                                                                                                                                                                                                                                                                                                                                20
W4-PIS10005                                                                                                                                                                                                                                                                                                                                                                                36
```
So I extracted the column headers (which are the sequences themselves) and put them into a FASTA file and give them names seq_1 seq_2 etc.
For the biom table, if seqtab.nochim.robj is exported directly as tab-delimited biom file, the difference between this and your example is 1) It is transposed, and 2) The sequence itself is the column name instead of sequence name. Therefore, I had to export seqtab.nochim as TSV, then do these two conversions.
