### ISSUE TITLE
pathway abundances in qiime2 picrust2 plugin

### ISSUE THREAD

**Issue by ceolder** [picrust/picrust2#64]
Hi,

I'm wondering if there is a way to get an output of pathway abundances that show each pathway's abundance per sample. Currently I have the pathway_abundance.qzv, but as far as I can tell, there is not functionally within viewing this file that allows me to see which specific pathways were predicted per sample (can only see a pathway is found in x samples or a sample has x pathways). I could not find anything on the wiki page or qiime2 site.

Thanks,
Caitlin

**Comment by gavinmdouglas** [comment]
Hi Caitlin,

I think this is the same question asked here: https://github.com/gavinmdouglas/q2-picrust2/issues/4

Does that help you? The main output tables are the abundances per sample - I think what you're referring to is just a quick visual summary of what's in the files.


Best,

Gavin

**Comment by ceolder** [comment]
Hi Gavin,

Thank you for providing that link, it was exactly what I was looking for :) Sorry, didn't even realize there was another place for the qiime2 plugin for picrust2! 

Thanks,
Caitlin
