### ISSUE TITLE
Issue of running picrust2_pipeline.py regarding /home/qiime2/miniconda/envs/picrust2/lib/python3.6/site-packages/ problem

### ISSUE THREAD

**Issue by cctsui** [picrust/picrust2#67]
####Halo, I am new to picrust2 and I encounter some problem running the tutorial data.
####I am using virtual machine to run picrust2 and my installation process is following below:
conda create -n picrust2
source activate picrust2
conda install -c bioconda -c conda-forge picrust2

#####After the installation I have run downloaded the tutorial data and run the command as follows:
picrust2_pipeline.py -s /media/sf_microbiome_USB/dry_lab/raw_data/picrust_testing/tutorial_seqs.fna -i /media/sf_microbiome_USB/dry_lab/raw_data/picrust_testing/tutorial.biom -o picrust2_out_pipeline

#####After that I have encounter the following error message:
Error: File existence/permissions problem in trying to open HMM file /home/qiime2/miniconda/envs/picrust2/lib/python3.6/site-packages/default_files/prokaryotic/reference.hmm.
HMM file /home/qiime2/miniconda/envs/picrust2/lib/python3.6/site-packages/default_files/prokaryotic/reference.hmm not found (no

Error running this command:
hmmalign --trim --dna --mapali /home/qiime2/miniconda/envs/picrust2/lib/python3.6/site-packages/default_files/prokaryotic/reference.fna --informat FASTA -o picrust2_out_pipeline_5/intermediate/place_seqs/query_align.stockholm /home/qiime2/miniconda/envs/picrust2/lib/python3.6/site-packages/default_files/prokaryotic/reference.hmm /media/sf_microbiome_USB/dry_lab/raw_data/picrust_testing/tutorial_seqs.fna

####After investigation, I found that /home/qiime2/miniconda/envs/picrust2/lib/python3.6/site-packages have no any sub directory under it. However, I dun know why this will be happened and how to solve it.

Thank you so much for helping me

**Comment by gavinmdouglas** [comment]
Hi there,

Are you able to install any tools successfully with conda? Since it looks like nothing was installed when you ran the conda command this makes me think there may be something wrong with your miniconda installation.

**Comment by gavinmdouglas** [comment]
Closed due to inactivity.

**Comment by qbdong122** [comment]
Have you solved this?

**Comment by clearc352** [comment]
> Have you solved this?

it's seems that conda install package  will lost default_files,a solution is that downlaod repo files https://github.com/picrust/picrust2/tree/master/picrust2/default_files/prokaryotic/pro_ref copy to  /you_conda_env /lib/you_python_version/site-packages/default_files
plz note that rename pro_ref to reference
