### ISSUE TITLE
Default tree with EPA-NG

### ISSUE THREAD

**Issue by adityabandla** [picrust/picrust2#69]
What is the current tree into which sequences are placed when using the EPA-NG pipeline? I was trying to figure out which database, but could not find that info 

I was wondering if the EPA-NG pipeline can be used to place sequences onto the SILVA tree

**Comment by gavinmdouglas** [comment]
Hi there,

The current tree is a custom tree made from 16S sequences from IMG genomes (i.e. the genomes for which there is functional content available).

You can definitely place your own sequences into the SILVA tree for other analyses, but for the default PICRUSt2 pipeline you need to place your sequences into this IMG tree.

**Comment by adityabandla** [comment]
Thanks Gavin for the prompt reply. That clarifies!
