### ISSUE TITLE
MinPath SyntaxError: Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by jjmmii** [picrust/picrust2#7]
Hi Gavin!
So I'm on step 4 of your pipeline now. I typed this command and got this error:
```
$ run_minpath.py -i OUT_PREFIX.genefamilies.biom -m /path/to/MinPath/data/ec2path -o Pathway_abundances.tsv --keep_tmp
  File "/home/ubuntu/MinPath/MinPath12hmp.py", line 74
    print "now get SEED"
                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("now get SEED")?
Error running this command:
MinPath12hmp.py -any minpath_tmp_jam0tj_8/W0-PIS10005_minpath_in.txt -map /path/to/MinPath/data/ec2path -report minpath_tmp_jam0tj_8/W0-PIS10005_minpath_report.txt -details minpath_tmp_jam0tj_8/W0-PIS10005_minpath_details.txt -mps minpath_tmp_jam0tj_8/W0-PIS10005_minpath.mps
```
I think MinPath uses python2 while the PICRUSt2 conda environment uses python3. How shall we fix this?
Also, you said to install MinPath12hmp.py in the [install wiki page](https://github.com/picrust/picrust2/wiki/Installation) but mentioned MinPath1.4.py in [step 4](https://github.com/picrust/picrust2/wiki/Workflow). I think you meant to use MinPath1.4.py because you need its support files, but I had to symlink it as MinPath12hmp.py because your script calls so.

Thanks!
Jamie

**Comment by jjmmii** [comment]
An update: I converted MinPath1.4.py from Python 2 code to Python 3 using [2to3](https://docs.python.org/2/library/2to3.html), and got it to run. Now I'm encountering this error: `lpx_add_cols: ncs = 0; invalid number of columns`. The preceding stdout lines tell me that W0-PIS10005_minpath_out.txt is empty (where W0-PIS10005 is one sample's name):
```
now write mps file..
original ortholog=73 found-in-the-fam-list=0 found-in-the-fam-mapped-to-pathway=0
End of PrintMPS
now run command = /home/ubuntu/MinPath//glpk-4.6/examples/glpsol minpath_tmp_x4hxwnuy/W0-PIS10005_minpath.mps -o minpath_tmp_x4hxwnuy/W0-PIS10005_minpath.mps.LPout
load_mps: reading LP data from `minpath_tmp_x4hxwnuy/W0-PIS10005_minpath.mps'...
load_mps: name `PATH'
load_mps: 1 rows
load_mps: 0 columns
load_mps: 0 non-zeros
load_mps: 0 right-hand side vector(s)
load_mps: 0 range vector(s)
load_mps: 0 bound vector(s)
load_mps: 7 cards were read
```
Do you have any ideas about this? Looking forward to discussing with you.

Best,
Jamie

**Comment by jjmmii** [comment]
Thank you for your quick response Gavin. After cloning the latest version, I use your custom mapping files, and this is the command:
`$ run_minpath.py -i OUT_PREFIX.genefamilies.biom -m ~/downloads/picrust2/MinPath/ec2metacyc_picrust_prokaryotic.txt -o Pathway_abundances.tsv --keep_tmp`
And then error:
```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda2/envs/picrust2-dev/bin/run_minpath.py", line 6, in <module>
(...truncated)
  File "/home/ubuntu/downloads/picrust2/picrust2/run_minpath.py", line 72, in minpath_wrapper
    minpath_in = str(tmp_dir + "/" + sample_id + "_minpath_in.txt")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
This is another Python2 to 3 issue I believe: https://stackoverflow.com/questions/15036594/python-3-3-typeerror-unsupported-operand-types-for-nonetype-and-str
I can't locate the line `minpath_in = str(tmp_dir + "/" + sample_id + "_minpath_in.txt"` in any of the mentioned files.

**Comment by gavinmdouglas** [comment]
Thanks for reporting this bug as well. There was a typo in how the temp directory name was being passed to the wrapper for MinPath. It's fixed now in the latest push. You could also specify the name of the tmp directory to use yourself with the ```--tmp_dir``` option and it should work.

**Comment by jjmmii** [comment]
Thank you Gavin! The above error is gone. And I am getting the next error, haha XD :
```
Error when running glpsol from MinPath.

Error running this command:
/home/ubuntu/downloads/picrust2/MinPath/MinPath12hmp.py -any minpath_tmp_vhn_p7b2/W0-PIS10005_minpath_in.txt -map /home/ubuntu/downloads/picrust2/MinPath/ec2metacyc_picrust_prokaryotic.txt -report minpath_tmp_vhn_p7b2/W0-PIS10005_minpath_report.txt -details minpath_tmp_vhn_p7b2/W0-PIS10005_minpath_details.txt -mps minpath_tmp_vhn_p7b2/W0-PIS10005_minpath.mps
```
I tried running just the subcommand from the above snippet's last line but couldn't get any verbose output about glpsol either:
```
(...truncated)
>>>pathway-1007[1008; PWY0-781] fam=25 unique-fam=0
pathway-1008[1009; SULFATE-CYS-PWY] fam=9
>>>pathway-1008[1009; SULFATE-CYS-PWY] fam=9 unique-fam=0
now write mps file..
original ortholog=712 found-in-the-fam-list=440 found-in-the-fam-mapped-to-pathway=440
End of PrintMPS
Error when running glpsol from MinPath.
```
I seem to be stuck at around the same point as my first comment above https://github.com/picrust/picrust2/issues/7#issuecomment-384883520 .
I found a related thread in HUMANn Google group: https://groups.google.com/forum/#!msg/humann-users/MSVmXC7DSW0/10SnjM3HCQAJ which says the solution is to update glpsol. I wonder if glpsol is part of your repository? Also, `which glpsol` returned no results when picrust2-dev environment is activated or not. `find "*glpsol*"` under `~/miniconda2/envs/picrust2-dev` also returned no results.

Thanks a lot for following up on these bugs.
-Jamie

**Comment by gavinmdouglas** [comment]
Hey again,

Thanks for your patience with these bugs. Your trying the commands on a different system is really helpful :)

The issue is indeed that glpk needs to be installed. I added it to the dev-environment.yml so it will now be installed when you create the conda environment. You could also install it yourself elsewhere and it should work.


Best,

Gavin

**Comment by jjmmii** [comment]
Oh I see, I just found the respective libraries to install glpk on Ubuntu [here](https://askubuntu.com/questions/349582/installing-and-running-glpk). Anyway it's good that you put it into the environment.
After solving this, I successfully ran PICRUSt2 through all 4 steps! 😃  Thank you very much!! 😄
