### ISSUE TITLE
Problems with qiime picrust2 custom-tree-pipeline

### ISSUE THREAD

**Issue by BadProgrammerr** [picrust/picrust2#72]
I was trying out the q2-picrust2 Tutorial (from https://github.com/picrust/picrust2/wiki/q2-picrust2-Tutorial).
I got through the first part but got stuck at the **qiime picrust2 custom-tree-pipeline** command...

The feedback from the command is as followed:
Error running this command:
hsp.py -i 16S -t /tmp/tmp1fyg7g9t/placed_seqs.tre -p 1 -n -o /tmp/tmp1fyg7g9t/picrust2_out/16S_predicted -m mp

I am using the QIIME2 in a VirtualBox.
How should I fix it...?
Thanks in advance!!

**Comment by gavinmdouglas** [comment]
Hi @BadProgrammerr ,

Just to double-check - did you use the reference files specified in the tutorial for the read placement step? If you use the default SEPP files then this command will fail.

If that's not the problem could you send me your input files privately at gavinmdouglas[AT]gmail[DOT]com?

**Comment by gavinmdouglas** [comment]
Closed due to inactivity.
