### ISSUE TITLE
Export denoised reads from QIIME to use in PICRUST

### ISSUE THREAD

**Issue by negin1986** [picrust/picrust2#76]
Hi,

Can I export feature-table from dada2 and analyzed in PICRUST plugin in QIIME and use in PICRUST to have more options or should I use close-reference reads? Currently, I can only see how many pathways and what pathways we have but there is no information about which samples or which species have how many of which pathways so the information is very limited in PICRUST plugin in QIIME.

**Comment by gavinmdouglas** [comment]
Hey,

Yes you can use your DADA2 output with PICRUSt2.

If you're referring to the summary file created by ```qiime feature-table summarize``` yes this isn't a useful file for analyses, it only gives you a quick breakdown of the data. You can analyze the data like any feature table (including exporting it as a BIOM):

```qiime tools export --input-path q2-picrust2_output/pathway_abundance.qza --output-path pathabun_exported```

And you could convert this to a plaintext file if you preferred analyzing it that way:

```
biom convert -i pathabun_exported/feature-table.biom -o pathabun_exported/feature-table.biom.tsv --to-tsv
```

I think you'll find the output of those commands is what you were expecting.

**Comment by negin1986** [comment]
Hi Gavin,

Thanks for your response. After I convert qza files to biom files, what kind of analysis can I run in picrust? I thought I had to use raw files for "Normalize By Copy Number", "Predict Metagenome",
"Categorize by function". Output files from qiime seem to have already predicted the pathways but there is no link between these pathways and host samples these microbes come from. How can I get that info and what kind of analysis can I do using files from qiime picrust plug in to get meaningful results?

**Comment by gavinmdouglas** [comment]
The output files by the QIIME2 plugin are the final output files (i.e. they are similar to what would have been outputted by those three PICRUSt1 commands you mentioned).

The BIOM file should be a table with pathways/functions as rows and samples as columns - is that what you are looking for?

There are many possible analyses you could perform. Figuring out the best analyses methods for microbiome feature data is an open area and the best approach will depend on what your question is. For instance, if you're interested in finding predicted functions at differential abundance between two sample groupings you could convert the output table to relative abundance (i.e. to percentages) and then perform Wilcoxon tests to identify significant features. This could be done in R or a software such as STAMP (http://kiwi.cs.dal.ca/Software/STAMP).
