### ISSUE TITLE
Running tutorial with this command

### ISSUE THREAD

**Issue by bmillerlab** [picrust/picrust2#80]
Hello, I tried running the tutorial command as listed for place_seqs.py and it gives this usage error message:

$ place_seqs.py -s dna-sequences.fasta -o placed_seqs.tre -p 2 --print_cmds
usage: place_seqs.py [-h] -s PATH [-r PATH] -o PATH [--threads THREADS]
                     [--intermediate PATH] [--chunk_size CHUNK_SIZE]
                     [--print_cmds] [-v]
place_seqs.py: error: unrecognized arguments: -p 2

It runs fine without the -p option, but the detailed page on the command does say this should work.

**Comment by gavinmdouglas** [comment]
Hey @bmillerlab - the `-p` option was swapped in for the most recent PICRUSt2 version 2.1.3-b. You can use the `--threads` option with older versions of that script.
