### ISSUE TITLE
mapping description to pathways

### ISSUE THREAD

**Issue by chassenr** [picrust/picrust2#83]
Hi,
I noticed that the last step in the picrust2 pipeline (mapping the description to the pathways, using the default files) returns descriptions which are not on metacyc anymore, but have been updated, e.g. ARGORNPROST-PWY, BRANCHED-CHAIN-AA-SYN-PWY, CATECHOL-ORTHO-CLEAVAGE-PWY, CHLOROPHYLL-SYN, COA-PWY, COBALSYN-PWY. At the moment, I am manually updating the pathway description, but I would really appreciate it if you knew of a faster way to do this. 
Btw: Is there a way to include the higher-level grouping of the metacyc pathways in the description?

Thanks!

Cheers,
Christiane

**Comment by gavinmdouglas** [comment]
Hey @chassenr,

Thanks for pointing this out. I don't know of any faster way to make those changes unfortunately. The MetaCyc files were taken from HUMAnN2 and I haven't looked into whether MetaCyc has an API or another easy way to acquire the pathways.

I can look into adding the higher-level groupings to a future release, but currently this information isn't found in any of the description files.


Best,

Gavin

**Comment by chassenr** [comment]
Hi Gavin,
thanks for the quick reply. I am fairly new to metacyc so I am not yet familiar with all the analysis options that they offer. I found out however (after posting my question), that apparently once you create a (free) account you can download a list of all pathways (description and ID) from so called smart tables. As luckily the pathway IDs apparently stayed the same, I was able to re-map the pathway descriptions. 

Cheers,
Christiane

**Comment by gavinmdouglas** [comment]
That's good to know! Did the developers say whether only the descriptions of the pathways and not the underlying definition changed? (e.g. that the key reactions for the pathways were still the same).

Best,

Gavin

**Comment by chassenr** [comment]
Thanks for pointing this out. Unfortunately, I don't know. 
However, after your comment I checked one of the pathways (autoinducer AI-2 biosynthesis II (Vibrio)), which I was pretty sure should be detected in my data set (given that I have more than 50% reads affiliated with Vibrio). In the pathway output this pathway was not represented (also when I ran pathway_pipeline.py with --skip_minpath). I then checked the EC output for the enzymes, which according to metacyc are involved in this pathway, and all of them were there. 
I then looked for one specific enzyme (EC:4.4.1.21) in the picrust mapping files. According to metacyc, this enzyme is part of 4 different pathways, and only one of these affiliations is included in the picrust mapping files. Is it possible that the some of the recent updates to metacyc are not yet included in picrust?

Cheers,
Christiane

**Comment by gavinmdouglas** [comment]
It's definitely possible that new changes are in the MetaCyc database that aren't in PICRUSt2. However, in the case of that pathway (autoinducer AI-2 biosynthesis II (Vibrio)) predictions aren't output for it since it was filtered out of the HUMAnN2 structured pathway database. From the HUMAnN2 paper, these are the two conditions under which pathways were excluded:

> (i) if they contained less than four quantifiable reactions (reactions associated with level 4 EC numbers, which are in turn associated with UniRef90 and UniRef50 families) or (ii) if they included 10% unquantifiable reactions (unquantifiable reactions in otherwise acceptable pathways were flagged as “optional” in the structured pathway syntax).


I believe both conditions were met for this pathway, at least with the EC to MetaCyc reaction mapping files used at the time. This might be true for the other pathways that EC number is involved in as well. The motivation for excluding these pathways is that hopefully it will reduce the number of false positives since inferring the presence and abundance of pathways is unreliable when based on an incomplete set of reactions.

Best,

Gavin

**Comment by chassenr** [comment]
My bad. Sorry for not checking the references carefully. Thanks for your explanation. 

Cheers,
Christiane
