### ISSUE TITLE
bioconda install issues

### ISSUE THREAD

**Issue by mortonjt** [picrust/picrust2#84]
When I try to conda install picrust within a qiime2-2019.4 environment and try to run it, I get the following error

```
Error: File existence/permissions problem in trying to open HMM file /Users/jmorton/miniconda3/envs/qiime2-2019.4/lib/python3.6/site-packages/default_files/prokaryotic/reference.hmm.
HMM file /Users/jmorton/miniconda3/envs/qiime2-2019.4/lib/python3.6/site-packages/default_files/prokaryotic/reference.hmm not f

Error running this command:
hmmalign --trim --dna --mapali /Users/jmorton/miniconda3/envs/qiime2-2019.4/lib/python3.6/site-packages/default_files/prokaryotic/reference.fna --informat FASTA -o results/picrust_out_pipeline/intermediate/place_seqs/query_align.stockholm /Users/jmorton/miniconda3/envs/qiime2-2019.4/lib/python3.6/site-packages/default_files/prokaryotic/reference.hmm data/seqs.fa
(qiime2-2019.4) C02XW0D4HX8F:american-gut jmorton$ rm -r
.DS_Store    data/        ipynb/       picrust.sh   picrust.sh~  results/
(qiime2-2019.4) C02XW0D4HX8F:american-gut jmorton$ rm -r results/picrust_out_pipeline/
(qiime2-2019.4) C02XW0D4HX8F:american-gut jmorton$ Error: File existence/permissions problem in trying to open HMM file /Users/jmorton/miniconda3/envs/qiime2-2019.4/lib/python3.6/site-packages/default_files/prokaryotic/reference.hmm.
```

From a first glance, it doesn't look like the reference.hmm was downloaded - is this expected?

Note that the downloading from source works just fine.

**Comment by gavinmdouglas** [comment]
Hey @mortonjt,

The database files are meant to be installed through bioconda as well. This is done through a "post link" bash script to prevent large files being backed up in the bioconda source repository. You can see the post link script [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/picrust2/post-link.sh).

It's supposed to move the default files to a folder called "picrust2". In my QIIME2 environment it's installed in: `/home/gavin/local/miniconda3/envs/qiime2-2019.4/lib/python3.6/site-packages/picrust2/default_files/`. All of the Python code is also in that `picrust2` directory on my system. 

Could you check if the `picrust2` folder exists in `site-packages` (and if that's where the code is) or alternatively if you received an error when installing the package through conda?

Also, could you let me know what system you're running?

Thanks,

Gavin

**Comment by mortonjt** [comment]
Hi @gavinmdouglas .  I double checked the install, it seems to work if I create a new conda environment like the wiki installation instructions recommended.

This build fails if I try to install in an existing environment (i.e. a qiime2-2019.4 environment) - but as noted before, the workaround is to install from source within the qiime2 environment.

I'm not sure if this is an outstanding problem - so I'm going to close this issue for now.
