### ISSUE TITLE
Otu table from FROGS to use in PICRUSt

### ISSUE THREAD

**Issue by najouamghazli** [picrust/picrust2#85]
Hello,

I'm new to PICRUSt and I need your help.

I have used [FROGS](https://github.com/geraldinepascal/FROGS) for my bioinformatic analysis, and now I want to use PICRUSt. FROGS generate .tsv and .biom files but PICRUSt doesn't seem to read my tables. After that, I manually modified my OTU table just to see if it works, then I got thie erreor message:

```
(picrust2) mghazli@Mghazli-VirtualBox:~$ picrust2_pipeline.py -s ~/PICRUSt2/05-filters.fasta -i ~/PICRUSt2/SelfGeneratedOtu.tsv -o ~/PICRUSt2/picrust2_out_pipline
Stopping - no ASV ids overlap between input FASTA and sequence abundance table
```
My Fasta file looks like this:

```
>M03493:145:000000000-BRT22:1:2112:28400:16960;size=1 1:N:0:1 
CCGCGGTAAGACAAAAAGGGCGACCCATCGGAGTTTTAAATCGGTGTAAAGGATACGTAGCCGGCCTGTCGACTTTTTTACAAAAGAGGGCTAGAGTCAAATAGAGAAATTAACAATACCTAGAGTAGGGCTGATATCTTATCATACTAGGGGGAGAGCTAAAGGCGAAGGCATGATTCTAGGTAATGACTGACGGTGAGGTATGAAGGCTAGGGTAGCGATAGGGATTAGATACCCGGG
>M03493:145:000000000-BRT22:1:1113:9009:22133;size=2 1:N:0:1 
CCGCGGTAAGACAAAAAGGGCGACCCATCGGAGTTTTAAATCGGTGTAAAGGATACGTAGCCGGCCTGTTGACTTTTTTACAAAAGAGGGCTAGAGTCAAATAGAGGAATTAACAATACCTAGAGTAGGGCTGATATCTTATCATACTAGGGGGAGAGCTAAAGGCGAAGGCATGATTCTAGGTAATGACTGACGGTGAGGTATGAAGGCTAGGGTAGCGATAGGGATTAGATACCCCAG
```

My OTU table looks like this:

> #OTU_ID | 35 | 36 | 37 | 38 | 39
> -- | -- | -- | -- | -- | --
> M03493:145:000000000-BRT22:1:1101:17556:3320 | 0.00834402679102375 | 0.00550843479077337 | 0.094034615504992 | 0.123770773997684 | 0.0344684047447654
> M03493:145:000000000-BRT22:1:1101:15161:1686 | 0.080463965788681 | 0.0887007385050947 | 0.0482172454368339 | 0.0615509942442008 | 0.0171620452599606

I'll appreciate your help.

Best

**Comment by gavinmdouglas** [comment]
Hi there,

The FASTA and OTU table need to have exactly the same sequence ids. The FASTA will need to have just 1 field per headerline as well. You can see example input files in the tutorial: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.1.4-beta)

It may be easiest to create your own ids, e.g. "sequence1", "sequence2", etc.

Best,

Gavin
