### ISSUE TITLE
Suggestion: include quality control in the PICRUSt2 documentation

### ISSUE THREAD

**Issue by yanxianl** [picrust/picrust2#87]
Hi,

Thanks for developing the PICRUSt2 and congrats on the release of the preprint!

One thing that the PICRUSt1 documentation has done really well than its counterparts was to include a quality control section, specifying the limits of the tool and highlighting the warnings. Could you also include a quality control section for the PICRUSt2?  

Cheers,
Yanxian

**Comment by gavinmdouglas** [comment]
Hi @yanxianl,

Thanks! I've been meaning to emphasize some of the limitations in particular, thanks for the reminder. The main points are largely what is on the PICRUSt1 website, but I'll aim to add more details over time. You can see the new pages here:
https://github.com/picrust/picrust2/wiki/Key-Limitations
https://github.com/picrust/picrust2/wiki/Validation-with-paired-metagenomes


Best,

Gavin

**Comment by yanxianl** [comment]
Hi Gavin,

Thanks for pointing to the relevant wiki pages. They're really helpful in guiding users to use the tool wisely. Most documentations of bioinformatic tools do not contain such a section, which can lead to wrong applications and generate flawed results.

Again, nice work!

Yanxian

**Comment by gavinmdouglas** [comment]
Thanks for the feedback Yanxian!

Best,

Gavin
