### ISSUE TITLE
Missing default files

### ISSUE THREAD

**Issue by vinisalazar** [picrust/picrust2#88]
Hi, 

I've successfully built PICRUst2 but I've noticed that it does not come with the default files. When I try to run `picrust2_pipeline.py` or even `place_seqs.py` I get the following:

```
No FASTA file found in specified directory. Expected to find one of:
/home/ubuntu/.miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna.gz
/home/ubuntu/.miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fasta.gz
/home/ubuntu/.miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna
/home/ubuntu/.miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fasta


In addition to the missing FASTA file, the following expected file(s) could not be found:
/home/ubuntu/.miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.tre
/home/ubuntu/.miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.hmm
/home/ubuntu/.miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.model


Error - missing at least one of the four reference files in this specified directory: /home/ubuntu/.miniconda3/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/pro_ref
```

I expected the default reference files to come along with the installation. Is there a easy way to obtain them? I had a look through your wiki and could find [this page](https://github.com/picrust/picrust2/wiki/Sequence-placement) which details how to build a custom reference file, but I couldn't find the "default ones".

Thank you for any assistance you can provide,

sincerely,

V

**Comment by gavinmdouglas** [comment]
Hi @vinisalazar, 

The default files should have been installed as well so something went wrong with the conda installation. A few other users have also run into this issue and fixed it by installing PICRUSt2 from source.

So far I haven't been able to reproduce this problem. Could you let me know your operating system and version of Python and miniconda?

Thanks

**Comment by vinisalazar** [comment]
Hi @gavinmdouglas,

thank you very much for the prompt response. I'm using `Ubuntu 18.04.2 LTS`,  `Python 3.6.7` and `conda 4.6.14`.

Building from source seems to have fixed it. My suspicions is that those files are not included in your conda recipe, therefore the conda installation doesn't include them? I would suggest you to check that. I will be closing the issue for now.

Sincerely,

V

**Comment by GodloveD** [comment]
I'm experiencing the same issue with v2.4.2.  I've tried installing it with conda and it spins forever (I've left it overnight) trying to resolve the environment.  Then I've installed it with mamba instead, which works, but then the program complains about the missing files mentioned by @vinisalazar.  Then I've installed the package from source as suggested in the instructions and I get the same error.  Where are these files?  At this point I'd be happy to just copy them in manually if it will work.

**Comment by gavinmdouglas** [comment]
Hi @GodloveD,

That's odd, the files are downloaded with the source repo and should be when installed with conda as well. You can find them in this sub-folder of the repo: ```picrust2/default_files```.


Cheers,

Gavin

**Comment by GodloveD** [comment]
So I performed the following after installation and now things seem to be working as expected:
```
cp -r picrust2/default_files \
        /opt/conda/envs/picrust2/lib/python3.8/site-packages/picrust2/
```
How exactly are those files supposed to be installed into the installation tree?  Should there be some mention of `default_files` in [`setup.py`](https://github.com/picrust/picrust2/blob/master/setup.py)?  I don't see it there, but I'm also no python expert.
