### ISSUE TITLE
Genome annotations in qiime2

### ISSUE THREAD

**Issue by mortonjt** [picrust/picrust2#89]
One thing that would be really cool if there was a way to build qiime2 transformers for the genome annotations (see this post for [more details](https://forum.qiime2.org/t/how-to-output-metadata-as-an-artifact/10338)).  It could help link genome exploration across multiple statistical analyses / visualizations (see mmvec biplot [here](https://github.com/biocore/rhapsody))

This shouldn't be too bad to do - will be happy to possibly contribute.

**Comment by gavinmdouglas** [comment]
Sounds useful, thanks for the suggestion! I'll have to take a look at the example transformer referenced in the first link to know how easy it will be to implement, but I'm definitely interested.
