### ISSUE TITLE
ValueError: This input file was not found: ./picrust_tutorial_out/EC_metagenome_out/seqtab_norm.tsv

### ISSUE THREAD

**Issue by erimjr** [picrust/picrust2#90]
Hi,
I'm trying to run the tutorial data using the pipeline command on a cluster. I've attached my submission script so you can see it. 
The pipeline seems to be running fine but I get an output error (below). From the error and the output files it looks to me like the  --per_sequence_contrib flag is trying to call seqtab_norm.tsv but the output from the metagenome_pipeline.py command is gzipped, but I don't know much about these things.
Could you help me to resolve this?
Thanks so much!

--------
0 of 37 ASVs were above the max NSTI cut-off of 2.0 and were removed.

0 of 37 ASVs were above the max NSTI cut-off of 2.0 and were removed.

Error running this command:
pathway_pipeline.py --input ./picrust_tutorial_out/EC_metagenome_out/pred_metagenome_unstrat.tsv.gz --out_dir ./picrust_tutorial_out/pathways_out --map /home/svu/erimjr/.conda/miniconda/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/pathway_mapfiles/metacyc_path2rxn_struc_filt_pro.txt --intermediate ./picrust_tutorial_out/intermediate/pathways --proc 20 --regroup_map /home/svu/erimjr/.conda/miniconda/envs/picrust2/lib/python3.6/site-packages/picrust2/default_files/pathway_mapfiles/ec_level4_to_metacyc_rxn.tsv --per_sequence_contrib --per_sequence_abun ./picrust_tutorial_out/EC_metagenome_out/seqtab_norm.tsv --per_sequence_function ./picrust_tutorial_out/EC_predicted.tsv.gz

Standard output of failed command:
""

Standard error of failed command:
"Traceback (most recent call last):
  File "/home/svu/erimjr/.conda/miniconda/envs/picrust2/bin/pathway_pipeline.py", line 211, in <module>
    main()
  File "/home/svu/erimjr/.conda/miniconda/envs/picrust2/bin/pathway_pipeline.py", line 169, in main
    print_cmds=args.print_cmds)
  File "/home/svu/erimjr/.conda/miniconda/envs/picrust2/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 311, in pathway_pipeline
    check_files_exist([per_sequence_abun, per_sequence_function])
  File "/home/svu/erimjr/.conda/miniconda/envs/picrust2/lib/python3.6/site-packages/picrust2/util.py", line 377, in check_files_exist
    raise ValueError("This input file was not found: " + missing_files[0])
ValueError: This input file was not found: ./picrust_tutorial_out/EC_metagenome_out/seqtab_norm.tsv
"
      ======================================================================================
      Resource Usage on 2019-06-25 13:56:07.244866:
      JobId: 1031332.venus01  				 Project: picrust_tutorial 
      Submission Host: atlas8-c01.hpc.local 
      Exit Status: 1
      NCPUs Requested: 20 				 NCPUs Used: 20
      Memory Requested: 64gb 				 Memory Used: 10575016kb 
      Vmem Used: 37141788kb
      CPU Time Used: 00:19:55 
      Walltime requested: 240:00:00 			 Walltime Used: 00:08:58
      Submit Time:  Tue Jun 25 13:08:21 2019 		 Start Time: Tue Jun 25 13:47:08 2019 
      End Time: Tue Jun 25 13:56:07 2019 
      Execution Nodes Used: (atlas9-c22:ncpus=20:mem=67108864kb)
      ======================================================================================

[picrust_pbs_template.txt](https://github.com/picrust/picrust2/files/3324019/picrust_pbs_template.txt)

**Comment by gavinmdouglas** [comment]
Hey @erimjr ,

Thanks a lot for reporting this error. It looks like this is a bug due to how I changed the intermediate files to be gzipped in the last update. For now you can run the `pathway_pipeline.py` command reported above, but add ".gz" to `./picrust_tutorial_out/EC_metagenome_out/seqtab_norm.tsv`.


Best,

Gavin

**Comment by gavinmdouglas** [comment]
Note that this bug is now fixed in the latest developmental version.

**Comment by erimjr** [comment]
Hi Gavin,
Thanks so much! I always worry that I haven't looked hard enough for an answer in the documentation or on the web, so it's nice to know I haven't just screwed something up :)
I'll try to get the administrators of our cluster to install your update, but they usually don't like installing developmental versions. 
In the meantime, for your suggestion, I don't see that option in the pipeline command? Do you mean I should edit the script itself? I'm not sure I'm up to that :)

When I open the script and see usage examples I can see one that says:
Map EC numbers to MetaCyc pathways and get stratified output corresponding to contribution of predicted gene family abundances within each predicted genome:
pathway_pipeline.py -i EC_metagenome_out/pred_metagenome_unstrat.tsv.gz -o pathways_out_per_seq --per_sequence_contrib --per_sequence_abun EC_metagenome_out/seqtab_norm.tsv.gz --per_sequence_function EC_predicted.tsv.gz

So do you mean that in my submission script the command might look like this:

picrust2_pipeline.py -s seqs.fna -i table.biom -o ./picrust_tutorial_out -p 20 --per_sequence_contrib 
--per_sequence_abun EC_metagenome_out/seqtab_norm.tsv.gz --per_sequence_function EC_predicted.tsv.gz --min_samples 1 --stratified --metagenome_contrib

And that would fix my problem? Thanks again for your really prompt attention and rapid resolution :)

**Comment by gavinmdouglas** [comment]
Hey again,

No you would want to use the `pathway_pipeline.py` script directly (which would not require installing the developmental version). The `picrust2_pipeline.py` script is a wrapper for several scripts described in this tutorial: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.1.4-beta). The command you will want to alter is the one after the "Error running this command:" message.


Best,

Gavin

**Comment by erimjr** [comment]
Hi!

Thank you again for your quick response!
I think I understand now. You're saying that if I run the steps of the picrust2_pipeline.py wrapper individually (basically by following the workflow tutorial step by step instead of with the wrapper), when it's time to pathway_pipeline.py I can change ~/seqtab_norm.tsv to ~/seqtab_norm.tsv.gz and that should do it. Is that correct?
Since it's all modular, I guess I could also just start from pathway_pipeline.py with the outputs i've already got? Since I'm trying to set up a pbs submission script i can use in the future, I think I'll try to start again from scratch though. 
Thanks again for all of your help!

**Comment by erimjr** [comment]
Ok that's got it for me! Thanks so much 👍 I'm going to close this thread.

**Comment by gavinmdouglas** [comment]
Hi @erimjr, yes that's correct - the pipeline is modular so you could run the pathway_pipeline.py step after running all other parts of the picrust2_pipeline.py script.

Gavin
