### ISSUE TITLE
Stopping - no ASV ids overlap between input FASTA and sequence abundance table

### ISSUE THREAD

**Issue by Eve-Cheung** [picrust/picrust2#92]
There is a warning "Stopping - no ASV ids overlap between input FASTA and sequence abundance table" when putting files produced by QIIME1. I have no idea about how to do next. Please help me .

**Comment by gavinmdouglas** [comment]
Hey @Eve-Cheung,

Example input files are described in the tutorial: https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.1.4-beta)#download-data. This FAQ may also be related to your issue: https://github.com/picrust/picrust2/wiki/Frequently-Asked-Questions#how-can-i-restrict-a-fasta-file-to-be-the-first-field-per-line

Please let me know if that resolves your issue or not!

Gavin

**Comment by Eve-Cheung** [comment]
Gavin, thank you! I have worked out above problem after made my fasta file have single field per header-line (awk '{print $1 }' FASTA_IN > FASTA_OUT). It's so nice of you~

**Comment by DharitriSaikia** [comment]
Hello Sir, @gavinmdouglas 
I am facing the same problem: "Stopping - no ASV ids overlap between input FASTA and sequence abundance table." while running run 'picrust2_pipeline.py' . I am using DADA2 (qiime2-2019.10) output files (i. e., dna-sequence.fasta and feature-table.biom converted to tab delimited file) as input.
I have also tried to run the tutorial data set but got the same error. 
Installed version is picrust2=2.3.0_b. Looking forward for your suggestion. Thanks.

**Comment by gavinmdouglas** [comment]
Hi @DharitriSaikia, the files must be malformed or the ASV ids truly don't match. I can confirm that the tutorial files do work with v2.3.0-b - perhaps there was an issue downloading these files? Could you post the beginning of each of the files you're trying to input?


Best,

Gavin

**Comment by DharitriSaikia** [comment]
Thanks for your reply.
I have attached the beginning of the input files here. Another important issue is when I give the table.biom as input, it gives another error. I'm even unable to view any biom file using biom head command. So, I converted it to tab delimited format and got the no overlapping ASV id error. I am completely clueless where is the root of the problem. I have tried reinstalling the software too.
Please find the attachments for details of the input files and the error messages.
Hope this helps you to find it 
![Details--version](https://user-images.githubusercontent.com/60462206/73462019-22bf9d00-43a1-11ea-8b73-219ddfb95c3e.png)
![Error_table-biom](https://user-images.githubusercontent.com/60462206/73462020-22bf9d00-43a1-11ea-8305-2113f0e32b9e.png)
![error-table-txt](https://user-images.githubusercontent.com/60462206/73462021-22bf9d00-43a1-11ea-9c6d-15d5f49c9fdb.png)
![error-biom-head](https://user-images.githubusercontent.com/60462206/73462023-23583380-43a1-11ea-8bb3-f7d5687c64b0.png)
![less-table-txt](https://user-images.githubusercontent.com/60462206/73462024-23583380-43a1-11ea-8fb1-bc8a2d5c4a8a.png)
![less-seq-fna](https://user-images.githubusercontent.com/60462206/73462025-23f0ca00-43a1-11ea-9e2a-864d90c735f5.png)

Best regards,
Dharitri

**Comment by gavinmdouglas** [comment]
Hi @DharitriSaikia,

First, you're not actually running the tests - you'll need to download the entire source to run the tests with `pytest`. Make sure you're in the source folder when running `pytest` as described here: https://github.com/picrust/picrust2/wiki/Installation#install-from-source (you don't need to re-install the tool or create a new conda environment).

It looks like for some reason you can't open H5DF files on your system, which is unusual. Either way, if you remove the line "#Constructed from a BIOM file" and change the first column name from "#OTU ID" to "OTU_ID" I think it will probably work.

Best,

Gavin

**Comment by DharitriSaikia** [comment]
Hello, @Gavin Douglas It worked after removing "#Constructed from a BIOM file" and changing the first column name from "#OTU ID" to "OTU_ID".
Thanks a lot. 🙂
