### ISSUE TITLE
Running more cores with place_seqs.py using -p

### ISSUE THREAD

**Issue by bmillerlab** [picrust/picrust2#93]
Hello, I asked about this command a while back while running the tutorial since it wouldn't run and you mentioned it was a replacement for --threads in the new version of picrust2.  I am now using the new v2.1.4 beta on my own data and this still isn't working, so this step is taking an insane amount of time.  I have tried using the --threads command just in case, but it isn't recognized.

Is there a new command in this version of picrust2?

Thank you.

**Comment by gavinmdouglas** [comment]
Hey @bmillerlab,

That's strange that the `-p` option isn't working since it is implemented in that version. What's the exact command you're running and what is the error? You should be able to see the option listed if you type `place_seqs.py --help`.

One thing to watch out for is if you copying the command from a website you may need to re-type it if your terminal isn't interpreting the `-` characters correctly.

Another likely issue could be related to your installation. If the above doesn't fix your problem, how did you install the tool and is it installed in a fresh conda environment?

Thanks,

Gavin

**Comment by bmillerlab** [comment]
Hi, It doesn't give an error it just runs on one thread which is very slow.  I just went back and tried it with the tutorial data and typed in the -p to make sure the character was read correctly, just in case, but that didn't matter.  Of course, the tutorial runs relatively quickly because it is a small dataset.  

I used the bioconda method from your wiki:

conda create -n picrust2 -c bioconda -c conda-forge picrust2

and I'm in a fresh conda environment.  I am running conda v4.6.14 though because when I updated to the latest version a few days ago I began to have a ton of problems.  Maybe that is the reason?

Oh, the command I'm using is straight from the tutorial:

place_seqs.py -s dna-sequences.fasta -o out.tre -p 8

**Comment by bmillerlab** [comment]
Oh, I did try using --processes and that did give an error that it was unrecognized.  

place_seqs.py: error: unrecognized arguments: --procresses 4

**Comment by gavinmdouglas** [comment]
Hey @bmillerlab,

Updating to the latest version of conda shouldn't be related to this issue.

I think the confusion here is probably that not all steps in the `place_seqs.py` pipeline can be run in parallel (e.g. the hmmalign step and the first steps of EPA-NG). This command can take a really long time depending on the number of input ASVs (esp. if you're in the range of >10,000 ASVs).

Hmm `--processes` is recognized correctly with v2.1.4-b. In the unedited comment it looks like you typed `--procresses` - could that be the issue or was that just when you were responding on here?

**Comment by bmillerlab** [comment]
Hi, Yes I was running more ASVs than that.  Also, I checked and did make a typo in processes.  I thought I made it when I copied the command into a file later.  Maybe for future users you could mention that part of this pipeline doesn't run in parallel and so it can take a long time - it took over 3 hours to complete on my computer because of that.  The next command, hsp.py, runs in minutes with on the dataset with parallel processes.

By the way, I really appreciate the additional detailed explanations you have linked into the tutorial pages now.  They are really helpful for those of us who aren't experts and don't have anybody to ask anything.  I got thrown to the wolves on this project which is based on scoring gut microbes using 16s, which NOBODY has done before in my department.  Thanks for taking the time to develop such a helpful guide.
