### ISSUE TITLE
Metagenome_pipeline.py is not reading the full biom table I enter, plus warning (online search indicates it is due to panda)

### ISSUE THREAD

**Issue by bmillerlab** [picrust/picrust2#94]
Hello, Thanks for help with the last problem and now I've run into a new one.  I am getting this error running metagenome_pipeline.py

sys:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.

The pipeline seems to complete and gives all the output files, but the output only includes a small subset of my actual dataset. I looked up the error message and found this happens when changing data  types in their columns, but this is a normal biom file that will run in programs like qiime2.  

Is this because my file is much bigger than the tutorial biom example or is it because my OTU IDs are numbers?  I compared my biom file and it looks the same as that one. Here is what is output for the head of the file:

$ biom head -i otu_biom.biom
# Constructed from biom file
#OTU ID	JSMat4	BSF2	BSF4	BSF5	BSF6
110001	0.0	6.0	36.0	122.0	18.0
81400	0.0	0.0	0.0	0.0	0.0
266048	0.0	0.0	108.0	227.0	278.0
266914	49.0	0.0	0.0	0.0	0.0
547497	0.0	0.0	0.0	0.0	0.0

**Comment by gavinmdouglas** [comment]
Sorry you're running into this problem, that definitely sounds like a bug, but I'm not sure exactly what's causing the problem. Would you mind sending me your input file to me at this email?
![gmail_screenshot](https://user-images.githubusercontent.com/12489683/61306000-33704300-a7c2-11e9-9cae-437a240f02a8.jpg)

It's possible that this problem only comes up when the OTU IDs are mixed strings and numbers and the file is large, but I'll have to troubleshoot the file.

**Comment by gavinmdouglas** [comment]
Thanks for sending me the file. I could reproduce the warning, which I'll fix in the upcoming release.

However, the output files I produced were the correct size - what file are you referring to when you say it was only a subset of your data and in what way?

Thanks,

Gavin

**Comment by bmillerlab** [comment]
Hi, When I run the file and look at the output (it does output all the files) it only has 10 of the 30,000+ OTUs in the seqtab_norm file and only those 10 are considered for the other output files.  Also in the weighted_nsti file there are only a few samples with values and the pred_metagenome_unstrat file is almost all 0's.  I will send you those files by email.

I went ahead and ran a comparison for output against my original biom table (that I did not edit to remove the negative controls) and I get the same error I sent before but I also get the full output in the files, with all the OTU's and samples being scored.  So now I guess that somehow when I edit the file in Rstudio to remove the negative controls something else must happen to the format of the biom table, either in that step or when I reformat into biom. 

I will try and do the edit in qiime2 and see if I can get a biom file that will run in picrust2 since I have limited skills in Rstudio and I don't know how to troubleshoot this - especially since I went ahead and used the edited biom file in qiime2 and it runs in there perfectly well though it is failing in picrust2.  Unless you have any other suggestions?

**Comment by gavinmdouglas** [comment]
For future reference we think this problem was due to the input BIOM and FASTA file containing only a small number of overlapping OTU ids.

Also the pandas warning about different object types should be resolved in the upcoming v2.2.0-b release.
