### ISSUE TITLE
Pathway prediction error

### ISSUE THREAD

**Issue by songb1230** [picrust/picrust2#95]
HI Gavin

I installed a latest version of PICRUSt2 and ran the samples that worked before with older version of PICRUSt2. I can get a predicted metagenome data with KO and EC numbers but there is no description of the gene and enzymes in the metagenome file.

I am sharing the error message that I got from the latest run:

(picrust2b) bash-4.2$ picrust2_pipeline.py -s WMWater16S.fasta -i WMWater16S.biom -o WMWater2 \--threads 16 
2679 of 2679 sequence ids overlap between input table and FASTA.

171 of 2679 ASVs were above the max NSTI cut-off of 2.0 and were removed.

171 of 2679 ASVs were above the max NSTI cut-off of 2.0 and were removed.

Error running this command:
pathway_pipeline.py --input WMWater2/EC_metagenome_out/pred_metagenome_unstrat.tsv --out_dir WMWater2/pathways_out --map /ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/picrust2/default_files/pathway_mapfiles/metacyc_path2rxn_struc_filt_pro.txt --intermediate WMWater2/intermediate/pathways --proc 16 --regroup_map /ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/picrust2/default_files/pathway_mapfiles/ec_level4_to_metacyc_rxn.tsv

STDOUT of failed command:

STDERR of failed command:
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 837, in unstrat_pathway_levels
    reaction_abun = unstrat_input[sample_id].to_dict(defaultdict(int))
TypeError: to_dict() takes 1 positional argument but 2 were given
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/ches/home00/songb/.conda/envs/picrust2b/bin/pathway_pipeline.py", line 196, in <module>
    main()
  File "/ches/home00/songb/.conda/envs/picrust2b/bin/pathway_pipeline.py", line 154, in main
    print_cmds=args.print_cmds)
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/picrust2/pathway_pipeline.py", line 427, in pathway_pipeline
    for sample_id in samples)
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/ches/home00/songb/.conda/envs/picrust2b/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: to_dict() takes 1 positional argument but 2 were given

**Comment by gavinmdouglas** [comment]
Hey @songb1230,

First, the descriptions are no longer added automatically by the pipeline script, so they are expected to be missing.

This error seems to be related to incompatible versions of the joblib / concurrent Python packages although I'm not sure. Can you confirm that this is v2.1.4-b installed in a fresh conda environment? Also, did you install this from bioconda? Lastly, would you mind reporting the output of `conda list`?

Thanks,

Gavin

**Comment by songb1230** [comment]
The list of python packages (see below) were installed in a fresh conda environment. The version and details of the packages (using conda list) are attached in the accompanying text file.

picrust2b was installed from bioconda and is version 2.1.1_b. joblib is installed from conda-forge and is version 0.13.1. Python itself is anaconda-3.6 distribution v4.4.0.

# packages in environment at /ches/home00/songb/.conda/envs/picrust2b:
#
_libgcc_mutex             0.1                        main  
_r-mutex                  1.0.1               anacondar_1    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
biom-format               2.1.7           py36h3010b51_1002    conda-forge
blas                      1.0                         mkl  
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.14.12              he6fea26_5    conda-forge
certifi                   2019.6.16                py36_0    conda-forge
click                     7.0                        py_0    conda-forge
coverage                  4.5.3            py36h14c3975_0    conda-forge
curl                      7.64.0               h646f8bb_0    conda-forge
epa-ng                    0.3.5                he860b03_0    bioconda
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h3cfcefd_1004    conda-forge
future                    0.17.1                py36_1000    conda-forge
gappa                     0.2.0                he860b03_0    bioconda
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
glpk                      4.65              ha14ba45_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.5                  h294904e_0    conda-forge
h5py                      2.7.0               np112py36_1    conda-forge
harfbuzz                  1.9.0                h08d66d9_0    conda-forge
hdf5                      1.8.18                        3    conda-forge
hmmer                     3.2.1                hf484d3e_1    bioconda
icu                       58.2              hf484d3e_1000    conda-forge
importlib_metadata        0.18                     py36_0    conda-forge
intel-openmp              2019.4                      243  
joblib                    0.13.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcurl                   7.64.0               h01ee5af_0    conda-forge
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
libopenblas               0.3.6                h6e990d7_4    conda-forge
libpng                    1.6.34               ha92aebf_2    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.9             h648cc4a_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_1    conda-forge
mkl                       2018.0.3                      1  
more-itertools            7.1.0                      py_0    conda-forge
ncurses                   5.9                          10    conda-forge
numpy                     1.12.1           py36he24570b_1  
openblas                  0.3.6                h6e990d7_4    conda-forge
openssl                   1.0.2r               h14c3975_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.22.0                   py36_1    conda-forge
pango                     1.40.14           h53a7087_1002    conda-forge
pcre                      8.39                          0    conda-forge
picrust2                  2.1.1_b                    py_0    bioconda
pip                       19.1.1                   py36_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pytest                    5.0.1                    py36_0    conda-forge
pytest-cov                2.7.1                      py_0    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
r-base                    3.4.1                         4    conda-forge
r-castor                  1.3.4            r341hfc679d8_0    conda-forge
r-naturalsort             0.1.3                  r3.4.1_0    conda-forge
r-rcpp                    1.0.0            r341h9d2a408_0    conda-forge
readline                  7.0                           0    conda-forge
scipy                     0.19.1           py36h9976243_3  
setuptools                41.0.1                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wget                      1.19.5               h1ad7b7a_0  
wheel                     0.33.4                   py36_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zipp                      0.5.1                      py_0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

**Comment by gavinmdouglas** [comment]
Hey @songb1230,

The latest version is PICRUSt2 2.1.4-b so you could try installing that version in a fresh conda environment to see if that fixes this issue.

**Comment by songb1230** [comment]
I installed 2.1.4.-b but still get the following error:

Error running this command:
hsp.py --tree NDSU2/out.tre --output NDSU2/marker_predicted_and_nsti.tsv.gz --observed_trait_table /ches/home00/songb/.conda/envs/picrust214b/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/16S.txt.gz --hsp_method mp --seed 100 --calculate_NSTI --processes 1

Standard output of failed command:
""

Standard error of failed command:
"Traceback (most recent call last):
  File "/ches/home00/songb/.conda/envs/picrust214b/bin/hsp.py", line 130, in <module>
    main()
  File "/ches/home00/songb/.conda/envs/picrust214b/bin/hsp.py", line 121, in main
    ran_seed=args.seed)
  File "/ches/home00/songb/.conda/envs/picrust214b/lib/python3.6/site-packages/picrust2/wrap_hsp.py", line 72, in castor_hsp_workflow
    predict_out_combined = pd.concat(predict_out_chunks, axis=1, sort=True)
TypeError: concat() got an unexpected keyword argument 'sort'
"

**Comment by gavinmdouglas** [comment]
Hi @songb1230,

Both errors you have run into are related to incompatible versions of the dependencies, which shouldn't happen when installing in a fresh environment since the correct dependency versions are specified exactly. Did you receive any warnings when installing PICRUSt2?

You can try running `conda clean --all` to clean up your conda install, which might help address this issue.

**Comment by songb1230** [comment]
My school IT tech did the clean up of condo and reinstalled picrust2.1.4b. No error for installation 

But when I did a test run, I got the same errors:

(picrust214b) bash-4.2$ picrust2_pipeline.py -s WMWater16S.fasta -i WMWater16S.biom -o WMWater4 -p 16

Error running this command:
hsp.py --tree WMWater4/out.tre --output WMWater4/marker_predicted_and_nsti.tsv.gz --observed_trait_table /ches/home00/songb/.conda/envs/picrust214b/lib/python3.6/site-packages/picrust2/default_files/prokaryotic/16S.txt.gz --hsp_method mp --seed 100 --calculate_NSTI --processes 1

Standard output of failed command:
""

Standard error of failed command:
"Traceback (most recent call last):
  File "/ches/home00/songb/.conda/envs/picrust214b/bin/hsp.py", line 130, in <module>
    main()
  File "/ches/home00/songb/.conda/envs/picrust214b/bin/hsp.py", line 121, in main
    ran_seed=args.seed)
  File "/ches/home00/songb/.conda/envs/picrust214b/lib/python3.6/site-packages/picrust2/wrap_hsp.py", line 72, in castor_hsp_workflow
    predict_out_combined = pd.concat(predict_out_chunks, axis=1, sort=True)
TypeError: concat() got an unexpected keyword argument 'sort'
"

**Comment by gavinmdouglas** [comment]
Hmm that's very strange. That option was added to the pandas function `concat` in pandas v0.23.0 and v0.24.2 is specifically required to install PICRUSt2 2.1.4-b. You can confirm what version of pandas is installed in the environment by typing `conda list`.

One possibility is that your python is pointing to a different python binary than what is installed in the `picrust214b ` miniconda environment. You can get at this by typing `which python` when the environment is activated. If this python was pointing to your base python for instance that could be related to this problem. Alternatively, if you have defined a bash variable like PYTHONPATH to point to a non-standard directory for Python libraries that might also be related to this issue.
