### ISSUE TITLE
Error running this command: hsp.py -i KO -t /tmp/tmpp3a9geq_/placed_seqs.tre -p 1 -o /tmp/tmpp3a9geq_/picrust2_out/KO_predicted -m mp

### ISSUE THREAD

**Issue by YakunWang-0125** [picrust/picrust2#99]
Hi, I'm very glad that you saw this question!
I installed the PICRUST2 plugin in Qiime2. In order to predict functional genes, run the following command:
qiime picrust2 custom-tree-pipeline --i-table table.qza \
--i-tree tutorial_placed_out/tree.qza \
--output-dir q2-picrust2_output \
--p-threads 1 \
--p-hsp-method mp \
--p-max-nsti 2
I got the error running this command:
hsp.py -i KO -t /tmp/tmpp3a9geq_/placed_seqs.tre -p 1 -o /tmp/tmpp3a9geq_/picrust2_out/KO_predicted -m mp
I tried to add --verbose after the above command. Unfortunately, it is invaild.

**Comment by gavinmdouglas** [comment]
Hey there,

How much RAM do you have? I would guess that this error is related to insufficient memory.

To run `hsp.py` with that tree you would need to first export the `tutorial_placed_out/tree.qza ` file to newick format with `qiime tools export`, which might give you a more useful error message.

**Comment by YakunWang-0125** [comment]
> Hey there,
> How much RAM do you have? I would guess that this error is related to insufficient memory.
> To run hsp.py with that tree you would need to first export the tutorial_placed_out/tree.qza  file to newick format with qiime tools export, which might give you a more useful error message.

Thanks for you to help me understand my problem! I have run the command, the error message is about RAM. Maybe I should change a large memory band to solve it. Thanks your help! Best wishes!
